### DISCUSSION TITLE
Am I doing something wrong?  Trying to get sockets to work..

### DISCUSSION THREAD

**Discussion by amnuts** [shivammathur/setup-php#286] [Q&A / Help] [answered]
I'm trying to set up my first action, which looks like:

```
name: CI

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.3'
                  tools: pecl, phpunit, phpcs, phpmd
                  extensions: mbstring, intl, sockets, sodium, zip
            - name: Install dependencies
              uses: php-actions/composer@master
              with:
                  ssh_key: ${{ secrets.CI_SECRET }}
                  ssh_key_pub: ${{ secrets.CI_PUBLIC }}
            - name: Dump autoload
              uses: php-actions/composer@master
              with:
                  command: dump-autoload
                  only_args: --no-dev --no-interaction --classmap-authoritative
            - name: PHPUnit Tests
              uses: php-actions/phpunit@v8
              with:
                  configuration: phpunit.xml
                  args: --coverage-text
```

The setup and everything appears to work.  For exampe, when I look at the workflow I see this output:

```
==> Setup PHP
✓ PHP Switched to PHP 7.3.21

==> Setup Tools
✓ composer Added
✓ PECL Added
✓ phpunit Added
✓ phpcs Added
✓ phpmd Added

==> Setup Extensions
✓ mbstring Enabled
✓ intl Enabled
✓ sockets Enabled
✓ sodium Enabled
✓ zip Enabled
```

But when it comes to actually installing my composer stuff I get this error:

```
  Problem 1
    - Installation request for php-amqplib/php-amqplib v2.12.0 -> satisfiable by php-amqplib/php-amqplib[v2.12.0].
    - php-amqplib/php-amqplib v2.12.0 requires ext-sockets * -> the requested PHP extension sockets is missing from your system.
  Problem 2
    - php-amqplib/php-amqplib v2.12.0 requires ext-sockets * -> the requested PHP extension sockets is missing from your system.
```

Which would seem to suggest that the sockets bit didn't work.  Was there something else I should have added to the action in order to make this work?
