### DISCUSSION TITLE
Private repos?

### DISCUSSION THREAD

**Discussion by amnuts** [shivammathur/setup-php#287] [Q&A / Help] [answered]
Sorry, yet another question as I try to work through things... 😄   This time it's about using private repos.

I'm playing around with the actions on my personal account and I'm trying to pull in a private repository from another account which is an organisation to which I belong and my user account has all the right read/write permissions for the repos there.

I've set up a Personal Access Token under on my personal account and added that as a 'secret' to my test repo.  I'm now trying something like this:

```
name: CI

on: [ push ]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    tools: pecl, phpunit, phpcs, phpmd
                    extensions: mbstring, intl, sockets, sodium, zip
                env:
                    COMPOSER_TOKEN: ${{ secrets.COMPOSER_KEY }}

            -   name: Authenticate composer
                run: composer config -g github-oauth.github.com ${{ secrets.COMPOSER_KEY }}

            -   name: Install dependencies
                run: composer install --no-progress --no-suggest --prefer-dist
```

Everything works until it gets to the private repo, and then it complains that the repo cannot be found (I can copy/paste the 'not found' url and it can be found just fine).

Clearly I'm not doing something right here, so any advice would be appreciated, thanks!

**Comment by shivammathur** [comment, marked as answer]
Add this step before `composer install`

```yaml
- name: Add SSH key
  uses: webfactory/ssh-agent@v0.4.1
  with:
    ssh-private-key: ${{ secrets.CI_SECRET }}
```

Make sure you have added the ssh key in `CI_SECRET` to your organization.

Also make sure you have added the private repository in `composer.json`
```json
{
  "repositories": [
    { "type": "vcs", "url": "git@github.com:your_org/privaterepo" },
  ],
}
```

**Update:** Removed step to add `github.com` to `known_hosts` as webfactory/ssh-agent does that.
