### DISCUSSION TITLE
Dependency installation fails

### DISCUSSION THREAD

**Discussion by abenerd** [shivammathur/setup-php#290] [Q&A / Help]
I have a symfony app on which I want to run my tests and phpstan but when I try to install phpunit via the symfony bridge it always fails in the phpunit job, in the phpstan job tho it always succeeds. I thought that maybe the cache might be interfering so I'm using different keys but this does not appear to be the case. And the error message is also utterly uninformative. Does anyone know why this is happening?

```
Writing lock file
Generating optimized autoload files
25 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
##[error]The operation was canceled.
```

```yaml
name: PHP Composer

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4]
        experimental: [false]
        include:
          -  php: 8.0
             experimental: true

    services:
      postgres:
        image: postgres:12.4-alpine
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-php${{ matrix.php }}-
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader
          php bin/phpunit install --colors=never
      
      - name: Prepare database
        run: |
          php bin/console doctrine:schema:update --force
          php bin/console doctrine:fixtures:load --no-interaction
      - name: Run PHPUnit tests
        continue-on-error: ${{ matrix.experimental }}
        run: php bin/phpunit

  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: xdebug

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-php7.4-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php7.4-
      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader
          php bin/phpunit install --colors=never
      - name: Run phpstan
        run: php vendor/bin/phpstan analyse
```
