### DISCUSSION TITLE
PHP/WP and Cypress - Start web server

### DISCUSSION THREAD

**Discussion by KevinBatdorf** [shivammathur/setup-php#360] [Q&A / Help] [answered]
I'm new to this so please go easy on me! Not sure where my bottleneck is so thought I'd try asking here first. 

Basically, I want to create a workflow for browser testing a WP Plugin. The GH repo would be the plugin itself.

I'm trying to:

1. Install WP 
1. Move the repo to a sub directory
1. Install cypress
1. Run Cypress

The last step is failing as Cypress is getting a 404. 

I'm thinking I need to start a PHP server? Do I need to use nginx service maybe? 

I'm not sure so if anyone has a tip I'm all ears. I'll try anything.

Here's where I am now: https://github.com/KevinBatdorf/gh-action-wp/runs/1521814526?check_suite_focus=true

**Comment by shivammathur** [comment, marked as answer]
Hi @KevinBatdorf,
Here are some changes you should do in your workflow

1) Yes, you need to start the PHP server before running Cypress.

```yml
name: Run PHP server
run: nohup php -S localhost:8080 > php.log 2>&1 &
```

2) Specify `CYPRESS_baseUrl` instead of `CYPRESS_port` in `cypress-io/github-action` step.
```yml
- uses: cypress-io/github-action@v2
  with:
    install: false
  env:
    CYPRESS_baseUrl: http://localhost:8080/index.php
```

3) Setup PHP supports installing `wp-cli`, so you can specify it in tools input and remove `Download WP-CLI` and `Install WP-CLI` steps.
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '${{ matrix.php }}'
    extensions: mysql, zip
    coverage: none
    tools: composer, wp-cli
```

diff - https://github.com/shivammathur/test-setup-php/commit/6898e9cd07149c7ffa9b149108e73695462cfe99
Test workflow - https://github.com/shivammathur/test-setup-php/actions/runs/409987703/workflow
