### DISCUSSION TITLE
phpcs with cs2pr report

### DISCUSSION THREAD

**Discussion by matthieuleorat** [shivammathur/setup-php#361] [Q&A / Help] [answered]
Hello,
i try to use phpcs with cs2pr formatting.
Here an extract of my ci.yml file
https://github.com/matthieuleorat/bankAccount/blob/issue/31/.github/workflows/ci.yml
```yml
- name: Setup PHP with intl
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl-66.1
          tools: composer:v1, cs2pr, phpcs, phpstan
          coverage: xdebug
      - uses: actions/checkout@v2
[...]
- name: Run phpcs
        run: phpcs -q --report=checkstyle src | cs2pr
```

The list of errors is nicely displayed, but I cannot see the refering file/line. 
When I click on the error's number, my url change to something like:https://github.com/matthieuleorat/bankAccount/pull/88/checks?check_run_id=1529248903#step:8:246 but nothing happen.

I feel a popin with details is missing, but i don't know if I am doing something wrong, or if there is a bug

I am on ubuntu 18.04, tested with firefox 83.0 and Chromium 87.0.4280.66

**Comment by shivammathur** [comment, marked as answer]
Go to https://github.com/matthieuleorat/bankAccount/pull/88/checks?check_run_id=1529248903
and click where it says 11.

![image](https://user-images.githubusercontent.com/1571086/101756914-8ad02b00-3afc-11eb-9900-bc09f41f3894.png)

Then you can find the file names in the annotations

![image](https://user-images.githubusercontent.com/1571086/101757166-d2ef4d80-3afc-11eb-886d-24c215ef47fc.png)

**Reply by matthieuleorat** [reply]
Thank you for your answer and for your work on this project !

**Comment by jrfnl** [comment]
@matthieuleorat I totally with you on this being annoying, so a while back I added [a code sample to the CS2PR readme](https://github.com/staabm/annotate-pull-request-from-checkstyle#using-php_codesniffer) for how to achieve this.


```yaml
      - name: Check PHP code style
        continue-on-error: true
        run: phpcs --report-full --report-checkstyle=./phpcs-report.xml

      - name: Show PHPCS results in PR
        run: cs2pr ./phpcs-report.xml
```

The first command will show the normal report, the second command will pipe the report through so issues will be displayed in-line in PRs.

The `continue-on-error` is only to ensure that the cs2pr command will still be run. And the cs2pr command will fail the build if it has something to display.
