### DISCUSSION TITLE
Self hosted action fails on linux.sh

### DISCUSSION THREAD

**Discussion by Steveb-p** [shivammathur/setup-php#410] [Q&A / Help] [answered]
When trying to build and run a github runner using the docs: https://github.com/shivammathur/setup-php/wiki/Dockerized-self-hosted-runner-on-Ubuntu

I keep getting an error: 

```
Run shivammathur/setup-php@2.9.0
  with:
    php-version: 7.4
    coverage: none
    extensions: pdo_sqlite, gd
    tools: cs2pr
  env:
    runner: self-hosted
Error: EACCES: permission denied, open '/opt/hostedtoolcache/linux.sh'
```

Is the setup-php on self hosted still supported?

**Comment by shivammathur** [comment]
Yes, it is supported.
Can you provide your Dockerfile for testing.

**Reply by Steveb-p** [reply]
@shivammathur haven't really changed it much from the docs: (COPY I've added later on - isn't working both with and without it)

```Dockerfile
FROM shivammathur/node:focal-slim
# ubuntu:focal, ubuntu:bionic and ubuntu:xenial would also work
# shivammathur/node docker images are optimised for setup-php

ARG RUNNER_VERSION=2.277.1
ARG RUNNER_URL=https://github.com/foo/bar
ARG RUNNER_TOKEN=tkn

RUN set -ex && apt-get update && apt-get install -y ca-certificates curl gnupg iputils-ping libicu-dev sudo --no-install-recommends

RUN adduser --disabled-password --gecos '' runner \
  && usermod -aG sudo runner \
  && mkdir -m 777 -p /home/runner \
  && sed -i 's/%sudo\s.*/%sudo ALL=(ALL:ALL) NOPASSWD : ALL/g' /etc/sudoers

USER runner
WORKDIR /home/runner

RUN sudo curl -o runner.tar.gz -sSL https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz \
  && sudo tar xf runner.tar.gz \
  && sudo bash ./bin/installdependencies.sh || true

COPY ./src/scripts/ /opt/hostedtoolcache/

CMD [ "bash", "-c", "./config.sh --url ${RUNNER_URL} --token ${RUNNER_TOKEN}; ./run.sh; sleep infinity"]

```

Here is my GH action:
```yaml
name: Code Style

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Code Style
    runs-on: "self-hosted"

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP Action
      uses: shivammathur/setup-php@2.9.0
      with:
        php-version: '7.4'
        coverage: none
        extensions: pdo_sqlite, gd
        tools: cs2pr
      env:
        runner: self-hosted

    - uses: "ramsey/composer-install@v1"
      with:
        dependency-versions: "highest"
        composer-options: "--prefer-dist --no-progress --no-suggest"

    - id: files
      uses: jitterbit/get-changed-files@v1

    - name: Run test suite
      run: composer run-script --timeout=600 php-cs -- --format=checkstyle ${{ steps.files.outputs.added_modified }} | cs2pr

```
