### DISCUSSION TITLE
PHPUnit problem matchers not showing up

### DISCUSSION THREAD

**Discussion by dityaaa** [shivammathur/setup-php#451] [Q&A / Help] [answered]
So, I've been trying all night long to setup PHPUnit with problem matchers on Laravel app.
What I have tried is add some flags to PHPUnit (--debug, --verbose, and also --colors=never), but whenever test fail, it didn't show up on annotation list

![image](https://user-images.githubusercontent.com/25661768/116766789-85955d80-aa56-11eb-9471-29fbc0f198be.png)

This is my workflow file (I removed some jobs in this file to make it shorter)
```
name: Laravel

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  feature-tests:
    name: Feature tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out respository code
      uses: actions/checkout@v2
      
    - name: Setup PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: bcmath, ctype, dom, fileinfo, json, mbstring, tokenizer, xml
        tools: composer, phpunit
        
    - name: Setup problem matchers for PHP
      run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      
    - name: Setup problem matchers for PHPUnit
      run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      
    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Prepare application
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        php artisan key:generate
        chmod -R 777 storage bootstrap/cache
        mkdir -p database
        touch database/database.sqlite
        
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: phpunit
```

This is the step output
![image](https://user-images.githubusercontent.com/25661768/116767073-0c970580-aa58-11eb-957c-d2eb14b50b33.png)

Is there anything wrong that I've done so far?

**Comment by shivammathur** [comment, marked as answer]
@dityaaa 
Current problem matcher patterns in [`phpunit.json`](https://github.com/shivammathur/setup-php/blob/8e5cc09df9476e32ce8d33e916fcab0b192ef9c9/src/configs/phpunit.json) do not support custom error messages in assertions.


You can use the `teamcity` reporter in `phpunit` and `mheap/phpunit-matcher-action` GitHub Action to generate annotations
```yml
- name: Configure matchers
  uses: mheap/phpunit-matcher-action@v1
- name: Run Tests
  run: phpunit --teamcity Tests
```
