### DISCUSSION TITLE
How do I enable runkit extension?

### DISCUSSION THREAD

**Discussion by danon** [shivammathur/setup-php#583] [Q&A / Help] [answered]
I would like to use runkit extension, is this possible now?

**Comment by shivammathur** [comment, marked as answer]
Which php versions do you want to test on? For 7.2 and above you can just specify `runkit7` in the extensions input.

**Reply by danon** [reply]
For 7.1, 7.2 and 7.3.

**Reply by shivammathur** [reply]
```yml
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3']
        extensions: ['runkit7']
        include:
         - php: '7.1'
           extensions: 'runkit7-3.1.0a1'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}
            extensions: ${{ matrix.extensions }}
```
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/2078226971/workflow
