### DISCUSSION TITLE
When will PHP v8.1.10 be available?

### DISCUSSION THREAD

**Discussion by PHLAK** [shivammathur/setup-php#644] [Q&A / Help] [answered]
When will we get PHP [v8.1.10](https://www.php.net/downloads.php#v8.1.10)? This version has has been out for over two weeks at this point and it [fixes a memory leak](https://github.com/php/php-src/issues/9266) that we need to address some issues in our CI pipeline.

**Comment by shivammathur** [comment, marked as answer]
It was only built 2 days ago in `ppa:ondrej/php` which is used for ubuntu builds.
https://launchpad.net/~ondrej/+archive/ubuntu/php/+index?batch=75&direction=backwards&start=225
so it will be there in the next GitHub action images.

If you want it now, please specify `update` environment variable as `true` in your `setup-php` step.
```yml
- name: Setup PHP with latest versions
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.1'
  env:
    update: true
```
https://github.com/shivammathur/setup-php#force-update-setup
