### DISCUSSION TITLE
Installing php/pecl-text-wddx extension

### DISCUSSION THREAD

**Discussion by petersendidit** [shivammathur/setup-php#669] [Q&A / Help] [answered]
I have followed the page in the wiki to [add an extension from source](https://github.com/shivammathur/setup-php/wiki/Add-extension-from-source#add-extension-from-github) and am not having any luck with it working.  We have a php v7.4 app that still is using wddx for a bit longer.  From reading the wiki page I would expect something like this to work:

```yml
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mysqli, mbstring, intl, iconv, ldap, xml, zip, gd, pdo_mysql, bcmath, exif, pcntl, soap, sockets, xdebug, 'php/pecl-text-wddx'
          tools: composer:v2
```

But any time I run the action I get this output:

```
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh
==> Setup PHP
✓ PHP Installed PHP 7.4.33
==> Setup Extensions
✓ mysql Enabled
✓ mbstring Enabled
✓ intl Enabled
✓ xml Enabled
✓ zip Enabled
✓ gd Enabled
✓ pdo_mysql Enabled
✓ bcmath Enabled
✓ exif Enabled
✓ pcntl Enabled
✓ soap Enabled
✓ sockets Enabled
✓ xdebug Enabled
/home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/extensions/source.sh: line 9: php/pecl_CONFIGURE_PREFIX_OPTS: invalid variable name
/home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/extensions/source.sh: line 9: php/pecl_CONFIGURE_OPTS: invalid variable name
/home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/extensions/source.sh: line 9: php/pecl_CONFIGURE_SUFFIX_OPTS: invalid variable name
/home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/extensions/source.sh: line 9: php/pecl_LIBS: invalid variable name
/home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/extensions/source.sh: line 9: php/pecl_LINUX_LIBS: invalid variable name
✗ php/pecl-textwddx Could not install php/pecl-textwddx on PHP 7.4.33
```

One thing I noticed is that even though the repo is `php/pecl-text-wddx` the output shows `php/pecl-textwddx`

Is there something I am doing wrong or have I hit some bug?
