### DISCUSSION TITLE
Custom installation of php module

### DISCUSSION THREAD

**Discussion by niden** [shivammathur/setup-php#677] [Q&A / Help] [answered]
I seem to be having an issue with installing an extension from a GitHub repository and hoping for some pointers

I checked this guide: https://github.com/shivammathur/setup-php/wiki/Add-extension-from-source and it seems all I need to do is:

```
      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: apcu, ...., niden/phalcon-module
          ini-values: apc.enable_cli=on, session.save_path=/tmp
          tools: pecl
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PHALCON_PATH: ext
```
In short, I want the extension from `niden/phalcon-module` and the installation files are located in `ext/`

Sadly that does not work. I am getting 

```
/home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/extensions/source.sh: line 9: 
niden/phalcon_CONFIGURE_PREFIX_OPTS: invalid variable name
```

(and other lines with errors).

I even tried `niden/phalcon-module@master` and that did not work either.

My workflow is here: https://github.com/niden/phalcon/blob/T38-url/.github/workflows/continuous-integration.yml#L58
Repo of the module: https://github.com/niden/phalcon-module  (code in `ext/`)
Failed run: https://github.com/niden/phalcon/actions/runs/3721548162/jobs/6311773885

Any pointers are more than appreciated.

Thank you.
