### DISCUSSION TITLE
some warning when installing PHP

### DISCUSSION THREAD

**Discussion by mimmi20** [shivammathur/setup-php#696] [Q&A / Help] [answered]
In my tests in one project I get these warnings when installing PHP.

```shell
Run shivammathur/setup-php@2.24.0
  with:
    php-version: 8.1
    extensions: none, phar, json, opcache, dom, iconv, intl, mbstring, simplexml, tokenizer, xml, xmlwriter :openssl, :mongodb, :amqp, :sockets, :curl
    ini-values: opcache.enable=1, opcache.fast_shutdown=0, zend.assertions=1, assert.exception=On, intl.default_locale=de, intl.use_exceptions=1, zend.exception_ignore_args=0
    coverage: none
    tools: composer:v2
    ini-file: production
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/2.24.0/src/scripts/run.sh

==> Setup PHP
✓ PHP Found PHP 8.1.14

==> Setup Extensions
✓ none Disabled all shared extensions
✓ phar Enabled
✓ json Enabled
✓ opcache Enabled
✓ dom Enabled
✓ iconv Enabled
✓ intl Enabled
✓ mbstring Enabled
✓ simplexml Enabled
✓ tokenizer Enabled
✓ xml Enabled
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module "dom" is already loaded in Unknown on line 0
PHP Warning:  Module "iconv" is already loaded in Unknown on line 0
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
PHP Warning:  Module "mbstring" is already loaded in Unknown on line 0
PHP Warning:  Module "SimpleXML" is already loaded in Unknown on line 0
PHP Warning:  Module "tokenizer" is already loaded in Unknown on line 0
PHP Warning:  Module "xml" is already loaded in Unknown on line 0
✓ xmlwriter Installed and enabled
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module "dom" is already loaded in Unknown on line 0
PHP Warning:  Module "iconv" is already loaded in Unknown on line 0
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
PHP Warning:  Module "mbstring" is already loaded in Unknown on line 0
PHP Warning:  Module "SimpleXML" is already loaded in Unknown on line 0
PHP Warning:  Module "tokenizer" is already loaded in Unknown on line 0
PHP Warning:  Module "xml" is already loaded in Unknown on line 0
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module "dom" is already loaded in Unknown on line 0
PHP Warning:  Module "iconv" is already loaded in Unknown on line 0
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
PHP Warning:  Module "mbstring" is already loaded in Unknown on line 0
PHP Warning:  Module "SimpleXML" is already loaded in Unknown on line 0
PHP Warning:  Module "tokenizer" is already loaded in Unknown on line 0
PHP Warning:  Module "tokenizer" is already loaded in Unknown on line 0
PHP Warning:  Module "xml" is already loaded in Unknown on line 0
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module "dom" is already loaded in Unknown on line 0
PHP Warning:  Module "iconv" is already loaded in Unknown on line 0
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
PHP Warning:  Module "mbstring" is already loaded in Unknown on line 0
PHP Warning:  Module "SimpleXML" is already loaded in Unknown on line 0
PHP Warning:  Module "tokenizer" is already loaded in Unknown on line 0
PHP Warning:  Module "xml" is already loaded in Unknown on line 0
✓ :curl Disabled

==> Setup Tools
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module "dom" is already loaded in Unknown on line 0
PHP Warning:  Module "iconv" is already loaded in Unknown on line 0
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
PHP Warning:  Module "mbstring" is already loaded in Unknown on line 0
PHP Warning:  Module "SimpleXML" is already loaded in Unknown on line 0
PHP Warning:  Module "tokenizer" is already loaded in Unknown on line 0
PHP Warning:  Module "xml" is already loaded in Unknown on line 0
✓ composer Added composer 2.[5](https://github.com/mimmi20/monolog-factory/actions/runs/4095850504/jobs/7063137133#step:5:5).2

==> Setup Coverage
✓ none Disabled Xdebug and PCOV

==> Add php.ini values
✓ opcache.enable=1 Added to php.ini
✓ opcache.fast_shutdown=0 Added to php.ini
✓ zend.assertions=1 Added to php.ini
✓ assert.exception=On Added to php.ini
✓ intl.default_locale=de Added to php.ini
✓ intl.use_exceptions=1 Added to php.ini
✓ zend.exception_ignore_args=0 Added to php.ini

==> #StandWithUkraine
✓ read-more https://setup-php.com/support-ukraine
...
Run composer require --no-update psr/log:^[2](https://github.com/mimmi20/monolog-factory/actions/runs/4095850504/jobs/7063137133#step:6:2)
  composer require --no-update psr/log:^2
  shell: /usr/bin/bash -e {0}
  env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module "dom" is already loaded in Unknown on line 0
PHP Warning:  Module "iconv" is already loaded in Unknown on line 0
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
PHP Warning:  Module "mbstring" is already loaded in Unknown on line 0
PHP Warning:  Module "SimpleXML" is already loaded in Unknown on line 0
PHP Warning:  Module "tokenizer" is already loaded in Unknown on line 0
PHP Warning:  Module "xml" is already loaded in Unknown on line 0
./composer.json has been updated
...
Run vendor/bin/phpunit -c phpunit.xml --no-coverage
  vendor/bin/phpunit -c phpunit.xml --no-coverage
  shell: /usr/bin/bash -e {0}
  env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
    CACHE_RESTORE_KEY: Linux-php-8.1.14-composer---optimize-autoloader---prefer-dist---prefer-stable--v-highest-
    MSYS: winsymlinks:nativestrict
Cannot load Zend OPcache - it was already loaded
PHP Warning:  Module "dom" is already loaded in Unknown on line 0
PHP Warning:  Module "iconv" is already loaded in Unknown on line 0
PHP Warning:  Module "intl" is already loaded in Unknown on line 0
PHP Warning:  Module "mbstring" is already loaded in Unknown on line 0
PHP Warning:  Module "SimpleXML" is already loaded in Unknown on line 0
PHP Warning:  Module "tokenizer" is already loaded in Unknown on line 0
PHP Warning:  Module "xml" is already loaded in Unknown on line 0
Typed property DOMDocument::$documentElement must not be accessed before initialization
Error: Process completed with exit code 1.
```

The pipeline is defined as 
```
...
  tests-monolog-without-extensions:
    name: "UnitTests with PHPUnit for monolog/monolog 3 without extensions"

    needs: "ci"

    runs-on: "${{ matrix.operating-system }}"

    continue-on-error: false

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-20.04"
          - "ubuntu-22.04"

        php-version:
          - "8.1"
          - "8.2"

        dependencies:
          - "highest"
          - "lowest"

        psr-log-version:
          - "2"
          - "3"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          lfs: false
          persist-credentials: false

      - name: "Run CouchDB"
        timeout-minutes: 3
        continue-on-error: true
        uses: "cobot/couchdb-action@master"
        with:
          couchdb version: "2.3.1"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@verbose"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "none, phar, json, opcache, dom, iconv, intl, mbstring, simplexml, tokenizer, xml, xmlwriter, :openssl, :mongodb, :amqp, :sockets, :curl"
          ini-values: "opcache.enable=1, opcache.fast_shutdown=0, zend.assertions=1, assert.exception=On, intl.default_locale=de, intl.use_exceptions=1, zend.exception_ignore_args=0"
          coverage: "none"
          tools: "composer:v2"

      - name: "Require psr/log ${{ matrix.psr-log-version }}"
        run: "composer require --no-update psr/log:^${{ matrix.psr-log-version }}"

      - name: "Remove dependencies with composer"
        run: "composer remove --no-update --dev actived/microsoft-teams-notifier"

      - name: "Remove dependencies with composer"
        if: "matrix.psr-log-version >= '3'"
        run: "composer remove --no-update --dev graylog2/gelf-php"

      - name: "Update dependencies with composer"
        uses: "ramsey/composer-install@2.2.0"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--optimize-autoloader --prefer-dist --prefer-stable -v"

      - name: "Run unit tests with phpunit/phpunit"
        run: "vendor/bin/phpunit -c phpunit.xml --no-coverage"
...
```

Is something wrong with my configuration?
