### DISCUSSION TITLE
Add problem matcher for PHP automatically?

### DISCUSSION THREAD

**Discussion by markseuffert** [shivammathur/setup-php#706] [Ideas / RFC]
Hi, at the moment I add the [problem matcher for PHP](https://github.com/shivammathur/setup-php#problem-matchers) after the `setup-php` step. Here's an example:

```
- name: Setup PHP
  uses: shivammathur/setup-php@v2
    with:
      php-version: ${{ matrix.php }}
      extensions: curl, gd, mbstring, zip
      ini-file: development
- name: Setup problem matchers for PHP
  run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
```

I wonder if this could be done automatically in setup-php@v3?
