### DISCUSSION TITLE
How to install on Microsoft Hosted Action Runners?

### DISCUSSION THREAD

**Discussion by CxDevLead** [shivammathur/setup-php#727] [Q&A / Help] [answered]
I am trying to install PHP8.2 on Ubuntu 22 Microsoft hosted (Azure) action runner.

This YAML code fails on the line `-name: Setup PHP`

```
pool:
  vmImage: 'ubuntu-22.04'

variables:
  phpVersion: 8.2

steps:
  - name: Setup PHP
    id: setup-php
    uses: shivammathur/setup-php@v2
    displayName: 'Setup PHP version $(phpVersion)'
    with:
      php-version: '$(phpVersion)'
      coverage: none
```

What am I doing wrong?

**Comment by shivammathur** [comment, marked as answer]
@CxDevLead 

Azure pipelines are not supported directly as github actions don't work there.

We do have a wrapper around the action if you want to use it - [shivammathur/spc](https://github.com/shivammathur/spc)

Although I haven't tested this in Azure Pipelines, it should work

```yml
pool:
  vmImage: 'ubuntu-22.04'

variables:
  phpVersion: 8.2

steps:
  - displayName: 'Setup PHP version $(phpVersion)'
    script: |
      curl -sL https://github.com/shivammathur/spc/releases/latest/download/spc -o spc
      chmod +x spc
      sudo mv spc /usr/local/bin/
      spc --php-version "$(phpVersion)" --coverage "none"

```
