### DISCUSSION TITLE
Proxy problem?

### DISCUSSION THREAD

**Discussion by brunomgv** [shivammathur/setup-php#797] [Q&A / Help]
I'm trying to use setup-php into a self hosted github enterprise, and I'm receiving the following error:

```
Run shivammathur/setup-php@verbose
/usr/bin/bash /runner/_work/_actions/shivammathur/setup-php/verbose/src/scripts/run.sh

==> Setup PHP
chmod: cannot access '/tmp/install.sh': No such file or directory
bash: /tmp/install.sh: No such file or directory
✗ PHP Could not setup PHP [7](https://github.xxx.com/xxx/Reponame/actions/runs/97026/job/378832#step:5:8).3
Error: The process '/usr/bin/bash' failed with exit code 1
```

This is the action:
```
name: sonarqube

on:
  workflow_call:
    inputs:
      app_language:
        description: 3 letter name, used to identify the project's language
        type: string
        required: true
    secrets:
      sonar_token:
        description: SonarQube token
        required: true
      sonar_host_url:
        description: SonarQube host_url
        required: true

jobs:
  sonar_scan:
    if: |
      inputs.app_language == 'php'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@verbose
        with:
          php-version: "7.3"
      - name: Install dependencies with composer
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
          SONAR_HOST_URL: ${{ secrets.sonar_host_url }}
```

I'm considering using our company's proxy, which other projects utilize. Could you guide me on how to set this proxy, as I couldn't find relevant information in the documentation? Thank you.
