### DISCUSSION TITLE
Problem with Composer

### DISCUSSION THREAD

**Discussion by brunomgv** [shivammathur/setup-php#801] [Q&A / Help]
I'm trying to use setup-php into a self hosted github enterprise, and I'm receiving the following error:

```
Run shivammathur/setup-php@verbose
  with:
    php-version: 7.3
    ini-file: production
/bin/docker exec  0f51cfc15199485d67cb41a5157609e476cae01b8943c808677b442b1ffe67cb sh -c "cat /etc/*release | grep ^ID"
/usr/bin/bash /__w/_actions/shivammathur/setup-php/verbose/src/scripts/run.sh
Reading package lists...
Building dependency tree...
Reading state information...
apt-transport-https is already the newest version (2.0.10).
autoconf is already the newest version (2.69-11.1).
automake is already the newest version (1:1.16.1-4ubuntu6).
ca-certificates is already the newest version (20230311ubuntu0.20.04.1).
curl is already the newest version (7.68.0-1ubuntu2.20).
file is already the newest version (1:5.38-4).
g++ is already the newest version (4:9.3.0-1ubuntu2).
gcc is already the newest version (4:9.3.0-1ubuntu2).
gnupg is already the newest version (2.2.19-3ubuntu2.2).
jq is already the newest version (1.6-1ubuntu0.20.04.1).
make is already the newest version (4.2.1-1.2).
unzip is already the newest version (6.0-25ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
RUNNER_TOOL_CACHE=/tmp

==> Setup PHP
update-alternatives: update-alternatives: using /usr/bin/php-config7.3 to provide /usr/bin/php-config (php-config) in manual modeusing /usr/bin/php7.3 to provide /usr/bin/php (php) in manual mode

update-alternatives: using /usr/bin/phar7.3 to provide /usr/bin/phar (phar) in manual mode
update-alternatives: warning: skip creation of /usr/share/man/man1/php.1.gz because associated file /usr/share/man/man1/php7.3.1.gz (of link group php) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/php-config.1.gz because associated file /usr/share/man/man1/php-config7.3.1.gz (of link group php-config) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/phar.1.gz because associated file /usr/share/man/man1/phar7.3.1.gz (of link group phar) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/phpize.1.gz because associated file /usr/share/man/man1/phpize7.3.1.gz (of link group phpize) doesn't exist
update-alternatives: using /usr/bin/phpize7.3 to provide /usr/bin/phpize (phpize) in manual mode
update-alternatives: using /usr/bin/phar.phar7.3 to provide /usr/bin/phar.phar (phar.phar) in manual mode
update-alternatives: warning: skip creation of /usr/share/man/man1/phar.phar.1.gz because associated file /usr/share/man/man1/phar.phar7.3.1.gz (of link group phar.phar) doesn't exist

production
date.timezone=UTC
memory_limit=-1
xdebug.mode=coverage
php-version=7.3.33
✓ PHP Switched to PHP 7.3.33

==> Setup Tools
✗ composer Could not setup composer
Error: The process '/usr/bin/bash' failed with exit code 1
```

This is the action:

```
name: sonarqube

on:
  workflow_call:
    inputs:
      app_language:
        description: 3 letter name, used to identify the project's language
        type: string
        required: true
    secrets:
      us_sonar_token:
        description: SonarQube token
        required: true
      us_sonar_host_url:
        description: SonarQube host_url
        required: true

jobs:
  sonar_scan:
    if: |
      inputs.app_language == 'php'
    runs-on: [self-hosted, skylight, Linux]
    container:
      image: shivammathur/node:focal-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@verbose
        with:
          php-version: '7.3'
          tools: composer:v1
      - name: Install dependencies with composer
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
          SONAR_HOST_URL: ${{ secrets.sonar_host_url }}

```

I've already tested with:
tools: composer:v1
tools: composer:v2
php-version: "7.4"

Any thoughts?

**Comment by shivammathur** [comment]
If you run this on your self-hosted server, what is the output.

```bash
curl -o /tmp/composer.phar -vL https://github.com/shivammathur/composer-cache/releases/latest/download/composer-7.3-2.phar
```

If the connection fails, as you mentioned you would need a proxy, you can configure one following [this](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/using-a-proxy-server-with-self-hosted-runners) in your GitHub Actions workflow.

**Reply by brunomgv** [reply]
Hey @shivammathur, thanks for helping me to debug the issue. 

I'm using:
shivammathur/node:latest as image for the container;
shivammathur/setup-php@verbose
php 7.3

I configured the proxy envs and added an extra step to the workflow:

```
- name: Download Composer with debug output
        run: |
          curl -o /tmp/composer.phar -vL https://github.com/shivammathur/composer-cache/releases/latest/download/composer-7.3-2.phar 2>&1 | tee /tmp/composer_download.log && ls -lh /tmp/composer.phar
```

the output:
```
100 2795k  100 2795k    0     0  3400k      0 --:--:-- --:--:-- --:--:-- 3400k
* Connection #1 to host (nil) left intact
-rw-r--r--. 1 root root 2.8M Dec 13 20:15 /tmp/composer.phar
```

So, the file has been downloaded. But the Composer setup still doesn't work:
```
production
date.timezone=UTC
memory_limit=-1
xdebug.mode=coverage
php-version=7.3.33
✓ PHP Switched to PHP 7.3.33

==> Setup Tools
✗ composer Could not setup composer
Error: The process '/usr/bin/bash' failed with exit code 1
```

Here is the workflow:
```
name: sonarqube

env:
  http_proxy: "http://companyproxy:3128"
  https_proxy: "http://companyproxy:3128"
  no_proxy: "localhost,127.0.0.1,github.companyname.com"

on:
  workflow_call:
    secrets:
      sonar_token:
        description: SonarQube token
        required: true
      sonar_host_url:
        description: SonarQube host_url
        required: true

jobs:
  sonar_scan:
    runs-on: [self-hosted, Linux]
    container:
      image: shivammathur/node:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download Composer with debug output
        run: |
          curl -o /tmp/composer.phar -vL https://github.com/shivammathur/composer-cache/releases/latest/download/composer-7.3-2.phar 2>&1 | tee /tmp/composer_download.log && ls -lh /tmp/composer.phar
      - name: Setup PHP
        uses: shivammathur/setup-php@verbose
        with:
          coverage: "none"
          php-version: '7.3'
      - name: Install dependencies with composer
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
          SONAR_HOST_URL: ${{ secrets.sonar_host_url }}
```
