### DISCUSSION TITLE
Consider determining and enabling PHP extensions depending on requirements in `composer.json`

### DISCUSSION THREAD

**Discussion by localheinz** [shivammathur/setup-php#808] [Ideas / RFC]
**Describe the feature**

Similar to #629, perhaps it would be useful to disable all PHP extensions, and determine and enable PHP extensions depending on requirements in `composer.json`.

I understand that this could be a bit problematic, because some could have dependencies on PHP extensions that are not directly or indirectly documented in `composer.json`, for example:

- for running PHARs
- required by PHARs
- recommended by PHARs

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
n/a

**Describe alternatives**
Alternatives include manually disabling and then enabling all required PHP extensions.

**Additional context**
n/a

**Are you willing to submit a PR?**
n/a

**Comment by shivammathur** [comment]
I'm open to a PR that adds extensions based on `composer.json`. 

We can add an input like `extensions-file` that supports `composer.json` as an input along with any file with a list of extensions.

This can be combined with `none` in the extensions input to have the desired effect. But that can be dangerous as you mentioned removing all extensions might break phar tools that are used in the pipeline in case they are not in `composer.json`. 

Handling that would be the responsibility of the user. The action does try to enable extensions that are required for the supported tools though.

**Comment by localheinz** [comment]
Thank you for your feedback, @shivammathur  - perhaps it's too much work and not worth the effort, given the complications.

**Comment by jasongill** [comment]
We use Composer's built in [platform config option](https://getcomposer.org/doc/06-config.md#platform) to force our local environments and development environments to match our production server version.

This makes it easy to grab the appropriate version from composer.json and pass it to php-setup:
```
      - name: Get required PHP version
        uses: sergeysova/jq-action@v2
        id: php_version
        with:
          cmd: |
            jq '.config.platform.php' composer.json -r
      - name: Setup PHP runtime
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ steps.php_version.outputs.value }}"
```

Hope this helps someone else who is trying to find a way to force setup-php to match their configuration without having to keep their github actions yml up to date.
