### DISCUSSION TITLE
Getting exception on downloading sqlsrv extensions

### DISCUSSION THREAD

**Discussion by driesvints** [shivammathur/setup-php#835] [Q&A / Help] [answered]
For the following workflow:

```
  windows_tests:
    runs-on: windows-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]
        laravel: [10, 11]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - Windows

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo, sqlsrv, pdo, pdo_sqlsrv,
          ini-values: error_reporting=E_ALL, memory_limit=512M
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework=~${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit
```

I get this error when it's attempting to download the `sqlsrv, pdo, pdo_sqlsrv,` extension:

<img width="1083" alt="Screenshot 2024-04-19 at 11 01 00" src="https://github.com/shivammathur/setup-php/assets/594614/07617714-7cee-43c7-bea6-a6bb7dbaa961">

I'm most likely doing something obviously wrong. I suspect these extensions not to be available on a windows build? If so, how do I make sure the `pdo_sqlsrv` extension is installed and working?

Related PR: https://github.com/laravel/installer/pull/334
