### DISCUSSION TITLE
Setting the timezone ini value doesn't seem to be functional

### DISCUSSION THREAD

**Discussion by Rockylars** [shivammathur/setup-php#901] [Q&A / Help] [answered]
I've got a simple Laravel project that locally uses Docker with a supplied ini file in the docker-compose.yml file.
```yaml
example-php-service:
  volumes:
    - ./docker/custom.ini:/usr/local/etc/php/conf.d/zzz-last-loaded.ini
```
This ini contains a timezone setter `date.timezone="Europe/Amsterdam"` as otherwise the timezone would be `UTC`, it isn't set in Laravel. Without it, my test for "pull records from an hour ago, based on `now()->toImmutable()`" would fail. With it, my tests now succeed.

Now i wanted to repeat this on my test runner by using this config.
```
-   name: Setup PHP with tools
    timeout-minutes: 1
    uses: shivammathur/setup-php@2.31.1
    with:
        php-version: 8.2
        extensions: none, bcmath, Core, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, json, libxml, mbstring, mongodb, mysqlnd, openssl, pcre, PDO, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, random, readline, redis, Reflection, session, SimpleXML, soap, sodium, SPL, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, Zend OPCache, zip, zlib
        coverage: none
        ini-values: memory_limit="1G", date.timezone="Europe/Amsterdam"
        tools: composer:v2
```
Which loads it in as shown by the GitHub log
```
==> Add php.ini values
✓ memory_limit=1G Added to php.ini
✓ date.timezone=Europe/Amsterdam Added to php.ini
```
But then when pulling the timezone from a timestamp in a PHPUnit step, it is still set as `UTC` (note that it did also say this locally but the tests did get fixed), where as it fixed it in my Docker set up just fine.

What would be the cause? For now i can fix it in the code by doing this, but it is weird that my ini value isn't respected.
```php
protected function setUp(): void
{
    parent::setUp();
    date_default_timezone_set('Europe/Amsterdam');
}
```
