### DISCUSSION TITLE
Job randomly hangs

### DISCUSSION THREAD

**Discussion by gaborjonasecd** [shivammathur/setup-php#909] [Q&A / Help] [answered]
Hi,
We've recently move to Github, and using self-hosted runners (Ubuntu 22.04).
The first issue we've had when installing composer package:
```sh
Error: The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly
```
Which was fixed by adding
```yml
env:
  HOME: /home/github
```

The jobs work fine, but others randomly hang with:
```sh
==> Setup PHP
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```

```yml
name: "Continuous Integration"

on:
  push:

concurrency:
  group: group-${{ github.ref }}
  cancel-in-progress: true

env:
  COLUMNS: 120
  HOME: /home/github
  COMPOSER_ALLOW_SUPERUSER: 1

jobs:
  php-cs-fixer:
    name: PHP Coding Standards
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: curl, gd, redis
          ini-values: memory_limit=-1, error_reporting=E_ALL, display_errors=On
          tools: composer
          coverage: none
        env:
          fail-fast: true
          runner: self-hosted

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer packages
        run: composer install --classmap-authoritative

      - name: Run php-cs-fixer
        run: vendor/bin/php-cs-fixer check --diff
```
