### DISCUSSION TITLE
Wrong mongodb version install out of nowhere

### DISCUSSION THREAD

**Discussion by Rockylars** [shivammathur/setup-php#960] [Q&A / Help]
Yesterday i was working on some code and it worked fine as it always has, i'm still using Ubuntu 22.04 and pecl Mongo 1.17.0

![image](https://github.com/user-attachments/assets/419e7514-06fc-4299-9942-7695761c8e00)

Today i make a commit that changes nothing on composer but does add some extra flags to my PHPUnit steps, but suddenly it's trying to install pecl Mongo 2.1.0. I've locked it to the version now but it makes it take a whole extra minute.

![image](https://github.com/user-attachments/assets/fb6c9385-580f-4beb-ac39-17a9fd7b153a)

If you remove the version from the mongo install, it runs fine but installs the wrong version, without it it will take an extra minute to install it but will eventually install it.

```
        -   name: Setup PHP with tools
            timeout-minutes: 1
            uses: shivammathur/setup-php@2.34.0
            with:
                php-version: 8.2
                extensions: none, bcmath, Core, ctype, curl, date, dom, exif, fileinfo, filter, hash, iconv, json, libxml, mbstring, mongodb-1.17.0, mysqlnd, openssl, pcre, PDO, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, random, readline, redis, Reflection, session, SimpleXML, sodium, SPL, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, Zend OPCache, zlib
                coverage: none
                ini-values: memory_limit="1G"
                tools: composer:v2
```

I do use a mongo service as well, but that one hasn't changed.

```
      mongo:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        ports:
          - 27017:27017
```

Does anyone have any idea? I haven't changed anything, i was always using setup-php 2.31.1, upping it to 2.34.0 also changed no behaviour.
