### DISCUSSION TITLE
Unable to install specific version of symfony-cli

### DISCUSSION THREAD

**Discussion by marmorag** [shivammathur/setup-php#970] [Ideas / RFC]
**Describe the bug**
I am unable to install a specific version of the `symfony-cli` tool. Trying both `symfony:5.9.1` and `symfony:v5.9.1` result in the action installing the latest version available

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`ubuntu-latest`

**PHP versions**
`8.1`

**To Reproduce**
```yaml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: 8.1
    extensions: iconv, intl
    tools: symfony:5.9.1
```

**Expected behavior**

`setup-php` action installing `symfony-cli` in v5.9.1

**Screenshots/Logs**

![image](https://github.com/user-attachments/assets/438c1ca6-15f2-4492-a316-abe7b675e5a7)

**Additional context**

I've tried multiple syntax/tool name, all resulting in the actions installing the latest version

```yaml
name: Test setup php

on:
  workflow_dispatch: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [symfony, symfony-cli]
        version: ["v5.9.1", "5.9.1"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: iconv, intl
          tools: ${{ matrix.tool }}:${{ matrix.version }}

```

**Are you willing to submit a PR?**
