### ISSUE TITLE
Update xdebug version to 2.8.1 or new

### ISSUE THREAD

**Issue by Smolevich** [shivammathur/setup-php#109]
**Is your feature request related to a problem? Please describe.**
Update xdebug version >2.8.0 because tests slow executed. See [PR in xdebug](https://github.com/xdebug/xdebug/pull/517/files#diff-c23a49b975bde4591084a08c43ee6c45L1055)

**Describe the solution you'd like**

**Describe alternatives you've considered**
I try to install another version of xdebug, but i catch segmentation fault. See [step](https://github.com/Smolevich/graphql-php/commit/c866829561bacbf67ad6b19ede7feeab4ac05120/checks?check_suite_id=349596084)

**Additional context**

**Comment by shivammathur** [comment]
@Smolevich 
while I debug why this segmentation fault is there, you can bypass this and successfully update `Xdebug` using the step below. Here is a test [workflow](https://github.com/shivammathur/test-setup-php/commit/871c9ba8ceeae3ceb8831a5670d6142faae80bbf/checks?check_suite_id=349711573)

```yml
- name: Update Xdebug
  run: sudo pecl install xdebug-2.9.0
  continue-on-error: true
```

**Comment by Smolevich** [comment]
@shivammathur thanks for quick reply and help

**Comment by shivammathur** [comment]
@Smolevich This issue is not related to this PHP action. It is with `PECL` or `Xdebug`. When the extension is loaded after installation if older version is already loaded to gives the error. You can run the action with `coverage: none` install `Xdebug` later to get the latest release without errors. 

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@develop
  with:
    php-version: ${{ matrix.php-versions }}
    coverage: none
    pecl: true
- name: Install Xdebug
  run: sudo pecl install -f xdebug
```
