### ISSUE TITLE
Install custom extension

### ISSUE THREAD

**Issue by hotrush** [shivammathur/setup-php#116]
Hi. Do you know any way to install custom extension from git repository (not pecl or apt).

For examle we use gearman in our project, but it's pecl version is super outdated. So, we use this one https://github.com/wcgallego/pecl-gearman

**Comment by shivammathur** [comment]
`ext-gearman` should now install correctly on `ubuntu` after 1.6.1. 
Here is a [test run](https://github.com/shivammathur/test-setup-php/commit/86626c3ca96c3504266f932d28cb7529ecbad937/checks?check_suite_id=358685444)
```yml
uses: shivammathur/setup-php@v1
with:
  php-version: '7.4'  
  extensions: gearman
```
