### ISSUE TITLE
Slow execution of tests with coverage set to none

### ISSUE THREAD

**Issue by ewerkema** [shivammathur/setup-php#123]
**Describe the bug**
It seems that the execution of tests is too slow on Github Actions. Local execution takes 50-60 seconds without test coverage. On GitHub actions it takes ~30 minutes. From my local installation I know that this slow execution is caused by XDebug (even if test coverage is disabled), but the Github Actions settings include `coverage: none` and should also disable XDebug. Do you have any idea what could cause this performance difference?

**To Reproduce**
GitHub Action `.yml` file:
```
name: Laravel CI

on:
  pull_request:
    branches:
      - master

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy ENV Laravel Configuration for CI
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: '7.2'
        coverage: none
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        php artisan migrate
    - name: Install Laravel Passport
      run: php artisan passport:install
    - name: Yarn production
      run: |
        yarn install --silent
        yarn run prod
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit --no-coverage
```

**Expected behavior**
I expect the ~300 test cases to finish within 5 minutes. The actual result is a time around 30 minutes (see screenshot below).

![Screenshot Capture - 2019-12-19 - 16-03-36](https://user-images.githubusercontent.com/16745495/71183925-211a9980-2279-11ea-961a-37681638b5f6.png)

**Comment by Jeckerson** [comment]
Try to remove xdebug before running the tests:
`apt-get remove php-xdebug`

**Comment by ewerkema** [comment]
Thanks @Jeckerson! Running `sudo apt-get remove php-xdebug` indeed solves the slow execution. The test cases have improved from ~30 minutes to ~3 minutes.

Shouldn't this be default behavior, since the docs actually state that:

> It will disable Xdebug, which will have a positive impact on PHP performance.?

**Comment by shivammathur** [comment]
@ewerkema 
Please add this step after the setup step, and let me know the output
```yml
- name: Test version and extensions
  run: php -v && php -m
```

Also if you can give me a link to your repository, it will help me debug what is causing this.

**Comment by shivammathur** [comment]
@ewerkema 
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v1
  with:
    php-version: '7.2'
    coverage: none
```
After `1.6.2` `coverage: none` will not just disable but completely remove `ext-xdebug` and `ext-pcov`.
Please test and let me know
