### ISSUE TITLE
Pecl not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by ruudboon** [shivammathur/setup-php#129]
I'm trying to use Pecl under windows. The same setup works fine under linux MacOS
```
 install-windows:
    needs: build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [windows-latest]
        php-versions: ['7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, json, psr
          pecl: true
      - name: Install package
        run: pecl install my-package.tgz
```
I get the following error:
```
pecl : The term 'pecl' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\a\_temp\d5e656a9-0ff2-4855-94ac-b48d41494579.ps1:2 char:1
+ pecl install my-package.tgz
+ ~~~~
+ CategoryInfo          : ObjectNotFound: (pecl:String) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : CommandNotFoundException
```
