### ISSUE TITLE
several extensions enabled by default on php7.2, but non 7.0

### ISSUE THREAD

**Issue by clxmstaab** [shivammathur/setup-php#143]
**Describe the bug**
using a action which installs via composer sabre/xml I am gettin an error when using php7.0 because of a missing ext-dom extension but on php 7.2 build it works fine

![image](https://user-images.githubusercontent.com/47448731/71990490-c222c180-3233-11ea-9f63-4350d1aafa57.png)

in the php 7.0 build the ext-dom extension needs to be explicitly activated via github-action workflow config, but on php 7.2 it works out of the box.

is this difference intentional?

**Comment by clxmstaab** [comment]
my github action worfklow is:

```yml
name: PHP Checks

on: [push]

jobs:

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: 7.2
        coverage: none
    - run: |
        composer install --prefer-dist --no-progress # install the apps dependencies
        composer bin phpstan install --no-progress
    - run: composer phpstan -- --no-progress

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: 7.0
        coverage: none
    - run: |
        composer install --prefer-dist --no-progress # install the apps dependencies
        composer bin php-cs-fixer install --no-progress
    - run: composer csfix -- --dry-run --diff --verbose
```
