### ISSUE TITLE
Never ending setup Setup PHP action

### ISSUE THREAD

**Issue by sergeyklay** [shivammathur/setup-php#148]
It seems for the following configuration I get infinity loop or something like that :)

```yaml
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.1'
          extensions: psr zip
          tools: pecl
```

![image](https://user-images.githubusercontent.com/1256298/72396733-51edd180-3746-11ea-9336-8770dc2fde23.png)
