### ISSUE TITLE
Missed pdo_sqlite and gmp

### ISSUE THREAD

**Issue by sergeyklay** [shivammathur/setup-php#149]
For the following configuration:
```yaml
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.0'
          extensions: pdo_sqlite gmp
```

I get this:

![image](https://user-images.githubusercontent.com/1256298/72396383-2c13fd00-3745-11ea-9f77-c2bebd869645.png)

Both extensions are standard. And as you can see Action does not trigger error and does not stop CI.
