### ISSUE TITLE
Add Phive to the available tools

### ISSUE THREAD

**Issue by Aerendir** [shivammathur/setup-php#151]
**Is your feature request related to a problem? Please describe.**
Often it happens that dev tools cause conflicts in the tree of dependencies.

To solve this problem it is possible to download some tools as a PHAR package.

To make easier the use of the PHAR packages, a tool exists: Phive.

Phive is like Composer, but for PHAR packages.

It permits to create a list of packages to download as PHAR and makes their management easier.

You can read more about Phive here: https://phar.io/

**Describe the solution you'd like**
Make possible to use a configuration like this to make Phive available:

```yaml
            - name: Setup PHP
              uses: shivammathur/setup-php@v1
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none # disable xdebug, pcov
                  tools: phive
                  extensions: intl
```

**Describe alternatives you've considered**

Obviously it is possible to install Phive manually, but having the action do it makes thing a lot easier.
