### ISSUE TITLE
Unable to install PSR extension using PHP 7.4

### ISSUE THREAD

**Issue by sergeyklay** [shivammathur/setup-php#154]
```yaml
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: gmp, pdo_sqlite, psr, zip
          tools: phpize, php-config
          coverage: xdebug
          ini-values: variables_order=EGPCS, enable_dl=On, allow_url_fopen=On, error_reporting=-1, memory_limit=1G, date.timezone=UTC, xdebug.max_nesting_level=256

      - name: Minimal Load Test for Required Extensions
        run: |
          for e in gmp pdo_sqlite psr zip; do
            php --ri $e 1>/dev/null || (echo "Extension $e was not found")
          done
```

The output for PHP 7.4 is:
```
Extension psr was not found
```

PHP 7.0, 7.1, 7.2, 7.3 works as expected. A day ago ([before 1.7.3 release](https://github.com/shivammathur/setup-php/releases/tag/1.7.3)) all was ok.
