### ISSUE TITLE
After latest tools: update, job always cancels itself

### ISSUE THREAD

**Issue by kwhat** [shivammathur/setup-php#160]
**Describe the bug**
After what ever happened with the latest updates, the install php job always fails with "##[error]The operation was canceled."  I didn't cancel the job so I am not sure why it is canceling itself.  This is kind of important as all of my CI is down right now...

**To Reproduce**
```
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 1
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ast, mbstring, pdo
          ini-values: "date.timezone=UTC"
          coverage: PCOV
          tools: pecl
      - name: Check PHP Version
        run: php -v
      - name: Check PHP Extensions
        run: php -m
      - name: Check Composer Version
        run: composer -V
      - name: Install Project Dependencies
        run: composer install --dev --prefer-dist --optimize-autoloader --no-progress
      - name: Lint Source
        run: composer lint
```

**Expected behavior**
I would expect things to complete as they use to.

**Screenshots**
max-parallel: 15
![image](https://user-images.githubusercontent.com/676164/73035136-fd102200-3dfb-11ea-94c1-f39d0514496d.png)

max-parallel: 1
![image](https://user-images.githubusercontent.com/676164/73035632-b91e1c80-3dfd-11ea-9ed6-d12593ca2cd0.png)

**Additional context**
This was working until very recently.
