### ISSUE TITLE
Fail when extension cannot be installed

### ISSUE THREAD

**Issue by ruudk** [shivammathur/setup-php#171]
**Describe the bug**
I specify an extension that cannot be installed

**To Reproduce**
```
            -   name: Setup PHP
                uses: shivammathur/setup-php@master
                with:
                    php-version: '7.4'
                    extensions: mbstring,bcmath,intl,gd,zip,rdkafka
```

**Expected behavior**
It fails that it cannot be installed. 

**Actual behavior**
It succeeds and continues ✅ .

**Screenshots**
<img width="1244" alt="Screenshot 2020-01-30 at 17 13 14" src="https://user-images.githubusercontent.com/104180/73467595-d2861200-4383-11ea-99cd-33b3cbd3f663.png">

**Comment by shivammathur** [comment]
There is no package `php-rdkafka` so to install it you will need pecl. So add `tools: pecl` to the inputs.
```yml
-   name: Setup PHP
    uses: shivammathur/setup-php@master
    with:
      php-version: '7.4'
      tools: pecl
      extensions: mbstring, bcmath, intl, gd, zip, rdkafka
```
