### ISSUE TITLE
Could not setup cs2pr

### ISSUE THREAD

**Issue by Kocal** [shivammathur/setup-php#178]
**Describe the bug**
It seems that since the [last version of cs2pr](https://github.com/staabm/annotate-pull-request-from-checkstyle/releases/tag/1.0.5), cs2pr is not setupable anymore.
I don't know if it's coming from this action or from cs2pr, I will open an issue in their repo too.

**To Reproduce**

Here is our whole step to setup PHP:

```yaml
- name: Setup PHP
  uses: shivammathur/setup-php@v1
  with:
      php-version: ${{ env.PHP_VERSION }}
      extensions: mbstring, intl, xsl # optional, setup extensions
      ini-values: date.timezone=${{ env.TZ }}, memory_limit=-1, session.gc_probability=0, opcache.enable=1, opcache.enable_cli=1, opcache.memory_consumption=256, opcache.max_accelerated_files=20000, opcache.validate_timestamps=0, realpath_cache_size=4096K, realpath_cache_ttl=600 # optional, setup php.ini configuration
      coverage: none
      tools: cs2pr # <--
```

**Expected behavior**
It should be able to setup cs2pr.

**Screenshots**
![Sélection_999(674)](https://user-images.githubusercontent.com/2103975/74635717-e2189f80-5166-11ea-937b-b0f0fb5083db.png)

**Additional context**

.

Thanks!
