### ISSUE TITLE
sudo error on php 7.4.2 with setup-php v2

### ISSUE THREAD

**Issue by prisis** [shivammathur/setup-php#180]
**Describe the bug**
sudo error on php 7.4.2
```
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"

sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0

sudo: fatal error, unable to load plugins

sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"

sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0

sudo: fatal error, unable to load plugins
```

**To Reproduce**
```yml
# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Continuous Integration on Linux"

on:
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  LinuxIntegration:
    name: "PHP ${{ matrix.php-versions }} Test on ubuntu-latest OS with ${{ matrix.dependencies }} dependencies"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ["7.3", "7.4.2"]
        dependencies: ["highest", "lowest"]

    env:
      key: "continuous-integration-linux-v1" # change key (version) to clear cache
      extensions: "mbstring"
      ini-values: "date.timezone=Europe/Berlin, opcache.enable_cli=1, serialize_precision=14"
      tools: "composer, composer-prefetcher"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: "Setup cache environment"
        id: cache-env
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: "Cache extensions"
        uses: actions/cache@v1
        with:
          path: ${{ steps.cache-env.outputs.dir }}
          key: ${{ steps.cache-env.outputs.key }}
          restore-keys: ${{ steps.cache-env.outputs.key }}

      - name: "Setup PHP"
        uses: shivammathur/setup-php@2.0.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          ini-values: ${{ env.ini-values }}
          tools: ${{ env.tools }}
          coverage: none

      - name: "Configure Container"
        env:
          NARROWSPARK_EMAIL: ${{ secrets.NARROWSPARK_EMAIL }}
          NARROWSPARK_USERNAME: ${{ secrets.NARROWSPARK_USERNAME }}
        run: |
          echo "::set-env name=PHPUNIT::./vendor/bin/phpunit --verbose"
          echo "::set-env name=COMPOSER_UP::composer update --no-progress --no-suggest --no-interaction --prefer-source --ansi"
          echo "::set-env name=SOURCE_NAME::${GITHUB_REF#refs/*/}"
          echo "::set-env name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}"
          echo "::set-env name=SOURCE_TAG::${GITHUB_REF#refs/tags/}"

          EMAIL=${NARROWSPARK_EMAIL:-"d.bannert@anolilab.de"}
          NAME=${NARROWSPARK_USERNAME:-"prisis"}

          git config --global user.email "${EMAIL}"
          git config --global user.name "${NAME}"

      - name: "Setup Problem Matchers for PHP"
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: "Check PHP Version"
        run: php -v

      - name: "List all php extensions with versions"
        run: php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'

      - name: "Setup Problem Matchers for PHPUnit"
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: "Check Composer Version"
        run: composer -V

      - name: "Validate composer.json and composer.lock"
        run: composer validate --strict

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache dependencies"
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: "Install highest dependencies"
        if: matrix.dependencies == 'highest'
        run: $COMPOSER_UP

      - name: "Install lowest dependencies"
        if: matrix.dependencies == 'lowest'
        run: $COMPOSER_UP --prefer-lowest --prefer-stable

      - name: "Run Test's"
        run: $PHPUNIT

```

**Expected behavior**
no sudo error

**Screenshots**

nope

**Additional context**
https://github.com/PrisisForks/php-cs-fixer-config/runs/450549204?check_suite_focus=true
