### ISSUE TITLE
PHP Startup: Unable to load dynamic library 'intl.so'

### ISSUE THREAD

**Issue by mfn** [shivammathur/setup-php#194]
**Describe the bug**
Approximately one or two hours ago our jobs starting to fail with this error:
> `PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

<details>
<summary>Here's the  output of the `Run shivammathur/setup-php@v2` step</summary>
I couldn't easily copy all lines, some issue with Firefox and copypasta from their interface; but the gist is there.

```
Run shivammathur/setup-php@v2
  with:
    php-version: 7.3
    extensions: bcmath, curl, fpm, gd, intl, mbstring, pgsql, xml, zip
    ini-values: memory_limit=-1
    coverage: none
  env:
    cache-key: cache-v2
    extensions: bcmath, curl, fpm, gd, intl, mbstring, pgsql, xml, zip
    ini-values: memory_limit=-1
/bin/bash /opt/hostedtoolcache/linux.sh 7.3 /home/runner/work/_actions/shivammathur/setup-php/v2/dist

==> Setup PHP
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
✓ PHP Switched to PHP 7.3.15

==> Setup Tools
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
✓ composer Added

==> Setup Extensions
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
✓ bcmath Enabled
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
✓ curl Enabled
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
✓ fpm Installed and enabled
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'intl.so' (tried: /usr/lib/php/20180731/intl.so (libicuio.so.64: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/intl.so.so (/usr/lib/php/20180731/intl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
…
✓ zip Enabled

==> Add php.ini values
✓ memory_limit=-1 Added to php.ini

==> Setup Coverage
✓ none Disabled Xdebug and PCOV
```
</details>

**To Reproduce**
Please provide the GitHub Action `.yml` file.
```yaml
name: PHPUnit tests
on: push

jobs:
  phpunit:
    strategy:
      matrix:
        phpunit-slices: ['1/8', '2/8', '3/8', '4/8', '5/8', '6/8', '7/8', '8/8']
        os: [ubuntu-latest]
        php-versions: ['7.3']
        pgsql-versions: ['12.2']
        elasticsearch-versions: ['5.3.0']
    name: Testsuite ${{ matrix.phpunit-slices }} with PHP ${{ matrix.php-versions }} / PostgreSQL ${{ matrix.pgsql-versions }} / ElasticSearch ${{ matrix.elasticsearch-versions}} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      cache-key: cache-v2 # can be any string, change to clear the extension cache
      extensions: bcmath, curl, fpm, gd, intl, mbstring, pgsql, xml, zip
      ini-values: memory_limit=-1

    services:

      postgres-main:
        image: postgres:${{ matrix.pgsql-versions }}
        env:
          POSTGRES_USER: …
          POSTGRES_PASSWORD: …
          POSTGRES_DB: …
        ports:
          # will assign a random free host port
          - 5432/tcp
        # needed because the container does not provide a healthcheck
        # also dedicate name so we can refer to it via `docker exec` in the steps
        options: --name postgres-main --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      postgres-logs:
        image: postgres:${{ matrix.pgsql-versions }}
        env:
          POSTGRES_USER: …
          POSTGRES_PASSWORD: …
          POSTGRES_DB: …
        ports:
          # will assign a random free host port
          - 5432/tcp
        # needed because the container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      elasticsearch:
        image: elasticsearch:${{ matrix.elasticsearch-versions }}
        ports:
          # will assign a random free host port
          - 9200/tcp
        # needed because the container does not provide a healthcheck
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - name: Enable postgres-main btree_gin extension
        run: docker exec postgres-main psql --dbname=… --username=… -c 'CREATE EXTENSION IF NOT EXISTS btree_gin;'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: cache-env
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.cache-key }}

      - name: Cache extensions
        uses: actions/cache@v1
        with:
          path: ${{ steps.cache-env.outputs.dir }}
          key: ${{ steps.cache-env.outputs.key }}
          restore-keys: ${{ steps.cache-env.outputs.key }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          ini-values: ${{ env.ini-values }}
          coverage: none

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - run: vendor/bin/phpunit-slicer --slice ${{ matrix.phpunit-slices }} --printer="\Mfn\PHPUnitImmediateExceptionPrinter\ImmediateExceptionPrinter"
        env:
          DB_PGSQL_LOGS_PORT: ${{ job.services.postgres-logs.ports['5432'] }}
          DB_PGSQL_PORT: ${{ job.services.postgres-main.ports['5432'] }}
          DB_PGSQL_READ_ONLY_PORT: ${{ job.services.postgres-main.ports['5432'] }}
          ELASTICSEARCH_SERVERS: localhost:${{ job.services.elasticsearch.ports['9200'] }}
          TESTS_ON_CI: yes
```
(obfuscated some things, this is from a private repo; I also didn't really shorten it, just so the full scope is available)

**Comment by mfn** [comment]
While preparing everything I already "found" the fix: I had to bust the cache.

I.e. from above workflow I changed `cache-key: cache-v2` to `cache-key: cache-v3`, problem solved.

I'll leave this issue open, maybe someone has more insights (maybe some underlying ubuntu changes?)

Thanks

**Comment by shivammathur** [comment]
Yes, recently `icu` was updated to from `64.2` to `65.1` in [Ondrej's PHP PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php), so if you have old `intl` extension cached, resetting the extension cache by changing the key would install and cache the new version.

**Comment by mfn** [comment]
Makes sense, thanks for the details 👍 

Do you think this is possible to "detect" when broken extensions are restored from the cache … 🤔

**Comment by shivammathur** [comment]
After Setup PHP step, you can add this step to check for `intl` extension and fail the  workflow if it is not found.
```yml
- name: Check extension 
  run: php -r "if(! extension_loaded('intl')) {throw new Exception('intl not found');}"
```

**Comment by mfn** [comment]
Clever ❤️

**Comment by mfn** [comment]
I expanded your suggestion to this in the end:
```yaml
      # See https://github.com/shivammathur/setup-php/issues/194
      - name: Check all PHP extensions are properly loaded
        run: php -r 'foreach ( explode(",", "${{ env.extensions }}") as $extension) { $extension = trim($extension); if (!extension_loaded($extension)) { throw new RuntimeException("Expected extension $extension to be loaded but is not, maybe you need to bust the cache-key ?"); } }'
```
