### ISSUE TITLE
Unable to install the AST extension

### ISSUE THREAD

**Issue by mridang** [shivammathur/setup-php#206]
**Describe the bug**
Unable to install the `ast` extension

**To Reproduce**

```
name: PHP CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.1'
        tools: composer, pecl, ast
```

**Expected behavior**
The expected behavior is that AST should be installed. 

**Screenshots**
<img width="1103" alt="Screenshot 2020-03-28 at 17 37 40" src="https://user-images.githubusercontent.com/327432/77822696-1a72ac80-711b-11ea-827c-525e431ef458.png">

**Additional context**

**Comment by shivammathur** [comment]
`ast` is not a tool, but an extension.

This will work
```yml
- name: Set up PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7.1'
    tools: pecl
    extensions: ast
```
