### ISSUE TITLE
Intermittant "imagick Could not install imagick on PHP 7.4.4"

### ISSUE THREAD

**Issue by bendavies** [shivammathur/setup-php#208]
**Describe the bug**
imagick fails to install on PHP 7.4.4 intermittently. Most of the time works, sometimes fails.

**To Reproduce**
Private, but the step is:
```
      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: imagick
          php-version: 7.4
```

**Expected behavior**
imagick installs

**Screenshots**
![image](https://user-images.githubusercontent.com/625392/78242260-95e8ab00-74d9-11ea-9197-3cac0e7ef66c.png)

**Additional context**
Why does the step continue here despite failing? Can we force a failure instead of continuing?

**Comment by shivammathur** [comment]
I'm unable to reproduce this. In my testing `imagick` installs correctly. Here is a [test workflow](https://github.com/shivammathur/test-setup-php/actions/runs/69127460/workflow).

If you can reproduce this in a public repo using the `verbose` tag, then please reopen the issue.
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@verbose
  with:
    php-version: '7.4'
    extensions: imagick
    coverage: none
```

The workflow does not fail if an extension fails to install. This behaviour has been documented [here](https://github.com/shivammathur/setup-php#heavy_plus_sign-php-extension-support) in second last point. If you want the workflow to fail, you can add a step after the `setup-php` step in your workflow to check for the extension.

```yml
- name: Check imagick
  run: php -r "if(! extension_loaded('imagick')) {throw new Exception('imagick not found');}"
```
