### ISSUE TITLE
Weird errors in /opt/hostedtoolcache/linux.sh

### ISSUE THREAD

**Issue by enumag** [shivammathur/setup-php#210]
**Describe the bug**

I'm trying to install PHP with the ds extension according to your [documentation](https://github.com/marketplace/actions/setup-php-action#heavy_plus_sign-php-extension-support) but it's not working. I don't think it's my fault in this case.

**To Reproduce**

```yml
name: "Build"

on:
    pull_request:
    push:
        branches:
            - "master"

env:
    PHP_VERSION: 7.4

jobs:
    composer:
        name: "Composer"
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2.0.0"

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  coverage: "none"
                  php-version: "${PHP_VERSION}"
                  tools: pecl
                  extensions: ds
```

**Expected behavior**

Installed PHP 7.4 with [ext-ds](https://pecl.php.net/package/ds).

**Screenshots**

![Screenshot from 2020-04-08 12-02-18](https://user-images.githubusercontent.com/539462/78771673-db512080-7990-11ea-9bd1-d8a753ce562f.png)
