### ISSUE TITLE
Unable to install ImageMagick

### ISSUE THREAD

**Issue by MrNicodemuz** [shivammathur/setup-php#213]
**Describe the bug**
Unable to install ImageMagick using the following steps:
```yaml
      - name: Install Image Magick
        run: sudo apt-get install imagemagick

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: mbstring, xml, ctype, iconv, mysql, imagick
```

**To Reproduce**
https://github.com/MrNicodemuz/setup-php-test/runs/581961204
https://github.com/MrNicodemuz/setup-php-test/blob/ffe18752e97a5b5b680bca28566df1c278e79477/.github/workflows/main.yml

**Expected behavior**
Expecting following statements to return true:
```php
extension_loaded('imagick')
class_exists('Imagick')
```

**Comment by YaFou** [comment]
Your workflow configuration file is wrong: `extension-csv` was removed in version 2. The following configuration works:
```yml
name: CI

on: [push]

jobs:

  imagicktest:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php-versions: ['7.3']

    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, mysql, imagick

      - name: Check PHP Version
        run: php -v

      - name: Check PHP Extensions
        run: php -m

      - name: Check Composer Version
        run: composer -V

      - name: Verify Image Magick installation
        run: php -r "if (extension_loaded('imagick') && class_exists('Imagick')) { echo 'OK'; exit(0); } else { exit(1); }"
```
You have to edit the version for `Setup PHP` and the keys to set extensions. Also, you don't need to install `imagemagick` because `Setup PHP` does it.
