### ISSUE TITLE
Extensions enabled by default?

### ISSUE THREAD

**Issue by ondrejmirtes** [shivammathur/setup-php#214]
**Is your feature request related to a problem? Please describe.**

Hi, I'd like to test [PHPStan](https://phpstan.org/) with various PHP extensions enabled or disabled. So I'd like to know, are there some PHP extensions that are enabled by default? I suspect it might be the case for the `SOAP` extensions, which can be enabled during PHP compilation with `--enable-soap`.

I'd like to test PHPStan behaviour with SOAP extension disabled.

**Describe the solution you'd like**

Ship PHP without any extensions enabled by default.

**Describe alternatives you've considered**

Include `extensions_disable` argument to be able to disable some built-in extensions like SOAP.

**Additional context**

This is my favourite GitHub action! Really well thought-out, a great piece of engineering. Thank you.

**Comment by shivammathur** [comment]
Thanks!

`php-soap` is pre-installed on the GitHub actions runner.

Disabling extensions is not supported currently.
You can disable soap for example by adding these steps after the setup-php step
```yaml
name: Disable soap on ubuntu
if: matrix.operating-system == 'ubuntu-latest'
run: sudo phpdismod -v ${{ matrix.php-versions }} soap

name: Disable soap on windows
if: matrix.operating-system == 'windows-latest'
run: Disable-PhpExtension soap C:\tools\php

name: Disable soap on macos
if: matrix.operating-system == 'macos-latest'
run: sudo sed -i '' "/soap/d" $(php --ini | grep "Loaded Configuration" | sed -e "s|.*:s*||" | sed "s/ //g")
```

**Comment by shivammathur** [comment]
@ondrejmirtes
Thanks!

`php-soap` is pre-installed on the GitHub actions runner.

Disabling extensions using the action is not supported currently.
You can disable soap for example by adding these steps as per the OS after the setup-php step
```yaml
name: Disable soap on ubuntu
if: matrix.operating-system == 'ubuntu-latest'
run: sudo phpdismod -v ${{ matrix.php-versions }} soap

name: Disable soap on windows
if: matrix.operating-system == 'windows-latest'
run: Disable-PhpExtension soap C:\tools\php

name: Disable soap on macos
if: matrix.operating-system == 'macos-latest'
run: sudo sed -i '' "/soap/d" $(php --ini | grep "Loaded Configuration" | sed -e "s|.*:s*||" | sed "s/ //g")
```
