### ISSUE TITLE
Unable to load dynamic library 'couchbase.so' - undefined symbol: json_globals 

### ISSUE THREAD

**Issue by jakzal** [shivammathur/setup-php#217]
**Describe the bug**

Enabling the couchbase extension fails with an error:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'couchbase.so' 
(tried: 
  /usr/lib/php/20190902/couchbase.so 
    (/usr/lib/php/20190902/couchbase.so: undefined symbol: json_globals),
  /usr/lib/php/20190902/couchbase.so.so 
    (/usr/lib/php/20190902/couchbase.so.so: cannot open shared object file: No such file or directory)
) in Unknown on line 0
```

**To Reproduce**

```yaml
name: Tests

on:
    push:
    pull_request:

jobs:

    integration:
        name: Integration
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: ['7.2', '7.4']

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Install system dependencies
                run: |
                    sudo wget -O - http://packages.couchbase.com/ubuntu/couchbase.key | sudo apt-key add -
                    echo "deb http://packages.couchbase.com/ubuntu bionic bionic/main" | sudo tee /etc/apt/sources.list.d/couchbase.list
                    sudo apt-get update
                    sudo apt-get install libcouchbase-dev

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    extensions: "json,couchbase,xsl"
                    ini-values: "memory_limit=-1"
                    php-version: "${{ matrix.php }}"
                    tools: flex,pecl

            -   name: PHP info
                run: php -i

```

**Expected behavior**

The extension is installed and enabled.

**Screenshots**

<img width="858" alt="image" src="https://user-images.githubusercontent.com/190447/81043428-25eb8d00-8eaa-11ea-9ab7-7c5e11e6dd14.png">

**Additional context**

One of my test builds can be found here: https://github.com/jakzal/symfony/runs/645215707?check_suite_focus=true

Stackoverflow says the json extension should be loaded before couchbase, but setup-php  seem to already load extensions in the order they're defined in the configuration.
