### ISSUE TITLE
Specify patch version

### ISSUE THREAD

**Issue by Nyholm** [shivammathur/setup-php#224]
Our project noticed a bug in PHP 7.4.6. It is reported (https://bugs.php.net/bug.php?id=79616) but it still means that the CI will fail (at best) until PHP 7.4.7 release becomes available. 

Would it be possible to specify a patch version?

**Comment by shivammathur** [comment]
It is not possible to specify the patch in the `php-version` input as it truncates it. But if a patch of PHP is already installed, the action uses it unless update is set to true.

So here is a trick you can use till the next PHP release, provide your workflow with it a ubuntu container having PHP 7.4.5 installed with the runner environment variable set to `self-hosted` and the action will use the patch release in the container. 

I had update `shivammathur/node` images to `7.4.6` but the container digest in the `yml` below is of image having PHP `7.4.5`, `7.3.17` and `7.2.30`.

Test workflow - https://github.com/shivammathur/test-setup-php/actions/runs/111475914/workflow

```yaml
jobs:
  testrun:
    runs-on: ubuntu-18.04
    name: testrun
    strategy:
      matrix:
        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    container: shivammathur/node@sha256:11a4e6282885a7de5e84599294dc8a4b28b598241245f3bc629da6cf0482da62
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, mysql
          coverage: none
          tools: phpstan
        env:
          runner: self-hosted
     ...
     ...
```
