### ISSUE TITLE
Caching doesn't have much impact

### ISSUE THREAD

**Issue by olivernybroe** [shivammathur/setup-php#226]
**Describe the bug**
Without cache it took 1m 18s and with cache it took 57s for it to run for us.

![image](https://user-images.githubusercontent.com/5870441/82815383-587d1a00-9e99-11ea-8cbc-ea474bc4a6ea.png)
![image](https://user-images.githubusercontent.com/5870441/82815325-3c797880-9e99-11ea-8c8f-101a5ebd5292.png)

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
7.2

**To Reproduce**
```yaml
      - name: Setup cache environment
        id: cache-env
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v1
        with:
          path: ${{ steps.cache-env.outputs.dir }}
          key: ${{ steps.cache-env.outputs.key }}
          restore-keys: ${{ steps.cache-env.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}
          tools: pecl, prestissimo
          extensions: ${{ env.extensions }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

With the following extensions
```
extensions: pdo, bcmath, ctype, json, mbstring, openssl, tokenizer, xml, dom, mysql, curl
strategy:
  matrix:
    php: ['7.2']
```

**Expected behavior**
The time should be much faster with cache.
