### ISSUE TITLE
Flaky tests because of sometimes missing extension

### ISSUE THREAD

**Issue by greg0ire** [shivammathur/setup-php#228]
**Describe the bug**
ext-dom seems to be installed sometimes, sometimes not

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
7.4

**To Reproduce**
```
  static-analysis-phpstan:
    name: "Static Analysis with PHPStan"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: cs2pr

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v1"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

      - name: "Install dependencies with composer"
        run: "composer install --no-progress --no-suggest --no-interaction --prefer-dist"

      - name: "Run a static analysis with phpstan/phpstan"
        run: "php vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr"
```

**Expected behavior**
Works every time.

**Screenshots/Logs**
`- phar-io/manifest 1.0.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.`

https://github.com/doctrine/orm/pull/8165/checks?check_run_id=731742249

**Additional context**
Can't think of anything right now

**Are you willing to submit a PR?**
With some guidance, why not

**Comment by shivammathur** [comment]
@greg0ire It should be installed on the runner. Please specify `extensions: dom` in the inputs, that should fix it.
```yaml
...
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          extensions: dom
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: cs2pr
...
```
