### ISSUE TITLE
Seeking help with a possible PATH issue

### ISSUE THREAD

**Issue by kethinov** [shivammathur/setup-php#231]
I've set this up in my CI but it isn't working correctly. I think it might be a PATH issue with an easy fix, but I've been perusing the docs and I can't figure it out.

- [Failing build](https://github.com/rooseveltframework/express-php-view-engine/runs/739779989) - the tests pass on my local machine, just not on the CI.
- [How the project calls PHP](https://github.com/rooseveltframework/express-php-view-engine/blob/61f404815f2d13246032fa7a7900285d52068ed2/index.js#L20) - basically PHP is being called from a Node.js script.
- [My CI config](https://github.com/rooseveltframework/express-php-view-engine/blob/master/.github/workflows/.ci.yml) - do I need to alter my config to put PHP in my PATH correctly or something?

**Comment by shivammathur** [comment]
PHP is in path, so that should not be an issue. 
Without PHP you will get this error "Timed out while running tests".

**Comment by shivammathur** [comment]
- You are using short php tags `<? ... ?>`. which require adding `short_open_tag=On` to `php.ini`
- You are testing when variables are not defined in 2 and 3rd test case, so turn off `E_NOTICES` in error reporting by adding `error_reporting=E_ALL & ~E_NOTICE` to your `php.ini`
- Also specify `php-version` input while calling the action.

Change your setup-php step as below and it should work. Here is a [test workflow](https://github.com/shivammathur/test-setup-php/actions/runs/127053932/workflow).
```yml
- name: Setup PHP Action
  uses: shivammathur/setup-php@v2
  with:
    php-version: ${{ matrix.php-versions }}
    ini-values: short_open_tag=On, error_reporting=E_ALL & ~E_NOTICE
```
