### ISSUE TITLE
Example code showed to Cache Composer Dependencies doesn't work with https://github.com/nektos/act because of the hyphen in step id

### ISSUE THREAD

**Issue by fpalamour** [shivammathur/setup-php#233]
**Describe the bug**
Using the id `composer-cache` for the step _Get composer cache directory_ creates the following error on the following step :
`ERRO[0047] Unable to interpolate string '${{ steps.composer-cache.outputs.dir }}' - [ReferenceError: 'cache' is not defined]
`

see https://github.com/nektos/act/issues/104

**Version**
- [ ] I have checked releases and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 16.04

**PHP versions**
7.2

**To Reproduce**

```yml
- name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
```
Then launch  `act -P ubuntu-16.04=shivammathur/node:xenial`

**Expected behavior**
The expression `${{ steps.composer-cache.outputs.dir }}` the be correctly resolved

**Additional context**
I believe it has something to do with this : https://github.com/nektos/act/issues/104
