### ISSUE TITLE
Corrupted composer is installed using v1

### ISSUE THREAD

**Issue by stof** [shivammathur/setup-php#239]
**Describe the bug**
Things where working fine yesterday in the afternoon. But workflows running yesterday evening (19:35 UTC+2) installed a corrupted version of composer (without the setup-php step reporting a failure, so the failure was only reported by a later step using composer)

**Version**
- [ ] I have checked releases and the bug exists in the latest patch version of `v1` or `v2`.
- [ ] `v2`
- [x] `v1`

I haven't checked v2

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
linux

**PHP versions**
7.3

**To Reproduce**
```yaml
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.3
          extensions: intl
          coverage: none
      # more steps following, where using composer would throw the same fatal error and break the build

**Expected behavior**
A usable version of composer is installed.
And another expectation would be that such fatal error actually makes the setup report a failure rather than failing silently.

**Screenshots/Logs**
Here is the output of the setup-php step:

```
 Setup PHP
24s
    coverage: none
Run shivammathur/setup-php@v1
  with:
    php-version: 7.3
    extensions: intl
    coverage: none
/bin/bash /opt/hostedtoolcache/linux.sh 7.3 /home/runner/work/_actions/shivammathur/setup-php/v1/dist

==> Setup PHP
✓ PHP Switched to PHP 7.3.19

==> Setup Tools
PHP Fatal error:  Uncaught PharException: internal corruption of phar "/usr/local/bin/composer" (truncated manifest header) in /usr/local/bin/composer:23
Stack trace:
#0 /usr/local/bin/composer(23): Phar::mapPhar('composer.phar')
#1 {main}
  thrown in /usr/local/bin/composer on line 23
✓ composer Added

==> Setup Extensions
✓ intl Enabled

==> Setup Coverage
✓ none Disabled Xdebug and PCOV
```

**Additional context**
<!-- Add any other context about the problem here. -->

**Are you willing to submit a PR?**
<!-- We accept pull requests targeting the develop branch. -->
