### ISSUE TITLE
Support PDO_OCI

### ISSUE THREAD

**Issue by samdark** [shivammathur/setup-php#241]
https://www.php.net/manual/en/ref.pdo-oci.php is useful in actions if you need to test against Oracle database. We have such need in Yii 2: https://github.com/yiisoft/yii2/tree/master/tests/framework/db/oci

It could be achieved by adding `--with-pdo-oci` during PHP build time.

**Version**
- [x] I have checked releases and the feature is missing in the latest patch version of `v2`.

**Are you willing to submit a PR?**

Not sure how to do it yet but may try it.

**Comment by shivammathur** [comment]
@samdark I added support for both `pdo_oci` and `oci8`. Can you test this with `Yii` using the develop branch of `setup-php`

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@develop
  extensions: pdo_oci, oci8
```

**Comment by shivammathur** [comment]
@samdark I added support for both `pdo_oci` and `oci8`. Can you please test this with `Yii Framework` using the develop branch of `setup-php`.

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@develop
  extensions: pdo_oci, oci8
```
