### ISSUE TITLE
Disable coverage when nothing is specified

### ISSUE THREAD

**Issue by Baptouuuu** [shivammathur/setup-php#254]
**Describe the bug**
I run my tests against linux and macOS. I didn't specified the `coverage` key and my tests run in about 5 minutes on macOS and about 3 hours on linux. The reason is that by default the linux runner comes with xdebug pre-installed. When I specify `coverage: none` both runners execution time are similar.

When nothing is specified it should remove xdebug by default as there are different behaviours between runners. This is an implicit behaviour.

**Version**
- [ ] I have checked releases and the bug exists in the latest patch version of `v1` or `v2`.
- [ ] `v2`
- [x] `v1`

I didn't actually test for `v2` but for what I understood from the code the problem is still present.

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`ubuntu-latest` and `macOS-latest`

**PHP versions**
`7.4`

**To Reproduce**
```yml
phpunit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        php-version: ['7.4']
    name: 'PHPUnit - PHP/${{ matrix.php-version }} - OS/${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
         with:
           php-version: ${{ matrix.php-version }}
           extensions: mbstring, intl
      - name: PHPUnit
        run: vendor/bin/phpunit
```

**Expected behavior**
The execution for both operating system should be similar

**Screenshots/Logs**
<img width="1186" alt="Screenshot 2020-07-18 at 18 07 04" src="https://user-images.githubusercontent.com/851425/87856787-bbcb7b80-c921-11ea-8389-d15b6a88d8ac.png">
<img width="1188" alt="Screenshot 2020-07-18 at 18 07 19" src="https://user-images.githubusercontent.com/851425/87856790-bec66c00-c921-11ea-8dfd-64b3e763bd99.png">
<img width="1191" alt="Screenshot 2020-07-18 at 18 08 05" src="https://user-images.githubusercontent.com/851425/87856792-bf5f0280-c921-11ea-9be6-9d0130aa0f7e.png">
<img width="1187" alt="Screenshot 2020-07-18 at 18 08 20" src="https://user-images.githubusercontent.com/851425/87856793-bff79900-c921-11ea-8b4c-7a73ec8e8554.png">

**Additional context**

**Are you willing to submit a PR?**
Yes
