### ISSUE TITLE
build grpc_php_plugin in github actions with setup-php

### ISSUE THREAD

**Issue by zhangchunsheng** [shivammathur/setup-php#262]
I want to build grpc_php_plugin in github actions with setup-php

like below
git clone -b v1.27.0 https://github.com/grpc/grpc
cd grpc && git submodule update --init && make grpc_php_plugin
mv grpc_php_plugin /usr/local/bin

I use v2 version

I think this can add to tools label.

**Comment by shivammathur** [comment]
@zhangchunsheng 
Now you can setup `grpc_php_plugin` and `protoc`.
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  id: php
  with:
    php-version: 7.4
    tools: protoc, grpc_php_plugin
```
`grpc_php_plugin` path is exported as `grpc_php_plugin_path` which can be used in a later step.
For example
```yml
- name: Test grpc_php_plugin and protoc       
  run: |
    git clone https://github.com/grpc/grpc          
    cd grpc/examples/php
    protoc --proto_path=../protos --php_out=. --grpc_out=. --plugin=protoc-gen-grpc=${{ steps.php.outputs.grpc_php_plugin_path }} ../protos/helloworld.proto
```
