### ISSUE TITLE
Build a specific php 8.0. version.

### ISSUE THREAD

**Issue by terabytesoftw** [shivammathur/setup-php#264]
Hi, it is possible to build the latest alpha 3 version of php 8.0, since to test the packages it would be good to test  with lasted alpha versions in linux and windows.

**Comment by shivammathur** [comment]
The nightly `PHP 8` builds are newer than `alpha 3`.
It will be difficult for me to maintain 6 different PHP 8.0 builds, extension builds and support for them in `setup-php`.

I understand that PHP 8 nightly builds might give unexpected errors in tests as something changes daily or is unstable. I suggest adding `continue-on-error: true` to the testing steps when PHP is 8.0. And after each [PHP 8 beta/RC](https://wiki.php.net/todo/php80) release in future you can fix tests in your project.

```yml
- name: Run tests for  PHP < 8.0
  if: matrix.php-version != '8.0'
  run: phpunit ...

- name: Run tests for PHP 8.0
  if: matrix.php-version == '8.0'
  continue-on-error: true
  run: phpunit ...
```
