### ISSUE TITLE
PCOV does not work with a self-hosted runner

### ISSUE THREAD

**Issue by Jamesking56** [shivammathur/setup-php#271]
**Describe the bug**
When using a self-hosted runner and setting up coverage with `pcov`, `phpunit` says:

```
Warning:       No code coverage driver available
```

**Version**
- [x] I have checked releases and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [ ] GitHub Hosted
- [x] Self Hosted

**Operating systems**
Ubuntu 20.04 LTS

**PHP versions**
PHP 7.3

**To Reproduce**
```
laravel-tests:
    runs-on: [self-hosted, ubuntu-latest]
    needs: composer

    services:
      mysql:
        image: mariadb:10.2
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: social-leaderboard
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          coverage: pcov # enable coverage
          tools: cs2pr
        env:
          runner: self-hosted # Specify the runner.
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Get composer cache directory
        id: composer-cache-directory
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        id: composer-cache
        uses: actions/cache@v1
        with:
          path: |
            ${{ steps.composer-cache-directory.outputs.dir }}
            composer.lock
            vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Run migrations
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: php artisan migrate --force -vvv
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
```

**Expected behavior**
Everything passes and Codecov is sent the codecoverage file

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/253237/89872045-482f2e00-dbb0-11ea-9432-785003de3157.png)

![image](https://user-images.githubusercontent.com/253237/89872077-554c1d00-dbb0-11ea-9a8e-be9af9f6a364.png)

**Additional context**
My server has PHP 5.6 -> 7.4 installed with `pcov` already installed.

**Are you willing to submit a PR?**
I'm not sure how this project works
