### ISSUE TITLE
I can't get composer dependencies caching to work

### ISSUE THREAD

**Issue by miloskroulik** [shivammathur/setup-php#272]
**Describe the bug**
I tried to set up composer dependencies caching according to the README, but I wasn't succesful - it seems that `echo "::set-output name=dir::$(composer config cache-files-dir)"` doesn't return the path for some reason, as the output logged is `shell: /bin/bash -e {0}`

**Version**
- [x] I have checked releases and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
* ubuntu-latest

**PHP versions**
* 7.4

**To Reproduce**
I'm trying to use instructions mentioned in the README:
```yml
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl
    - name: Get composer cache directory
      id: composercache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composercache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist
```

**Expected behavior**
I would expect output like `::set-output name=dir::/var/www/.composer/cache/files` (which I get in my local environment)
