### ISSUE TITLE
phpunit doesn't work with PHP 7.2 since PHPUnit 9

### ISSUE THREAD

**Issue by korelstar** [shivammathur/setup-php#276]
**Describe the bug**
phpunit is not compatible to PHP 7.2

**Version**
Affected version is v2.4.3; before that it worked.

**Runners**
GitHub Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
7.2

**To Reproduce**
```
   - name: Set up PHP 7.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.2
        tools: phpunit
```
Then run phpunit.

**Expected behavior**
PHPUnit works.

**Screenshots/Logs**
```
PHPUnit 9.3.7 by Sebastian Bergmann and contributors.

This version of PHPUnit is supported on PHP 7.3 and PHP 7.4.
You are using PHP 7.2.33-1+ubuntu18.04.1+deb.sury.org+1 (/usr/bin/php7.2).
```

**Additional context**
Honestly, before v2.4.3, I did not include the `tools: phpunit` parameter, since this wasn't necessary: phpunit was already installed. However, since v2.4.3, phpunit is not available anymore by default. Then, I added the `tools: phpunit` parameter, but then an incompatible version of phpunit was installed.

I think either the original behavior has to be restored or the phpunit must depend on the used PHP version.
