### ISSUE TITLE
How to enable php-fpm

### ISSUE THREAD

**Issue by heyanlong** [shivammathur/setup-php#280]
**Describe the bug**
How to enable php-fpm

**Version**
- [ ] I have checked releases and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
Only `cli` is supported by the action, may I know your use-case for php-fpm and OS you are using.

On `Ubuntu`, for `PHP 5.6` to `PHP 7.4` you can add this step
```yml
- name: Add php-fpm
  env:
    version: ${{ matrix.php-versions }}
  run: |
    sudo apt-get install -y php$version-fpm
    sudo service php$version-fpm start
```

**Comment by mnapoli** [comment]
Thanks for the workaround! However it doesn't work with PHP 8.

In [Bref](https://github.com/brefphp/bref) we run PHP-FPM in some tests to test the behavior of the FastCGI proxy. Would enabling php-fpm be something that could be considered?

Thanks!

**Comment by shivammathur** [comment]
@mnapoli I will check that and get back to you.

**Comment by shivammathur** [comment]
```
php-fpm -v
PHP 8.0.0-dev (fpm-fcgi) (built: Oct  5 2020 01:06:08)
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0-dev, Copyright (c), by Zend Technologies
```

@mnapoli `php-fpm` with PHP 8.0 for now is installed by default and should be in `PATH`.
When PHP 8.0 is released as stable, the above workaround to install `php-fpm` will work for PHP 8.0 as well.

**Comment by mnapoli** [comment]
Thanks a lot!

Funnily enough, it seems php-fpm is already installed in other PHP versions, for example 7.4:

```
Run if [ "$version" != "8.0" ]; then sudo apt-get install -y php$version-fpm; fi
Reading package lists...
Building dependency tree...
Reading state information...
php7.4-fpm is already the newest version (7.4.10-1+ubuntu18.04.1+deb.sury.org+1).
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
```

But then when PHP tries to run `php-fpm`:

```
exec: php-fpm: not found
```

In case it helps here is the related build: https://github.com/brefphp/bref/pull/767/checks?check_run_id=1210149707

If you have any idea that could help, I'd love it :)

**Comment by shivammathur** [comment]
The apt package puts `php-fpm` binary in `/usr/sbin`.
You can add a line to copy it to `/usr/bin` which will be in `PATH`.

```yml
- name: Setup php-fpm
  if: matrix.php != '8.0'
  env:
    version: ${{ matrix.php }}
  run: |
    sudo apt-get install php$version-fpm
    sudo cp /usr/sbin/php-fpm$version /usr/bin/php-fpm # copy to /usr/bin
    sudo service php$version-fpm start
    sudo service php$version-fpm status
- name: Test php-fpm
  run: php-fpm -v
```

Test workflow - https://github.com/shivammathur/test-setup-php/actions/runs/289826117/workflow
