### ISSUE TITLE
How to enable xsl on php5.5

### ISSUE THREAD

**Issue by yuta-ron** [shivammathur/setup-php#281]
**Describe the bug**
I tried to enable php extention of `xsl` on php 5.5.
But occured following error.

```yml
name: test_and_lint
on:
  push

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: install modules
        run: |
          sudo apt update
          sudo apt install libxml2-dev libxslt-dev php-xml
      - name: Installing php5.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: "5.5"
          extensions: mbstring, soap, xsl
```
[![Image from Gyazo](https://i.gyazo.com/777e953588b9262470a6d3cde8359f06.png)](https://gyazo.com/777e953588b9262470a6d3cde8359f06)

But with php7.3 it succeses.
```yml
name: test_and_lint
on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: install modules
        run: |
          sudo apt update
          sudo apt install libxml2-dev libxslt-dev php-xml
      - name: Installing php7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.3"
          extensions: mbstring, soap, xsl
```
[![Image from Gyazo](https://i.gyazo.com/6ffbc07d212aac5778366d6816c1fd3f.png)](https://gyazo.com/6ffbc07d212aac5778366d6816c1fd3f)

Is this a bug? 
Could you tell me how to resolve it?

Thanks.

**Version**
- [ ] I have checked releases and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**
