### ISSUE TITLE
Support for 32 bit builds of PHP

### ISSUE THREAD

**Issue by danog** [shivammathur/setup-php#302]
**Describe the feature**
Thanks for the awesome project!
It would be great if you could also specify the architecture of binaries about to be installed, I would like to run my tests on 32-bit versions of PHP, too.

**Comment by shivammathur** [comment]
By default 64 bit PHP is installed, except on `Windows` for PHP 5.6 and below which is 32 bit.

I have no plans to adding cross-platform support for specifying the architecture directly as an input unless someone sponsors this work.
But on Ubuntu for PHP 5.6 to 7.4, you can use [`shivammathur/node`](https://github.com/shivammathur/node-docker) docker images as a container and run `setup-php` manually to get both 32 bit and 64 bit PHP.

Here is a [test workflow](https://github.com/shivammathur/test-setup-php/actions/runs/295378658/workflow).

```yml
name: Multiarch workflow
on:
  push:
jobs:
  ubuntu:
    name: multiarch    
    runs-on: ubuntu-latest
    container: shivammathur/node:bionic-${{ matrix.tag }}
    strategy:
      fail-fast: false
      matrix:
        tag: ["amd64", "i386"]
        php: ['7.3', '7.4']
    steps:
      - name: Setup PHP
        # Inputs to manual.sh are in this order - php-versions, extensions, ini-values, coverage, tools
        run: curl -sL https://setup-php.com/manual.sh | bash -s ${{ matrix.php }} "intl" "memory_limit=-1" "pcov" "phpunit"
      - name: check int size
        # PHP_INT_SIZE is 4 for 32 bit and 8 for 64 bit
        run: php -r "echo PHP_INT_SIZE;"
```

**Comment by danog** [comment]
Thanks!

**Comment by Danon** [comment]
> By default 64 bit PHP is installed, except on `Windows` for PHP 5.6 and below which is 32 bit.
> 
> I have no plans to adding cross-platform support for specifying the architecture directly as an input unless someone sponsors this work.
> But on Ubuntu for PHP 5.6 to 7.4, you can use [`shivammathur/node`](https://github.com/shivammathur/node-docker) docker images as a container and run `setup-php` manually to get both 32 bit and 64 bit PHP.
> 
> Here is a [test workflow](https://github.com/shivammathur/test-setup-php/actions/runs/295378658/workflow).
> 
> ```yaml
> name: Multiarch workflow
> on:
>   push:
> jobs:
>   run:
>     runs-on: ubuntu-latest
>     container: shivammathur/node:latest-${{ matrix.arch }}
>     strategy:
>       matrix:
>         arch: ["amd64", "i386"]
>     steps:
>       - name: Install PHP
>         run: |
>           # Update spc (See https://github.com/shivammathur/spc for options)
>           spc -U
> 
>           # Install PHP
>           spc --php-version "7.4" \
>               --extensions "mbstring, intl" \
>               --ini-values "post_max_size=256M, short_open_tag=On" \
>               --coverage "xdebug" \
>               --tools "php-cs-fixer, phpunit"
>       - name: check int size
>         # PHP_INT_SIZE is 4 for 32 bit and 8 for 64 bit
>         run: php -r "echo PHP_INT_SIZE;"
> ```

i can't get it working.

I can't use `actions/checkout` and I can't install git to clone the repo. How to make it work?

**Comment by shivammathur** [comment]
@Danon Please use actions/checkout@v1, that should work. Related issue https://github.com/actions/checkout/issues/334

**Comment by shivammathur** [comment]
@Danon 
I have fixed this in our `shivammathur/node` x86 images (https://github.com/shivammathur/node-docker/commit/ac95d443b1f436126474c1681273715ba2de983c) and now actions should work using the normal syntax on them (`spc` is not required anymore). I will update the documentation about this in the next release.

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1154928977/workflow

```yml
name: Multiarch workflow
on:
  push:
jobs:
  run:
    runs-on: ubuntu-latest
    container: 
      image: shivammathur/node:latest-${{ matrix.arch }}
    strategy:
      matrix:
        arch: ["amd64", "i386"]
    steps:
      - uses: actions/checkout@v2    
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring, intl
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug
          tools: php-cs-fixer, phpunit
      - name: check int size
        # PHP_INT_SIZE is 4 for 32 bit and 8 for 64 bit
        run: php -r "echo PHP_INT_SIZE;"
```
