### ISSUE TITLE
composer:v2 alongside composer-unused installs composer:v1

### ISSUE THREAD

**Issue by Slamdunk** [shivammathur/setup-php#316]
Config:

```yaml
    steps:
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "7.4"
          tools: composer:v2, composer-unused

      - name: "Check composer version"
        run: "composer -V"
```

Result: https://github.com/Slamdunk/composer-folders-plugin/runs/1297453872?check_suite_focus=true

![immagine](https://user-images.githubusercontent.com/152236/96993861-2b0dc880-152c-11eb-9b3d-3c2c7474f612.png)
