### ISSUE TITLE
PHP 8.0 install ext-imagick fail.

### ISSUE THREAD

**Issue by bolechen** [shivammathur/setup-php#320]
the result is

```
✗ imagick Could not install imagick on PHP 8.0.0-dev
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-20.04

**PHP versions**
8.0

**To Reproduce**
```yml
    # https://github.com/shivammathur/setup-php
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: bcmath, gd, intl, mbstring, pdo_sqlite, zip, redis, imagick
        coverage: none
```
