### ISSUE TITLE
"tools": Composer cache not working when using specific Composer version

### ISSUE THREAD

**Issue by tyrann0us** [shivammathur/setup-php#322]
**Describe the bug**
When using the [`tools` input](https://github.com/shivammathur/setup-php#wrench-tools-support) to specify a specific Composer version (e.g. `tools: composer:v1`), Composer won't use cache as described [here](https://github.com/shivammathur/setup-php#cache-composer-dependencies) and [here](https://github.com/actions/cache/blob/main/examples.md#php---composer).

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`ubuntu-latest` (resolves to `ubuntu-18.04`, [still](https://github.com/actions/virtual-environments/issues/1816))

**PHP versions**
7.4

**To Reproduce**
```
name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: shivammathur/setup-php@v2
        with:
          tools: composer:v1
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-
      - run: composer validate --ansi
      - run: composer install -vv --ansi --no-dev --prefer-dist
```
Note that unrelated parts of the workflow files have been removed.

**Expected behavior**
Composer to load packages from cache on subsequent runs.

**Screenshots/Logs**
![screenshot-github com-2020 10 30-15_26_48](https://user-images.githubusercontent.com/8144115/97718858-b0622180-1ac6-11eb-9366-d546d83e5797.jpg)
Note that the screenshot only shows the very first packages, the rest is redacted.

**Additional context**
We need to use the `tools` input to force Composer `v1` because GitHub Actions started to use Composer  `v2` by default, see https://github.com/actions/virtual-environments/issues/1924 and https://github.com/actions/virtual-environments/commit/215647d28a6b1171943ea2c2e6f5a6376a110ea6.

Note that we haven't checked whether this issue also occurs with Composer `v2`.

Cache used to worked before.

What other information do you need from me to investigate?
