### ISSUE TITLE
sqlsrv and PHP 8.0

### ISSUE THREAD

**Issue by hrach** [shivammathur/setup-php#328]
**Describe the feature**

Please, support the sqlsrv installation in PHP 8.0. There is a preview version of the ext: https://pecl.php.net/package/pdo_sqlsrv
(also requested here: https://github.com/shivammathur/setup-php/issues/309)

I know that it is just a preview, but as a library author I'd love to be prepared for upcoming PHP version. Thank you.

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Comment by shivammathur** [comment]
You can use sqlsrv-5.9.0preview1 and pdo_sqlsrv-5.9.0preview1 currently on `Ubuntu` and `macOS` with PHP 8.

Windows DLL for PHP 8.0 is not there on PECL in `5.9.0preview1` releases, so it won't work with windows.

```yml
- name: Install PHP
  uses: shivammathur/setup-php@develop
  with:
    php-version:  8.0
    extensions: pdo_sqlsrv-5.9.0preview1, sqlsrv-5.9.0preview1
```

**Test workflow:** https://github.com/shivammathur/test-setup-php/actions/runs/340631680/workflow
