### ISSUE TITLE
Specific version of Imagick ignored

### ISSUE THREAD

**Issue by MaxGiting** [shivammathur/setup-php#331]
**Describe the bug**
I am trying to install version `7.0.10` of Imagick and the setup seems to ignore this requirement.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted

**Operating systems**

Ubuntu 10.4

**PHP versions**

7.4

**To Reproduce**

Put the below lines in your YML action file
```
    - name: PHP Setup
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer, pecl
        extensions: imagick-7.0.10
        coverage: none
      env:
        fail-fast: true

    - name: Which Imagick Version
      run: php -r 'var_dump(Imagick::getVersion());'
```
**Expected behavior**

I expect it to output that the version of Imagick installed and in use is 7.0.10, but it says 6.8.9
