### ISSUE TITLE
Version of php-config isn't correct in some php version.

### ISSUE THREAD

**Issue by jmjoy** [shivammathur/setup-php#335]
**Describe the bug**
Version of `php-config` isn't correct in some php version.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
- 7.1
- 7.2

**To Reproduce**
```yaml
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        php-version:
          - 7.1
          - 7.2
          - 7.3
          - 7.4

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: PHP Config
        run: php-config --version && php-config --phpapi && php --version

```

**Expected behavior**

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/8677974/99152694-3e045a80-26de-11eb-8eb2-042d096e38a9.png)
![image](https://user-images.githubusercontent.com/8677974/99152705-55434800-26de-11eb-9bfe-2325b0457342.png)
https://github.com/jmjoy/phper/runs/1400337212?check_suite_focus=true

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
That is because `php-dev` is not installed on the GA runner for PHP 7.2 and lower. 
This was fixed in actions/virtual-environments#1945, it will take a week or so for this change to be in images being used.

Till then please specify `php-config` in tools and `setup-php` will install the correct one
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: ${{ matrix.php-version }}
    tools: php-config
```
