### ISSUE TITLE
/opt/hostedtoolcache/linux.sh: line 385: php7.4: command not found

### ISSUE THREAD

**Issue by williamdes** [shivammathur/setup-php#336]
**Describe the bug**
"/opt/hostedtoolcache/linux.sh: line 385: php7.4: command not found"

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [x] Self Hosted

**Operating systems**
https://github.com/myoung34/docker-github-actions-runner

**PHP versions**
7.4

**To Reproduce**
https://github.com/wdes/php-I18n-L10n/commit/78a3013a46ab49ca4bf5cd2865004d0078f897a6#diff-ba61267a4315a0596af390906b6dcee1e40f701f74b741e5bfe7494f5c0040f8R15

**Expected behavior**
Run

**Screenshots/Logs**
```
==> Setup PHP
/opt/hostedtoolcache/linux.sh: line 385: php7.4: command not found
/opt/hostedtoolcache/linux.sh: line 483: php: command not found
/opt/hostedtoolcache/linux.sh: line 484: php: command not found
/opt/hostedtoolcache/linux.sh: line 485: php: command not found
chmod: cannot access '': No such file or directory
```
**Additional context**
Self hosted runner

**Are you willing to submit a PR?**
No

**Comment by shivammathur** [comment]
Please set `runner` environment variable as `self-hosted` and try again.
https://github.com/shivammathur/setup-php#self-hosted-setup
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7.4'
    tools: composer:v2
  env:
    runner: self-hosted # Specify the runner.
```
