### ISSUE TITLE
APCu support for PHP 8.0

### ISSUE THREAD

**Issue by dbalabka** [shivammathur/setup-php#341]
**Describe the bug**
setup-php reports `✗ apcu Could not install apcu on PHP 8.0.0` while the latest version of APCu supports PHP 8.0:
https://pecl.php.net/package-info.php?package=APCu&version=5.1.19

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`runs-on: ubuntu-18.04`

**PHP versions**
`8.0`

**To Reproduce**
```yaml
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        php:
          - version: "7.4"
            allow-fail: false
          - version: "8.0"
            allow-fail: true
```

**Comment by shivammathur** [comment]
@dbalabka
Fixed, please try again
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/372170734/workflow

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.0'
    extensions: apcu
```
