### ISSUE TITLE
Segmentation fault when installing mongodb

### ISSUE THREAD

**Issue by greg0ire** [shivammathur/setup-php#348]
**Describe the bug**
The output is cluttered with warnings, and there is a segmentation fault:

```
==> Setup Extensions
/home/runner/work/_actions/shivammathur/setup-php/v2/dist/../src/scripts/common.sh: line 138: 13465 Broken pipe             yes '' 2> /dev/null
     13466 Segmentation fault      | sudo pecl install -f "$extension" > /dev/null 2>&1
PHP Warning:  Module 'mongodb' already loaded in Unknown on line 0
✓ mongodb Installed and enabled
PHP Warning:  Module 'mongodb' already loaded in Unknown on line 0
PHP Warning:  Module 'mongodb' already loaded in Unknown on line 0
PHP Warning:  Module 'mongodb' already loaded in Unknown on line 0
```

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-20.04

**PHP versions**
PHP 7.2, 7.3 and 7.4 have the issue

**To Reproduce**
```
  phpunit-standalone:
    name: "PHPUnit on standalone servers"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        os:
          - "ubuntu-20.04"
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
        mongodb-version:
          - "4.4"
          - "4.2"
          - "4.0"
          - "3.6"
        driver-version:
          - "stable"
        deps:
          - "normal"
        include:
          - deps: "low"
            os: "ubuntu-20.04"
            php-version: "7.2"
            mongodb-version: "3.6"
            driver-version: "1.5.0"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: "pecl"
          extensions: "mongodb-${{ matrix.driver-version }}, bcmath"
          coverage: "none"
          ini-values: "zend.assertions=1"
```

**Expected behavior**
No segmentation fault

**Screenshots/Logs**
https://github.com/doctrine/mongodb-odm/runs/1462657688?check_suite_focus=true#step:6:21

**Are you willing to submit a PR?**
No
