### ISSUE TITLE
Cannot disable Xdebug on PHP 8.0

### ISSUE THREAD

**Issue by julienfalque** [shivammathur/setup-php#350]
When installing PHP and the Xdebug extension, `phpdismod` does not disable the extension.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`ubuntu-latest`

**PHP versions**
`7.2`, `7.3`, `7.4` and `8.0`. The issue only occurs on `8.0`.

**To Reproduce**
```yaml
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          # `matrix.php-version` is "8.0"
          php-version: ${{ matrix.php-version }}
          # same result with `coverage: xdebug` instead
          extensions: xdebug

      - name: Disable Xdebug
        run: sudo phpdismod xdebug; php -m
```

**Expected behavior**
I would expect `php -m` not to print `xdebug`.

**Comment by shivammathur** [comment]
`phpdismod` script on the runner currently does not support PHP 8.0. In a future release `setup-php` will move to `ppa:ondrej/php` for PHP 8.0 and `phpdismod` would work.

Currently to disable Xdebug on PHP 8 you can do.

1) Prefix xdebug with `:` in extensions input.
```yml
- name: Install PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: ${{ matrix.php-version }}
    extensions: :xdebug
```

2) Specify `coverage: none`.
```yml
- name: Install PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: ${{ matrix.php-version }}
    coverage: none
```

**Comment by julienfalque** [comment]
I tried both solutions but they remove the extension completely. What I need is the extension being installed but not loaded by default. If I understand correctly, this is not supported until moving to `ppa:ondrej/php`. Is there something I can do to help?

**Comment by shivammathur** [comment]
@julienfalque Yes, that is correct.
Currently you can do this manually and switch back to `phpdismod`, once it is available.
To disable `Xdebug`
```yml
- name: Disable Xdebug
  run: |
    scan_dir=$(php --ini | grep additional | sed -e "s|.*: s*||")
    ini_file=$(php --ini | grep "Loaded Configuration" | sed -e "s|.*:s*||" | sed "s/ //g")
    pecl_file="$scan_dir"/99-pecl.ini
    sudo sed -Ei "/xdebug/d" "${ini_file:?}"
    sudo sed -Ei "/xdebug/d" "${pecl_file:?}"
    sudo rm -rf "$scan_dir"/xdebug*
```
To enable it again
```yml
- name: Enable Xdebug
  run: |
    scan_dir=$(php --ini | grep additional | sed -e "s|.*: s*||")
    echo "zend_extension=xdebug" | sudo tee "$scan_dir"/xdebug.ini
```

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/389761481/workflow
