### ISSUE TITLE
PHP 8.0: Could not install imap

### ISSUE THREAD

**Issue by Slamdunk** [shivammathur/setup-php#351]
**Describe the bug**
PHP 8.0: Could not install imap

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
```
Current runner version: '2.274.2'
Operating System
  Ubuntu
  18.04.5
  LTS
Virtual Environment
  Environment: ubuntu-18.04
  Version: 20201115.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20201115.1/images/linux/Ubuntu1804-README.md
```

**PHP versions**
```
  with:
    coverage: pcov
    php-version: 8.0
    ini-values: zend.assertions=1
    tools: pecl
    extensions: imap
```

**To Reproduce**
https://github.com/ddeboer/imap/blob/24a5425a4167002e582fd4af03b4096f2e8619d7/.github/workflows/integrate.yaml#L92

**Screenshots/Logs**
https://github.com/ddeboer/imap/pull/483/checks?check_run_id=1473215042#step:4:24

**Comment by shivammathur** [comment]
Added support in https://github.com/shivammathur/php-builder/commit/70f81b05c3d89f369a7d0c5362e6e3b217b69134
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/391700864/workflow
```yml
name: Setup PHP
uses: shivammathur/setup-php@v2
with:
  php-version: '8.0'
  extensions: imap
```
