### ISSUE TITLE
Could not install imagick on PHP 8.0.0

### ISSUE THREAD

**Issue by MGatner** [shivammathur/setup-php#353]
**Describe the bug**
ImageMagick is failing to install for us on `ubuntu-latest`. It is not listed on the `8.0` extensions list (https://github.com/shivammathur/setup-php/wiki/Php-extensions-on-ubuntu-20.04#php-80) but I also don't see it there for `7.4` which is working fine. I also see this issue has come up before (https://github.com/shivammathur/setup-php/issues/320) and been resolved.

**Version**
- [X] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**
- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`ubuntu-latest`

**PHP versions**
Various (issue is with `8.0.0`)

**To Reproduce**
```
jobs:

  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: PHP ${{ matrix.php-versions }} - ${{ matrix.db-platforms }}

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
        db-platforms: ['MySQLi', 'Postgre', 'SQLite3', 'Sqlsrv']
...
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer, pecl
          extensions: imagick, sqlsrv
          coverage: xdebug
        env:
          update: true
```

**Expected behavior**
Prefer not to see "The ImageMagick extension is not available"

**Screenshots/Logs**
Check the "Setup PHP" step:
https://github.com/codeigniter4/CodeIgniter4/pull/3932/checks?check_run_id=1471547834#step:6:19

**Additional context**
Trying to add support for PHP 8.0 to the CodeIgniter framework

**Are you willing to submit a PR?**
I am comfortable with PRs but would need some direction as to how to troubleshoot the issue. I am also willing to receive a quote for work that needs to be done.
