### ISSUE TITLE
Could not install memcached on PHP 8.0.0

### ISSUE THREAD

**Issue by bensinclair** [shivammathur/setup-php#354]
**Describe the bug**
Memcached is failing to install for us on `ubuntu-latest`. It is not listed on the 8.0 extensions list (https://github.com/shivammathur/setup-php/wiki/Php-extensions-on-ubuntu-20.04#php-80).

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [x] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`ubuntu-latest`

**PHP versions**
`8.0.0`

**To Reproduce**
```
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check Out Code

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        extensions: memcached
```

**Expected behavior**
Memcached should be installed and enabled.

**Screenshots/Logs**
<img width="828" alt="Screen Shot 2020-12-01 at 5 26 54 pm" src="https://user-images.githubusercontent.com/1043658/100709789-6dafa400-33fa-11eb-9325-fa5f22f18de5.png">

**Additional context**
n/a

**Are you willing to submit a PR?**
I'd have to familiarise myself with the codebase but could certainly try if required.

**Comment by shivammathur** [comment]
@bensinclair `setup-php` will move to `ppa:ondrej/php` in a future release for PHP `8.0` and this will not be required then, now you can add a step above `setup-php` step to install `libmemcached-dev` and `memcached` extension will be setup successfully by `setup-php`

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/393821866/workflow

```yml
- name: Install libmemcached
  run: sudo apt-get install libmemcached-dev -y

- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.0'
    extensions: memcached
```

**Comment by shivammathur** [comment]
@bensinclair Now setup-php uses PHP 8 from `ppa:ondrej/php` and just specifying memcached in extensions input would work.
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.0'
    extensions: memcached
```
