### ISSUE TITLE
Setup Coverage keeps failing for only PHP 7.4 in macos-latest

### ISSUE THREAD

**Issue by 5amfung** [shivammathur/setup-php#355]
**Describe the bug**

Any idea why the job keeps failing for PHP `7.4` and `macos-latest`?
But `7.3` is fine.

https://github.com/adobe/target-php-sdk/pull/6/checks?check_run_id=1490104506

```
==> Setup Coverage
Error: The process '/bin/bash' failed with exit code 1
```

```
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ macos-latest ]
        php-versions: [ '7.4' ]
    name: Tests with PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug
          ini-values: max_execution_time=300
        env:
          fail-fast: true
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

macos-latest

**PHP versions**

7.4

**To Reproduce**

https://github.com/adobe/target-php-sdk/blob/a49412b96f948bb2bb8cfef7e31f0b1946d34df7/.github/workflows/main.yml

**Expected behavior**

Should not fail.

**Screenshots/Logs**

![image](https://user-images.githubusercontent.com/371691/100954988-8c7d6b80-34ca-11eb-8d48-300e870665e8.png)

**Additional context**

**Are you willing to submit a PR?**
