### ISSUE TITLE
Running vimeo/psalm reports errors when running in setup-php

### ISSUE THREAD

**Issue by danfraticiu** [shivammathur/setup-php#356]
**Describe the bug**
Running psalm reports errors about missing php 8 functions (ex: str_contains str_ends_with) even though symfony/polyfill-php80 is installed.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
7.4

**To Reproduce**
```
jobs:
  psalm:
    if: github.ref == 'refs/heads/feature/SHIFT-1498-psalm'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: psalm
      
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      
      - name: Install dependencies
        run: composer install --prefer-dist --no-scripts

      - name: Run Psalm
        run: psalm --output-format=github
```

**Expected behavior**
Output from pslam 
```
------------------------------
No errors found!
------------------------------
```

**Screenshots/Logs**
<img width="625" alt="CleanShot 2020-12-03 at 13 15 40@2x" src="https://user-images.githubusercontent.com/1186135/101005988-ade16480-3569-11eb-959a-bb1fb3ee731a.png">

<img width="766" alt="CleanShot 2020-12-03 at 13 17 38@2x" src="https://user-images.githubusercontent.com/1186135/101006940-f731b400-3569-11eb-9a1a-a1387441f43d.png">

**Additional context**

Running `vendor/bin/psalm` in the Docker container or locally will return "No errors found".

**Are you willing to submit a PR?**
n/a
