### ISSUE TITLE
php/5.3.29/lib/libmemcached.so.11: file too short

### ISSUE THREAD

**Issue by glensc** [shivammathur/setup-php#358]
**Describe the bug**

Appears that `ext-memcached` extension dependant library `libmemcached.so.11` is truncated:

```
Warning: PHP Startup: Unable to load dynamic library '/home/runner/php/5.3.29/lib/php/extensions/no-debug-non-zts-20090626/memcached.so' - /home/runner/php/5.3.29/lib/libmemcached.so.11: file too short in Unknown on line 0
```

You can see the job output in this job:
- https://github.com/glensc/php-zf1s/runs/1512646164?check_suite_focus=true

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**

5.3

**To Reproduce**

```yaml
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: 5.3
          extensions: memcached

      - name: Test ext-memcached
        run: |
          php -m
          php -r 'var_dump(extension_loaded("memcached"));'
```

**Expected behavior**

**Screenshots/Logs**

- https://github.com/glensc/php-zf1s/runs/1512646164?check_suite_focus=true

**Additional context**

**Are you willing to submit a PR?**
