### ISSUE TITLE
Phive doesn't work on PHP7.1

### ISSUE THREAD

**Issue by dbrekelmans** [shivammathur/setup-php#366]
**Describe the bug**
With `php-version: 7.1` and `tools: phive`, this action installs a version of phive that is not compatible with php7.1. Phive's github releases mention: `Please note: Version 0.14.x requires PHP 7.2 or later.`, so I'm assuming version `0.13.x` works with PHP7.1, but I have not tested this.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
7.1

**To Reproduce**
```
with:
    php-version: 7.1
    tools: phive
```

**Expected behavior**
`run: phive install --force-accept-unsigned` works without issues

**Screenshots/Logs**
```
Run phive install --force-accept-unsigned
  phive install --force-accept-unsigned
  shell: /bin/bash -e {0}
Phive requires PHP 7.2 or later; Upgrading to the latest version of PHP is highly recommended. (Version used: 7.1.33-24+ubuntu18.04.1+deb.sury.org+1)

Error: Process completed with exit code 1.
```

**Additional context**

**Are you willing to submit a PR?**

Not likely at the moment as I can work around it, but maybe in the future when I have some free time

**Comment by shivammathur** [comment]
Yes, unless you specify the version for the tool, it will install the latest version.

To install say phive 0.13.5, you can specify the version.
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
     php-version: '7.1'
     tools: phive:0.13.5
```

To setup different versions of phive with different PHP versions, you can use the matrix.

```yml
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:      
        php-versions: ['7.2', '7.3']
        phive-versions: ['latest']
        
        # Include special cases
        include:
        - php-versions: '7.1'
          phive-versions: '0.13.5'
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: phive:${{ matrix.phive-versions }}
```
**Test workflow:** https://github.com/shivammathur/test-setup-php/actions/runs/418759844/workflow
