### ISSUE TITLE
PHP 8 is now default on Ubuntu GitHub-hosted environments 

### ISSUE THREAD

**Issue by shivammathur** [shivammathur/setup-php#369]
Default PHP version was changed to PHP 8.0 on Ubuntu GitHub-hosted environments.
Now `setup-php` uses the PHP 8.0 from `ppa:ondrej/php` which is pre-installed, instead of builds from `shivammathur/php-builder`.

- If you face any issues with PHP 8 because of this, please report them.

- If you require PHP 7.4 which was the previous default version. It is recommended to use `setup-php` to pin your version as the first step.
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7.4'
```

**Comment by MMLaws7** [comment]
![CookiePro Knowledge About CookiePro Hosting Options, Locations, and Backup](https://user-images.githubusercontent.com/76396199/105574531-2965c380-5d1a-11eb-9536-02fc8b282c9e.png)

**Comment by ThibaultVlacich** [comment]
Setting the PHP version to "8.0" installs PHP 8.0.0, and not 8.0.1 which has been released for a few weeks.

**Comment by shivammathur** [comment]
@ThibaultVlacich 

PHP 8.0 version was updated to 8.0.1 in the pre-releases images yesterday, they will be deployed likely by end of the week.
https://github.com/actions/virtual-environments/releases

By default `setup-php` does not upgrade PHP versions installed on the images as it adds to the workflow run time, so to always get latest patch releases you can set `update` env variable to true.

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.0'
  env:
    update: true
```
