### ISSUE TITLE
xdebug doesn't disables with coverage 'none'

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#370]
**Describe the bug**

On docs said:
> Specify coverage: none to remove both Xdebug and PCOV.

> It will remove Xdebug, which will have a positive impact on PHP performance.

https://github.com/shivammathur/setup-php#disable-coverage

But `phan/phan` library still say that `xdebug` is enabled
![image](https://user-images.githubusercontent.com/3289702/102482176-b7cf9100-405a-11eb-9f4d-74da18375f16.png)

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu

**PHP versions**
`7.4`

**To Reproduce**
```
uses: shivammathur/setup-php@v2
with:
    php-version: '7.4'
    coverage: none

run: vendor/bin/phan
```

**Expected behavior**
Info message do not appear.

**Are you willing to submit a PR?**
No
