### ISSUE TITLE
Section "Setup Tools" is extremely slow and/or throws errors sometimes

### ISSUE THREAD

**Issue by froemken** [shivammathur/setup-php#373]
**Describe the bug**
Something weird happens while processing "Setup Tools" section. This process is extremely slow and sometimes it breaks with the message:

```
==> Setup Tools
| ✗ composer Could not download composer
[CI/PHP Unit and Functional Tests-2]   ❗  ::error::The process '/bin/bash' failed with exit code 1
[CI/PHP Unit and Functional Tests-2]   ❌  Failure - Set up PHP Version ${{ matrix.php }}
Error: exit with `FAILURE`: 1
```

Interesting: I don't have defined any tools:
```
      - name: Set up PHP Version ${{ matrix.php }}
        #uses: shivammathur/setup-php@v2
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl, mysql
          ini-values: memory_limit=1024M, max_execution_time=30
          coverage: none
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 18.04

**PHP versions**
7.2, 7.2, 7.4

**To Reproduce**
```
jobs:
  testing:
    runs-on: 'ubuntu-18.04'
    name: PHP Unit and Functional Tests
    strategy:
      fail-fast: true
      matrix:
        typo3: ['^9.5', '^10.4']
        php: ['7.2', '7.3', '7.4']
        include:
          # Reduce side effects while running functional tests
          - typo3: '^9.5'
            db-name: 'mysql_95'
          - typo3: '^10.4'
            db-name: 'mysql_104'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP Version ${{ matrix.php }}
        #uses: shivammathur/setup-php@v2
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, iconv, intl, mysql
          ini-values: memory_limit=1024M, max_execution_time=30
          coverage: none
          tools: composer:v1

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          composer require typo3/cms-extensionmanager:${{ matrix.typo3 }} --no-progress
          git checkout composer.json

      # Will only work, if you define an env file with act --env-file
      # act pull_request -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04 --env-file ~/htdocs/.env.act.ci
      # The env file must contain these typo3Database* vars
      - name: Functional Tests locally
        if: ${{ env.GITHUB_ACTOR == 'nektos/act' }}
        env:
          typo3DatabaseName: ${{ matrix.db-name }}
          COMPOSER_PROCESS_TIMEOUT: 600
        run: composer ci:tests:functional
```

**Expected behavior**
Do not install any tools or do the job behind "Setup Tools" much faster or without error

**Screenshots/Logs**
I have tried many things, but every docker logs [hash] is empty

**Additional context**
My executed command:
`act pull_request -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04 -vvv --env-file ~/htdocs/.env.act.ci`

**Are you willing to submit a PR?**
Currently no, as I'm new to act since today

**Comment by froemken** [comment]
I'm testing/working with your package since this morning 09:30. That's nearly 10 hours and I'm started your tool again and again. Maybe there are limitations at composer or github servers which reduce my download rate or close my requests.

**Comment by shivammathur** [comment]
Please use `shivammathur/node` docker images to run `setup-php` with `nektos/act`
https://github.com/shivammathur/setup-php#local-testing-setup.

```
# For runs-on: ubuntu-latest
act -P ubuntu-latest=shivammathur/node:latest

# For runs-on: ubuntu-20.04
act -P ubuntu-20.04=shivammathur/node:focal

# For runs-on: ubuntu-18.04
act -P ubuntu-18.04=shivammathur/node:bionic

# For runs-on: ubuntu-16.04
act -P ubuntu-16.04=shivammathur/node:xenial
```

**Comment by froemken** [comment]
In another ticket you told us to use this 18GB image, when we need parallel, git and other tools.

**Comment by shivammathur** [comment]
Can you point to the ticket. Since I added support for `nektos/act` in `setup-php`, we have only recommended using the images `shivammathur/node` which are built especially for this.

**Comment by froemken** [comment]
Ok...found it, but it wasn't you. Sorry

https://github.com/nektos/act/issues/107

**Comment by froemken** [comment]
I have switched back to your recommended ticket. Same problem:

```
➜ act pull_request -P ubuntu-18.04=shivammathur/node:bionic --env-file ~/htdocs/.env.act.ci
[CI/Coding Standard                ] 🚀  Start image=shivammathur/node:bionic
[CI/Coding Standard                ]   🐳  docker run image=shivammathur/node:bionic entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[CI/Coding Standard                ]   🐳  docker cp src=/Users/froemken/htdocs/typo3_104/public/typo3conf/ext/checkfaluploads/. dst=/github/workspace
[CI/Coding Standard                ] ⭐  Run Checkout
[CI/Coding Standard                ]   ✅  Success - Checkout
[CI/Coding Standard                ] ⭐  Run Setup PHP with tools
[CI/Coding Standard                ]   ☁  git clone 'https://github.com/shivammathur/setup-php' # ref=v2
[CI/Coding Standard                ]   🐳  docker cp src=/Users/froemken/.cache/act/shivammathur-setup-php@v2 dst=/actions/
| [command]/bin/bash /opt/hostedtoolcache/linux.sh 7.3 /actions/shivammathur-setup-php@v2/dist
| 
| ==> Setup PHP
| ✓ PHP Switched to PHP 7.3.24
| 
| ==> Setup Tools
```

Nothing happens since 5 minutes.

**Comment by froemken** [comment]
I have reduced my yaml to this minimal configuration:

```
name: CI

on: [pull_request]

jobs:
  coding:
    name: Coding Standard
    runs-on: 'ubuntu-18.04'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl
          ini-values: max_execution_time=30
          coverage: none
```

I have stopped and removed the container (not image) with docker stop and docker rm.

Command: `act pull_request -P ubuntu-18.04=shivammathur/node:bionic`

no tests, no matrix, no env vars, nothing.

```
1a4c761c0f6c   shivammathur/node:bionic  "/usr/bin/tail -f /d…"   11 minutes ago   Up 11 minutes                                                                                                   act-CI-Coding-Standard
```

I just have requested a new IP address in my FritzBox. But problem still exists.
