### ISSUE TITLE
Using PHP 7.0.x and getting PHP deprication error specific to 7.4

### ISSUE THREAD

**Issue by kabalin** [shivammathur/setup-php#384]
Not sure if this is the bug. We are using this action in https://github.com/moodlehq/moodle-plugin-ci project. Somehow same phpunit test started reporting deprication error specific to 7.4 while it is clearly run on 7.0.33, which has been setup using [syntax as follows](https://github.com/moodlehq/moodle-plugin-ci/blob/master/.github/workflows/test.yml#L73:L78):
```
    - name: Setup PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: pgsql, zip, gd, xmlrpc, soap
        coverage: none
```
Here is example of issue: https://github.com/moodlehq/moodle-plugin-ci/pull/61/checks?check_run_id=1600314186

It says at the beginning that PHP in use is clearly 7.0.33 (https://github.com/moodlehq/moodle-plugin-ci/pull/61/checks?check_run_id=1600314186#step:8:33), but then later fails on the error specific to 7.4 (https://github.com/php/php-src/pull/4416), so this is really odd to see it on 7.0.33.

The target repo code it is using for local tests is legacy, there were no changes there either. Same code test last was run 26 days ago with no issues and used the same PHP 7.0.33 (e.g. https://github.com/moodlehq/moodle-plugin-ci/actions/runs/387804242).

Just flagging up in case some recent chnage in this project made this misbehaviour occur, otherwise feel free to close.
