### ISSUE TITLE
test matrix uses "default" phpunit version, not the one specified for a particular php version

### ISSUE THREAD

**Issue by yivi** [shivammathur/setup-php#385]
Running with this:

```yaml
matrix:
        php-versions: ['7.3', '7.4', '8.0']
        phpunit-versions: ['latest']
        include:
          - php-versions: '7.2'
            phpunit-versions: '8.5.13'
```

I expect the jobs to be run with the latest phpunit version for PHP 7.3, 7.4 and 8.0, and phpunit version 8.5.13 for PHP 7.2

I tried this locally, and it works.

```
act -P ubuntu-latest=shivammathur/node:latest
```

But when I execute it on Github, I get:

```none
Run phpunit --coverage-text --coverage-clover=coverage.clover
PHPUnit 9.5.0 by Sebastian Bergmann and contributors.

This version of PHPUnit is supported on PHP 7.3 and PHP 7.4.
You are using PHP 7.2.34-8+ubuntu18.04.1+deb.sury.org+1 (/usr/bin/php7.2).
Error: Process completed with exit code 1.
```

![CleanShot 2020-12-23 at 17 01 35](https://user-images.githubusercontent.com/1815039/103015355-9120c700-4540-11eb-94f0-d2603464d257.png)

The whole job definition file 

```
on:
  push:
    branches:
      - 'master'
jobs:
  run:
    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0']
        phpunit-versions: ['latest']
        include:
          - php-versions: '7.2'
            phpunit-versions: '8.5.13'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: pdo_sqlite
          coverage: xdebug
          tools: composer, phpunit

      - name: install everything
        run: composer install

      - name: run tests
        run: phpunit --coverage-text --coverage-clover=coverage.clover

```
