### ISSUE TITLE
ext-ldap fails to enable on 5.3

### ISSUE THREAD

**Issue by glensc** [shivammathur/setup-php#386]
**Describe the bug**

somewhy `ext-ldap` is missing for 5.3 (you need to click on "Setup PHP 5.3" to see output):
- https://github.com/glensc/php-zf1s/runs/1597658212?check_suite_focus=true

```
==> Setup Extensions
✓ ctype Enabled
✓ dom Enabled
✓ gd Enabled
✓ iconv Enabled
✗ ldap Could not install ldap on PHP 5.3.29
✓ mbstring Enabled
...
```

and it's silently failing, i.e config request the extension, and it does not get enabled and job succeeds.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Linux

**PHP versions**

5.3

**To Reproduce**

```yml

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 5.3
          extensions: ldap
```

Full file:
- https://github.com/glensc/php-zf1s/blob/e370af93e1dc3a6a0f91fca3563370b56d79837c/.github/workflows/tests.yml

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

Si, Señor!
