### ISSUE TITLE
PHP 7.3: PHP Warning:  Module 'PDO' already loaded in Unknown on line 0

### ISSUE THREAD

**Issue by greg0ire** [shivammathur/setup-php#387]
Happy new year!

**Describe the bug**
The output of the job, and the output of subsequent job contains the warning in the title.
Also, a PHAR compiled on the test machine exits with a non-zero exit status

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

`ubuntu-20.04`

**PHP versions**

The issue occurs only on PHP 7.3, and we use 7.1 through 8.0

**To Reproduce**

```
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP with PCOV"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.3"
          coverage: "pcov"
          extensions: "pdo_sqlite"
          ini-values: "zend.assertions=1"

      - name: "Download box"
        run: "./download-box.sh"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-7.3-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-7.3-composer-locked-"

      - name: "Install dependencies with composer"
        run: "composer update --no-interaction --prefer-dist --no-progress"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"
```

**Expected behavior**

I expect no error about PDO, and a zero exit status

**Screenshots/Logs**

https://github.com/doctrine/migrations/pull/1105/checks?check_run_id=1631281228

**Additional context**

Nothing to add

**Are you willing to submit a PR?**

No
