### ISSUE TITLE
Breaks actions/setup-node if run after that action

### ISSUE THREAD

**Issue by anomiex** [shivammathur/setup-php#389]
**Describe the bug**

If this action is run after actions/setup-node, the wrong version of node may be used.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

ubuntu-latest

**PHP versions**

7.4, although I don't think it matters.

**To Reproduce**

```yaml
  runs-on: ubuntu-latest
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer
        coverage: none
    - name: Tool versions
      run: |
        which node
        node --version
```

**Expected behavior**

The "Tool versions" step outputs
```
/opt/hostedtoolcache/node/12.20.0/x64/bin/node
v12.20.0
```

**Screenshots/Logs**

The "Tool versions" step instead outputs
```
/usr/local/bin/node
v14.15.1
```
You may be able to see it in action at https://github.com/Automattic/jetpack/runs/1653040181?check_suite_focus=true#step:8:15

**Additional context**

It seems that 77721f66 caused this action to start prepending /usr/local/bin to the path, and GitHub's action runners seem to have a node binary in that directory.

It looks like you might work around it by changing [src/scripts/common.sh:9](https://github.com/shivammathur/setup-php/blob/77721f6/src/scripts/common.sh#L9) to point to some directory created by the action instead of using `/usr/local/bin`. But I see other instances of `/usr/local/bin` in the action that may also need to be changed.

**Are you willing to submit a PR?**

If necessary.
