### ISSUE TITLE
Incorrect behaviour of ini-values-csv argument on windows/7.4

### ISSUE THREAD

**Issue by SerafimArts** [shivammathur/setup-php#39]
A `windows-2019 / php 7.4` causes an installtion error when `ini-values-csv` argument is specified.

**To Reproduce**

```yml
name: CI

on: [push]

jobs:
  run:
    runs-on: windows-2019
  - name: 'Preparation (Windows)'
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.4
        ini-values-csv: 'extension=php_mbstring'
```

**Actual**

```
findstr : FINDSTR: Bad command line
At D:\a\graphql\graphql\7.4win32.ps1:44 char:17
+   if(!(php -m | findstr -i ) -and $exist) {
+                 ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (FINDSTR: Bad command line:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Could not find extension: 
done
```

![image](https://user-images.githubusercontent.com/2461257/65713245-793e6700-e0a1-11e9-801c-ecd2bf933a4a.png)

https://github.com/railt/graphql/runs/237694686

**Expected**

Add `extension=php_mbstring` parameter to end of the `php.ini` file.
