### ISSUE TITLE
sonar-cloud path problem

### ISSUE THREAD

**Issue by aradhell** [shivammathur/setup-php#390]
**Describe the bug**

/entrypoint.sh: line 24: sonar-scanner: command not found

Related topic https://community.sonarsource.com/t/github-action-sonarsource-sonarcloud-github-action-stopped-working/36665
https://github.com/shivammathur/setup-php/commit/4ddd49b7006f4d85e917f50908dbdc657c00c432

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**
7.4

**To Reproduce**
```
- name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**
