### ISSUE TITLE
Swoole extension latest installed instead of specified version

### ISSUE THREAD

**Issue by sshymko** [shivammathur/setup-php#391]
**Describe the bug**
Latest version of the Swoole extension (perhaps any extension?) is installed despite the configured specific version.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
- ubuntu-latest

**PHP versions**
- PHP 7.1, 7.2, 7.3, 7.4

**To Reproduce**
```yaml
jobs:
  tests:
    name: Test ${{ matrix.swoole-version }} against php ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.1', '7.2', '7.3']
        swoole-version:
          - swoole-4.0.4
          - swoole-4.1.2
          - swoole-4.2.13
          - swoole-4.3.6
          - swoole-4.4.22
          - swoole-4.5.8
          - swoole
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ matrix.swoole-version }}
          coverage: none
        env:
          fail-fast: true
      - name: Verify PHP environment
        run: php --ri swoole
```

**Expected behavior**
- Swoole extension version returned by `php --ri swoole` matches the configuration `extensions: swoole-X.Y.Z`

**Screenshots/Logs**
- Latest version of the Swoole extension is installed despite the configuration `extensions: swoole-X.Y.Z`
https://github.com/upscalesoftware/swoole-reflection/runs/1579859676?check_suite_focus=true
