### ISSUE TITLE
INI values with embedded commas parsed incorrectly

### ISSUE THREAD

**Issue by bishopb** [shivammathur/setup-php#392]
**Describe the bug**

XDebug 3 supports an [`xdebug.mode` INI setting][1] whose _values_ may be a comma-separated list: for example, `xdebug.mode=develop,gcstats,coverage`.

However, SPC fails to correctly parse this INI option:

```sh
$ spc --ini-values 'xdebug.mode=develop,gcstats,coverage'
<snip>
==> Add php.ini values
✓ xdebug.mode=develop Added to php.ini
✓ gcstats Added to php.ini
✓ coverage Added to php.ini
```

That's because the [CSVArray method][2] unconditionally splits on a comma, without first understanding that the comma is used in the value itself.

[1]:https://xdebug.org/docs/all_settings#mode
[2]:https://github.com/shivammathur/setup-php/blob/master/src/utils.ts#L251

**Version**
- [X] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [ ] `v2`
- [ ] `v1`

**Runners**
- [X] GitHub Hosted
- [X] Self Hosted

**Operating systems**

Ubuntu, MacOS, and Windows

**PHP versions**

5.5+, though this particular issue with xdebug.mode only applies to 7.3+ with XDebug 3.

**To Reproduce**

In YAML, this would be represented as:

```yaml
- uses: shivammathur/setup-php@v2                                       
  with:                                                                 
    ini-values: xdebug.mode=develop,gcstats,coverage         
```

**Expected behavior**

When support for INI values with commas is available, I would expect the INI file to have a single INI value added, whose value is exactly as given. Thus, if the INI given is "x=a,b" I would expect the INI file to have exactly that one line. Today, however, the INI file gets two lines: "x=a" followed by "b".

**Additional Context**

There are many other INI values that could technically have a comma in them: any ones dealing with file paths, dates, times, monetary values, MIME types, user-facing prompts, and PDO DSN. For a concrete example, consider [url_rewriter.hosts][3]:

> url_rewriter.hosts string
> url_rewriter.hosts specifies which hosts are rewritten to include output_add_rewrite_var() values. Defaults to
> $_SERVER['HTTP_HOST']. Multiple hosts can be specified by ",", no space is allowed between hosts. e.g. 
> php.net,wiki.php.net,bugs.php.net

Consequently, I don't think this is a niche problem, but rather one that is an edge case.

[3]:https://www.php.net/manual/en/outcontrol.configuration.php#ini.url-rewriter.tags

**Are you willing to submit a PR?**

Yes.

**Comment by shivammathur** [comment]
@bishopb 
I have added a patch (https://github.com/shivammathur/setup-php/commit/c9e1d2ca9cff1c4358170e4a94a6d3cf721700e0) to support quoted csv in `ini-values` input. So now it won't split commas inside quotes.

For example, this would work.
```yml
ini-values: xdebug.mode="develop,gcstats,coverage", date.timezone=UTC
```

Before I merge this, can you test this using the develop branch (shivammathur/setup-php@develop)

**Comment by bishopb** [comment]
Confirmed, the patch works as described. Thank you!

**Comment by shivammathur** [comment]
@bishopb Thanks for testing. Merged and updated `v2`.

**Comment by smichae** [comment]
@shivammathur This seems to have broken a build where pcov.directory and pcov.exclude are set in ini-values. I've attempted with the escape and without, as well as with single quotes, but nothing seems to work any more - it was working up until a few days ago.
`pcov.exclude=\"~(excluded|regex)~\"`

**Comment by shivammathur** [comment]
@smichae can you provide the test yaml and workflow. Are quotes required by pcov?

**Comment by smichae** [comment]
@shivammathur 
Here's a sample of what I've been using:
```
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: pcov
          ini-values: memory_limit=-1, pcov.directory=/home/runner/work/jobname/jobname, pcov.exclude=\"~(.tests|vendor)~\"
          extensions: curl, gd, gmp, intl, json, mbstring, memcached, pcov, readline, xml, zip
```
Yes, I believe the quotes are required for pcov to properly parse the exclude.

And in case it helps, the error I'm getting in the actions readout: /opt/hostedtoolcache/linux.sh: line 343: syntax error near unexpected token `('
