### ISSUE TITLE
How to use github secrets with setup-php when installing private packages via Composer

### ISSUE THREAD

**Issue by nivv** [shivammathur/setup-php#393]
**Describe the feature**
Add documention to clarify how to use github secrets with private/public keys with Composer

**Version**
- [X] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
I've checked issues on this project, but have not found any solution. #107 seems to be related, maybe it's outdated?

**Describe alternatives**
Using composer stand alone action below worked:
```yml
    - name: Install dependencies
      uses: php-actions/composer@v2
      with:
        ssh_key: ${{ secrets.ssh_key }}
        ssh_key_pub: ${{ secrets.ssh_key_pub }}
```

I can't seem to find a way to do the equivalent with the `setup-php`-action

**Additional context**

**Are you willing to submit a PR?**
Yes, if there is documentation that needs updating

**Comment by shivammathur** [comment]
@nivv 
https://github.com/shivammathur/setup-php/discussions/287#discussioncomment-76265
This should work, let me know if it doesn't.

**Comment by nivv** [comment]
@shivammathur that worked nicely, I didn't have to create the `.ssh` dir though. See my complete workflow below:

```yml
# GitHub Action for Laravel
name: tests
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  laravel:
    name: Laravel (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: exif
          coverage: pcov #optional
          # ssh_key: ${{ secrets.ssh_key }}
          # ssh_key_pub: ${{ secrets.ssh_key_pub }}
        env:
          # COMPOSER_AUTH: {"github-oauth": {"github.com": "${{ secrets.ci_token }}" }}
          COMPOSER_TOKEN: ${{ secrets.ci_token }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ssh_key }}
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Prepare the application
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate

      - name: Clear Config
        run: php artisan config:clear

      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-text --testdox
```
