### ISSUE TITLE
Cannot install Pecl http extension

### ISSUE THREAD

**Issue by llaville** [shivammathur/setup-php#396]
**Describe the bug**

Cannot install pecl `http` extension 3.2.4 (http://pecl.php.net/package/pecl_http) 

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Ubuntu 18.04

**PHP versions**

PHP 7.4.13

**To Reproduce**

Workflow is available online at https://github.com/llaville/php-compatinfo-db/blob/master/.github/workflows/php-tests.yaml

**Expected behavior**

Extension `http` and its dependencies `raphf` and `propro` installed

**Screenshots/Logs**

Logs available at https://github.com/llaville/php-compatinfo-db/runs/1713249088#step:3:65

![github_com_llaville_php-compatinfo-db_runs_1713249088#step_3_65](https://user-images.githubusercontent.com/364342/104808860-431e7c80-57e9-11eb-8311-67ece69ce6c3.png)

**Additional context**

I'm be able to install `http` pecl extension 3.2.4 on my docker environment, Ubuntu 18.04, PHP 7.4.14 with all its dependencies (`raphf` 2.0.1, `propro` 2.1.0, and librairies as explained at https://mdref.m6w6.name/http), in my project : see comment at https://github.com/llaville/php-compatinfo-db/issues/63#issuecomment-761535682

 I've also tried to install it locally with [act](https://github.com/nektos/act) 0.2.17 without success: see comment at https://github.com/llaville/php-compatinfo-db/issues/63#issuecomment-760091985

**Are you willing to submit a PR?**

No skill to do it, sorry !

**Comment by shivammathur** [comment]
To install from packages.

specify extensions in this order `raphf, propro, http`

```yml
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: raphf, propro, http
```
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/489948004/workflow


To install using PECL:

Install `libcurl4-openssl-dev -y` before running `setup-php` and suffix `pecl_http` with appropriate versions of `PHP 7.4` and `PHP 8.0`.

```yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '7.4'
            extensions: 'pecl_http-3.2.4'
          - php: '8.0'
            extensions: 'pecl_http-4.0.0'
    steps:
      - run: sudo apt-fast install libcurl4-openssl-dev -y  
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
```

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/489958829/workflow
