### ISSUE TITLE
Cant remove extension

### ISSUE THREAD

**Issue by fezfez** [shivammathur/setup-php#402]
Hello,

I try to remove extension with ":" prefix but it seem to have no effect

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [x] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

ubuntu-latest

**PHP versions**

7.4

**To Reproduce**
```yml
name: "Static Analysis by PHPStan"

on:
  pull_request:
  push:

jobs:
  static-analysis-psalm:
    name: "Static Analysis by PHPStan"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.4"
          coverage: none
          ini-values: memory_limit=-1
          tools: composer:v2
          extensions: :amqp :apcu :bcmath :bz2 :curl :dba :enchant :gd :gmp :igbinary :imap :ldap :memcache :memcached :mongodb :msgpack :odbc :pdo_dblib :PDO_Firebird :PDO_ODBC :pdo_pgsql :pdo_sqlite :pgsql :pspell :redis :snmp :soap :sqlite3 :tidy :xmlrpc :yaml :zip :zmq

      - name: "Install locked dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "show php module"
        run: "php -m"

      - name: "phpstan LargeMemoryConsumption"
        run: "./vendor/bin/phpstan analyse --debug -vvv src/LargeMemoryConsumption.php"

      - name: "phpstan MemoryConsumptionMini"
        run: "./vendor/bin/phpstan analyse --debug -vvv src/MemoryConsumptionMini.php"

```

**Expected behavior**
when running `php -m` bcmath  should not  be loaded for example

**Screenshots/Logs**
https://github.com/fezfez/phpstan-memory/blob/e3dbc37266c573dbda70cb4ba68a32f3bcc7a52b/.github/workflows/phpstan.yml
https://github.com/fezfez/phpstan-memory/runs/1769618922?check_suite_focus=true
