### ISSUE TITLE
Set-up with extensions: json, but json_decode still not available

### ISSUE THREAD

**Issue by derickr** [shivammathur/setup-php#403]
**Describe the bug**

I'm adding CI for https://github.com/php-geospatial/geospatial and [two of the tests](https://github.com/php-geospatial/geospatial/runs/1783964741?check_suite_focus=true#step:6:7) use `json_decode`. I have added `extensions: json` to the workflow, but it doesn't seem loaded.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
The default, so I guess Linux?

**PHP versions**
PHP 7.0 - 7.4 show the problem, PHP 8.0/8.1 do not.

**To Reproduce**

```
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none
                    ini-values: "session.save_path=/tmp"
                    extensions: json
                    tools: pecl
```

**Expected behavior**
`json_decode()` should be available

**Screenshots/Logs**
https://github.com/php-geospatial/geospatial/runs/1783964741?check_suite_focus=true#step:6:1

**Additional context**
The wiki says that json should have been loaded by default, so I am wondering what's going on.

**Are you willing to submit a PR?**
Sure, if I know what the problem is and how to fix it (I don't).
