### ISSUE TITLE
ext-ldap fails to enable on 5.4/5.5

### ISSUE THREAD

**Issue by glensc** [shivammathur/setup-php#407]
**Describe the bug**

Similarly to https://github.com/shivammathur/setup-php/issues/386 but now for 5.4/5.5:

somewhy `ext-ldap` is missing for 5.4/5.5 (you need to click on "Setup PHP 5.x" to see output):
- 5.4: https://github.com/zf1s/zf1/pull/42/checks?check_run_id=1831329804
- 5.5: https://github.com/zf1s/zf1/pull/42/checks?check_run_id=1831329832

```
==> Setup Extensions
✓ ctype Enabled
✓ dom Enabled
✓ gd Enabled
✓ iconv Enabled
✗ ldap Could not install ldap on PHP 5.3.29
✓ mbstring Enabled
...
```

and it's silently failing, i.e config requests the extension, and it does not get enabled and job succeeds.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Linux

**PHP versions**

5.4, 5.5

**To Reproduce**

```yml

      - name: Setup PHP 5.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: 5.4
          extensions: ldap

      - name: Setup PHP 5.5
        uses: shivammathur/setup-php@v2
        with:
          php-version: 5.5
          extensions: ldap
```

Full file:
- https://github.com/glensc/php-zf1s/blob/e370af93e1dc3a6a0f91fca3563370b56d79837c/.github/workflows/tests.yml

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

Si, Señor!

**Comment by shivammathur** [comment]
@glensc In my testing, I was unable to reproduce the issue. It should download the `ldap` package from the `dotdeb` repository and install it. Might have been a network issue. Can you try restarting your workflow and see if it fails again.

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/538579409/workflow

**Comment by glensc** [comment]
@shivammathur how about making failure to set up a required extension to be a fatal error?

**Comment by shivammathur** [comment]
By default `setup-php` does not end the workflow on tools and extension errors. This is done to allow cross-platform workflows as some extensions and tools only support a particular OS. 

You can change that by specifying `fail-fast` to `true`.

```yml
- name: Setup PHP with fail-fast
  uses: shivammathur/setup-php@v2
  with:
    php-version: '5.4'
    extensions: ldap
  env:
    fail-fast: true
```

Anyway this issue should not occur again as I have added `ldap` packages for PHP 5.4 and 5.5 in `php5-ubuntu`.
