### ISSUE TITLE
Add support for latest PHP versions

### ISSUE THREAD

**Issue by reypm** [shivammathur/setup-php#408]
**Describe the bug**
PHP 7.4.15 and PHP 8.0.2 were released a few days ago. This action does not seem to support them yet as per the below results from GA on a PR to our repository even forcing the version to be 7.4.15 as you will note below in the attached configuration:

![image](https://user-images.githubusercontent.com/627886/107292931-aaba9700-6a38-11eb-9389-d7322e3f9453.png)

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-20.04

**PHP versions**
7.4.15

**To Reproduce**
```
name: PHP Integration Workflow
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4.15 // leaving this as 7.4 should also install the latest available version
          extensions: intl, bcmath, apcu, redis
          ini-values: "post_max_size=256M" #optional
          tools: composer:v2
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
```

**Expected behavior**
The right version of PHP is installed. 

**Additional context**
Maybe Ubuntu has not updated or released latest version of PHP as yet

**Are you willing to submit a PR?**
Yes, if needed
