### ISSUE TITLE
define php-version via env var

### ISSUE THREAD

**Issue by clxmstaab** [shivammathur/setup-php#417]
**Describe the feature**

I want to define the php version via env var, but it seems this is not allowed?

```
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: {{ env.TARGET_PHP_VERSION }}
```

I am getting this error:

![image](https://user-images.githubusercontent.com/47448731/108983110-ce175000-768e-11eb-9399-561f7ca1722e.png)

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

depending on configuration I want to define the target php version beeing used.

**Describe alternatives**

**Additional context**

**Are you willing to submit a PR?**
