### ISSUE TITLE
Missing sqlite extension on Ubuntu 20.04.2 for PHP 7.3

### ISSUE THREAD

**Issue by dmitry-ivanov** [shivammathur/setup-php#424]
**Describe the bug**
Today I've made some changes in the readme file, and my tests became red on Ubuntu 20.04.2 for PHP 7.3.

It looks like there's no sqlite extension available for this combination:
https://github.com/dmitry-ivanov/laravel-testing-tools/runs/2025869782?check_suite_focus=true

It was fine on the previous execution (which was on Jan 2). For other PHP versions, it still works fine.

Could it be related to the absence of PHP 7.3 for Ubuntu 20.04 in this table?
https://github.com/actions/virtual-environments/issues/1816

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Ubuntu 20.04.2
_(But there's a `ubuntu-latest` in my yml, which could be an explanation for the different results on Jan 2 and today)_

**PHP versions**

PHP 7.3 is problematic.
_(PHP 7.4 and PHP 8.0 are ok)_

**To Reproduce**

```
steps:
  - name: Setup PHP
    uses: shivammathur/setup-php@v2
    with:
      php-version: 7.3
      tools: composer:v2
      coverage: xdebug
```
_See the full yml: https://github.com/dmitry-ivanov/laravel-testing-tools/blob/master/.github/workflows/tests.yml_

**Expected behavior**

Sqlite extensions should be available by default, and tests should be green as it was on the previous execution, on Jan 2.

**Are you willing to submit a PR?**

Sorry, don't have enough knowledge for that.

**Comment by shivammathur** [comment]
It worked before as ubuntu-latest was ubuntu-18.04, GitHub has upgraded it to ubuntu-20.04, which does not have PHP 7.3 installed.
https://github.com/shivammathur/setup-php#github-hosted-runners

`setup-php` installs a minimum set of extensions by default. It is recommended to specify the extensions you need in the extensions input.

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: 7.3
    extensions: sqlite3
```
