### ISSUE TITLE
ubuntu-latest is now ubuntu-20.04

### ISSUE THREAD

**Issue by shivammathur** [shivammathur/setup-php#425]
GitHub has upgraded `ubuntu-latest` images to `ubuntu-20.04`. It was `ubuntu-18.04` before.

`ubuntu-20.04` only has PHP 7.4 and PHP 8.0 pre-installed on the images. So your workflows might fail on older versions as setup-php only installs a minimum set of extensions when PHP is not pre-installed.
https://github.com/shivammathur/setup-php#github-hosted-runners

Therefore, it is recommended to specify the extensions you need, so that the workflow can be optimised as your requirement.
https://github.com/shivammathur/setup-php#heavy_plus_sign-php-extension-support

For example, to setup PHP 7.3 with `pgsql` and `sqlite3`
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7.3'
    extensions: pgsql, sqlite3
```

If an extension is failing to setup when specified in extensions input, feel free to file a [bug report](https://github.com/shivammathur/setup-php/issues/new/choose)
