### ISSUE TITLE
Multiple switch during one job does not happen

### ISSUE THREAD

**Issue by TomasVotruba** [shivammathur/setup-php#434]
Hi,

thank your for this package that is saving me from wasting hours of Docker details learning for a slight change in my CI :+1: 

I'm trying to build a downgraded script and I need to use **2 different PHP versions in one build** (not parallel builds, no matrix).

I assumed this would work, but it does not:

```yaml
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.1
                    coverage: none

            # some operation check

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            # PHP 8 is expected here
            # but PHP 7.1 is given
```

![image](https://user-images.githubusercontent.com/924196/111206700-00023f00-85c9-11eb-91c1-830e19d7ece9.png)

How can I make it happen? Or is there silent implicit limit that uses the 1st PHP version only?

Thank you
