### ISSUE TITLE
Unable to install PHP 8.0

### ISSUE THREAD

**Issue by milewski** [shivammathur/setup-php#435]
Hello, on the latest version I'm facing this problem where the script says the right PHP version has been installed.. however in reality it is not...

![image](https://user-images.githubusercontent.com/2874967/111490305-df2b1c80-8775-11eb-91a8-67c81ccd2332.png)

these are the important bits from my action

```
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  env:
    runner: self-hosted
  with:
    php-version: '8.x'
    tools: composer
    extensions: pdo_sqlite

- name: Install dependencies
  run: composer install --ignore-platform-reqs --no-progress

- name: Test php version
  run: php --version
```
