### ISSUE TITLE
Automatically installs beta version of php-cs-fixer 3

### ISSUE THREAD

**Issue by lukasbestle** [shivammathur/setup-php#436]
**Describe the bug**

Three hours ago, [v3.0.0-beta.1 of php-cs-fixer was released](https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/tag/v3.0.0-beta.1). If no explicit version is pinned in the Setup PHP action config, Setup PHP chooses this release over the stable version.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Ubuntu Latest (20.04.2)

**PHP versions**

7.3, 7.4, 8.0

**To Reproduce**

```yaml
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php }}
          coverage: none
          tools: php-cs-fixer
```

**Expected behavior**

The latest stable version of php-cs-fixer v2 should be installed.

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by lukasbestle** [comment]
I believe this is a bug in php-cs-fixer, so I have opened an issue in their repo as well: https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5558

I think we should keep this issue open for better visibility of the problem until it is fixed by the php-cs-fixer team.

**Comment by shivammathur** [comment]
Until the releases is marked correctly, to install the last stable version, you can specify the exact version in tools input.

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: 8.0
    tools: php-cs-fixer:2.18.4
```

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/672028723/workflow
