### ISSUE TITLE
psr extension did not installed but added to php.ini

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#439]
**Describe the bug**
```
- name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl, json, psr
          tools: pecl
```

```
==> Setup Extensions
✓ mbstring Enabled
✓ intl Enabled
✓ json Enabled
✓ imagick Installed and enabled
✓ apcu Enabled
✓ yaml Enabled
✓ redis Enabled
✓ igbinary Enabled
✓ msgpack Enabled

==> Add php.ini values
✓ apc.enable_cli=on Added to php.ini
✓ session.save_path=/tmp Added to php.ini
✓ extension=psr.so Added to php.ini
✓ extension=phalcon.so Added to php.ini
```

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'psr.so' (tried: /usr/lib/php/20200930/psr.so (/usr/lib/php/20200930/psr.so: cannot open shared object file: No such file or directory), /usr/lib/php/20200930/psr.so.so (/usr/lib/php/20200930/psr.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu

**PHP versions**
8.0

**To Reproduce**
https://github.com/phalcon/cphalcon/blob/b6c97f0c926273c38c72adda86d4b392b9e4168e/.github/workflows/codecoverage.yml

**Expected behavior**
PSR extension to be installed

**Screenshots/Logs**
* https://github.com/phalcon/cphalcon/runs/2212349168?check_suite_focus=true#step:7:31
* https://github.com/phalcon/cphalcon/pull/15350
