### ISSUE TITLE
PHP Startup: Unable to load dynamic library 'gd.so'

### ISSUE THREAD

**Issue by peter-mw** [shivammathur/setup-php#440]
**Describe the bug**
PHP GD and other plugins are not available 

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [x] `v1`

**Runners**

- [ ] GitHub Hosted
- [x] Self Hosted

**Operating systems**

**PHP versions**
7.3, 7.4, 8.0

**To Reproduce**
actions.yml

```
on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@master
      with:
        coverage: pcov
        php-version: '7.4'
        extension: dom, fileinfo, mbstring, gd
    - run: |
        composer install 


```

**Expected behavior**
To work

**Screenshots/Logs**
```
| PHP Warning:  PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/lib/php/20190902/gd.so (libX11.so.6: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/gd.so.so (/usr/lib/php/20190902/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
| PHP Warning:  PHP Startup: Unable to load dynamic library 'snmp.so' (tried: /usr/lib/php/20190902/snmp.so (libnetsnmp.so.35: cannot open shared object file: No such file or directory), /usr/lib/php/20190902/snmp.so.so (/usr/lib/php/20190902/snmp.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

```

**Comment by shivammathur** [comment]
@peter-mw 
Correct key is `extensions`, not `extension`.
Also, please use `v2` instead of `master`.

```diff
-    - uses: shivammathur/setup-php@master
+    - uses: shivammathur/setup-php@v2
       with:
         coverage: pcov
         php-version: '7.4'
-        extension: dom, fileinfo, mbstring, gd
+        extensions: dom, fileinfo, mbstring, gd
```

**Comment by peter-mw** [comment]
Hello, still does not work 

```
on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        coverage: pcov
        php-version: '7.4'
        extensions: dom, fileinfo, mbstring, gd
    - run: |
        composer install

```

Im using the local runner

![image](https://user-images.githubusercontent.com/5698247/113308186-985d2b00-930e-11eb-86c4-912d09bc958f.png)

**Comment by shivammathur** [comment]
@peter-mw In that case, please specify `runner: self-hosted`
https://github.com/shivammathur/setup-php#self-hosted-setup

**Comment by peter-mw** [comment]
@shivammathur in this case i get error

`  Skipping unsupported platform 'self-hosted'`

here is my actions.yml 

```

jobs:
  run:
    runs-on: self-hosted
    strategy:
      matrix:        
        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0']
    name: PHP ${{ matrix.php-versions }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
      env:
        runner: self-hosted # Specify the runner.


```

**Comment by shivammathur** [comment]
ok, local as in `nektos/act`, I though you were using self-hosted runners.
Sorry for the confusion.

`setup-php` does not work on default act images.
We maintain `shivammathur/node` docker images for this
https://github.com/shivammathur/node-docker

For example, to use `ubuntu-20.04` on act with setup-php, run
```bash
act -P ubuntu-20.04=shivammathur/node:focal
```
https://github.com/shivammathur/setup-php#local-testing-setup

**Comment by peter-mw** [comment]
Same error. 

Maybe the error is related to the `act` runner. What other options besides `act` i have to run this on local machine ?

**Comment by shivammathur** [comment]
@peter-mw  I cannot reproduce this error on my end

Please provide the complete workflow and complete yaml workflow.

My Test Workflow
```yml
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        coverage: pcov
        php-version: '7.4'
        extensions: dom, fileinfo, mbstring, gd
    - run: |
        php -v
        php -m
```


Act Output
```bash
~# act --version
act version 0.2.21
~# act -P ubuntu-latest=shivammathur/node:focal -j main
[test.yml/main] 🚀  Start image=shivammathur/node:focal
[test.yml/main]   🐳  docker run image=shivammathur/node:focal platform=linux/amd64 entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[test.yml/main]   🐳  docker cp src=/tmp/test/. dst=/tmp/test
[test.yml/main] ⭐  Run actions/checkout@v2
[test.yml/main]   ✅  Success - actions/checkout@v2
[test.yml/main] ⭐  Run shivammathur/setup-php@v2
[test.yml/main]   ☁  git clone 'https://github.com/shivammathur/setup-php' # ref=v2
[test.yml/main]   🐳  docker cp src=/root/.cache/act/shivammathur-setup-php@v2 dst=/actions/
| [command]/usr/bin/bash /opt/hostedtoolcache/linux.sh 7.4 /actions/shivammathur-setup-php@v2/dist
|
| ==> Setup PHP
| ✓ PHP Switched to PHP 7.4.15
|
| ==> Setup Tools
| ✓ composer Added composer 2.0.12
|
| ==> Setup Extensions
| ✓ dom Enabled
| ✓ fileinfo Enabled
| ✓ mbstring Enabled
| ✓ gd Installed and enabled
|
| ==> Setup Coverage
| ✓ pcov.enabled=1 Added to php.ini
| ✓ coverage: pcov PCOV enabled as coverage driver
|
| ==> Support this project
| ✓ setup-php https://setup-php.com/support
[test.yml/main]   ✅  Success - shivammathur/setup-php@v2
[test.yml/main] ⭐  Run php -v
php -m
| PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:38) ( NTS )
| Copyright (c) The PHP Group
| Zend Engine v3.4.0, Copyright (c) Zend Technologies
|     with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies
| [PHP Modules]
| calendar
| Core
| ctype
| curl
| date
| dom
| exif
| FFI
| fileinfo
| filter
| ftp
| gd
| gettext
| hash
| iconv
| intl
| json
| libxml
| mbstring
| mysqli
| mysqlnd
| openssl
| pcntl
| pcov
| pcre
| PDO
| pdo_mysql
| pdo_pgsql
| pgsql
| Phar
| posix
| readline
| Reflection
| session
| shmop
| SimpleXML
| sockets
| sodium
| SPL
| standard
| sysvmsg
| sysvsem
| sysvshm
| tokenizer
| xml
| xmlreader
| xmlwriter
| xsl
| Zend OPcache
| zip
| zlib
|
| [Zend Modules]
| Zend OPcache
|
[test.yml/main]   ✅  Success - php -v
```
