### ISSUE TITLE
Installing PHP 7.3 fails on Linux

### ISSUE THREAD

**Issue by bohdan-sokulskyi-n-ix** [shivammathur/setup-php#454]
**Describe the bug**
GH action fails with error:
```
==> Setup PHP
✗ PHP Could not setup PHP 7.3
Error: The process '/usr/bin/bash' failed with exit code 1
```

* Switching to Ubuntu 18.04 doesn't help
* Switching to PHP 7.4 helps (but we need 7.3, so for us it's not an option)
* Investigation shows that the problem is in this commit: https://github.com/shivammathur/setup-php/commit/ef477a1dd71038ae272fe0c68d206727da409264 (as the previous one works good)

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 20.04 (the same result for 18.04)

**PHP versions**
 - 7.3

**To Reproduce**

```
name: Debugging
on:
  push:
jobs:
  phpunit-tests:
    name: Debugging (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-20.04
    container: shivammathur/node:focal-slim
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.3']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, zip, json, pdo, imagick, bcmath, redis, apcu, gd, mysql
          tools: composer:v1
        env:
          update: true
```

**Expected behavior**
PHP 7.3 is being installed :)
