### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by cnizzardini** [shivammathur/setup-php#458]
**Describe the bug**
See https://github.com/shivammathur/setup-php/wiki/Add-extension-from-source `mongodb-mongodb/mongo-php-driver@v1.9` should be `mongodb/mongo-php-driver@v1.9`: 

```
- name: Setup PHP with mongodb from source
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7.4'  
    extensions: mongodb/mongo-php-driver@v1.9
```
