### ISSUE TITLE
Setting up PHP 8.1 on ubuntu-latest somehow tries to use redis extension

### ISSUE THREAD

**Issue by localheinz** [shivammathur/setup-php#461]
**Describe the bug**

In [`sebastianbergmann/phpunit`](https://github.com/sebastianbergmann/phpunit), we currently run tests against PHP 8.1.

Our GitHub Actions job definition looks like this (also see [`ci.yaml`](https://github.com/sebastianbergmann/phpunit/blob/564e78a6c088916467cd4bc0af2e1bb9da9b1a0c/.github/workflows/ci.yml#L55-L140)):

```yaml
  tests:
    name: Tests

    runs-on: ${{ matrix.os }}

    env:
      PHP_EXTENSIONS: dom, json, libxml, mbstring, pdo_sqlite, soap, xml, xmlwriter
      PHP_INI_VALUES: assert.exception=1, memory_limit=-1, zend.assertions=1

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php-version:
          - "8.0"
          - "8.1"

        compiler:
          - default

        dependencies:
          - lowest
          - highest

        include:
          - os: ubuntu-latest
            php-version: "8.0"
            compiler: jit
            dependencies: highest

          - os: ubuntu-latest
            php-version: "8.1"
            compiler: jit
            dependencies: highest

    steps:
      - name: Configure git to avoid issues with line endings
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v2

      - name: Override PHP ini values for JIT compiler
        if: matrix.compiler == 'jit'
        run: echo "PHP_INI_VALUES::assert.exception=1, memory_limit=-1, zend.assertions=1, opcache.enable=1, opcache.enable_cli=1, opcache.optimization_level=-1, opcache.jit=1255, opcache.jit_buffer_size=32M" >> $GITHUB_ENV

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          ini-values: ${{ env.PHP_INI_VALUES }}

      - name: Determine composer cache directory on Linux
        if: matrix.os == 'ubuntu-latest'
        run: echo "COMPOSER_CACHE_DIR=$(./tools/composer config cache-dir)" >> $GITHUB_ENV

      - name: Determine composer cache directory on Windows
        if: matrix.os == 'windows-latest'
        run: ECHO "COMPOSER_CACHE_DIR=~\AppData\Local\Composer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Cache dependencies installed with composer
        uses: actions/cache@v2
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-

      - name: Install lowest dependencies with composer
        if: matrix.dependencies == 'lowest'
        run: php ./tools/composer update --no-ansi --no-interaction --no-progress --prefer-lowest

      - name: Install highest dependencies with composer
        if: matrix.dependencies == 'highest'
        run: php ./tools/composer update --no-ansi --no-interaction --no-progress

      - name: Run sanity check
        run: bash ./build/scripts/sanity-check

      - name: Run tests with phpunit
        run: php ./phpunit
```

With this configuration, jobs running on `ubuntu-latest` with PHP 8.1 emit the following warning

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis' (tried: /usr/local/php/8.1/lib/php/extensions/no-debug-non-zts-20201009/redis (/usr/local/php/8.1/lib/php/extensions/no-debug-non-zts-20201009/redis: cannot open shared object file: No such file or directory), /usr/local/php/8.1/lib/php/extensions/no-debug-non-zts-20201009/redis.so (/usr/local/php/8.1/lib/php/extensions/no-debug-non-zts-20201009/redis.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

We do not understand why `redis` is causing problems here, because our job configuration does not indicate that we want `redis` to be installed.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
 - [x] `ubuntu-latest`

**PHP versions**

- [x] `8.1`

**To Reproduce**

See [`ci.yaml`](https://github.com/sebastianbergmann/phpunit/blob/564e78a6c088916467cd4bc0af2e1bb9da9b1a0c/.github/workflows/ci.yml#L55-L140).

**Expected behavior**

PHP 8.1 starts up without emitting a warning related to `redis`.

**Screenshots/Logs**

See the corresponding [run](https://github.com/sebastianbergmann/phpunit/runs/2653591589?check_suite_focus=true):

```console
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis' (tried: /usr/local/php/8.1/lib/php/extensions/no-debug-non-zts-20201009/redis (/usr/local/php/8.1/lib/php/extensions/no-debug-non-zts-20201009/redis: cannot open shared object file: No such file or directory), /usr/local/php/8.1/lib/php/extensions/no-debug-non-zts-20201009/redis.so (/usr/local/php/8.1/lib/php/extensions/no-debug-non-zts-20201009/redis.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Additional context**

n/a

**Are you willing to submit a PR?**

Absolutely!
