### ISSUE TITLE
composer v1 vs. v2 default

### ISSUE THREAD

**Issue by staabm** [shivammathur/setup-php#466]
**Describe the bug**

I am wondering why setup-php sometimes sets up composer v2 and somtimes v1 as a default when its not explicitly defined.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

ubuntu-latest

**PHP versions**

7.4

**To Reproduce**

my phpstan.yml:
```
# DONT EDIT THIS FILE OUTSIDE OF complex-gmbh/php-automation-templates
# changes will be one-way synced from the automation repos
#
# REQUIREMENTS
# - composer bin phpstan require phpstan/phpstan
# - composer-script 'phpstan-baseline'
# - composer-script 'phpstan-pull-request'

name: Static analysis

on:
  pull_request:
  pull_request_target:
  repository_dispatch:
    types: [ phpstan-baseline-command ] # triggered by /phpstan-baseline PR comment

jobs:

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    if: |
      (
        github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]' ||
        github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]'
      )

    steps:
      - name: Add action run link to trigger comment
        if: "github.event_name == 'repository_dispatch'"
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PHP_GH_ACTION }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            ```
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ```

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PHP_GH_ACTION }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
          tools: cs2pr

      - name: disable post-install-cmd in composer.json, which would trigger grunt etc.
        run: composer config scripts.post-install-cmd --unset

      - uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-dist --no-progress --no-suggest"

      - run: composer bin phpstan install --no-progress

      - run: composer phpstan-baseline # generate baseline
        if: "github.event_name == 'repository_dispatch'"

      - name: Commit changed files
        if: "github.event_name == 'repository_dispatch'"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply phpstan-baseline changes
          branch: ${{ github.head_ref }}
          file_pattern: '*.neon' # make sure we don't commit our locally changed composer.json

      - run: composer phpstan-pull-request
        if: "github.event_name != 'repository_dispatch'"
```

(both in private builds)

running this workflow on branch A of my repo leads to composer v1

![grafik](https://user-images.githubusercontent.com/120441/121659283-70264100-caa2-11eb-80c8-16e920df2ab6.png)

but sometimes in the very same repo on a different branch it uses composer v2

![grafik](https://user-images.githubusercontent.com/120441/121659341-7ddbc680-caa2-11eb-9d45-1d0151455f40.png)

**Expected behavior**

always the same version should be used, when non is explicitly defined

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**
