### ISSUE TITLE
Could not install extension from source.

### ISSUE THREAD

**Issue by razonyang** [shivammathur/setup-php#468]
**Describe the bug**

Hi, I follow the guide [Add extension from source](https://github.com/shivammathur/setup-php/wiki/Add-extension-from-source) to add an extension, but it doesn't work.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

`ubuntu-latest`

**PHP versions**

`8.0`

**To Reproduce**

```yml
name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install OpenCC
      run: sudo apt install libopencc-dev -y
    
    - name: Setup PHP with protobuf from source
      uses: shivammathur/setup-php@v2
      with:
        extensions: protobuf-protocolbuffers/protobuf@master
      env:
        PROTOBUF_PATH: php/ext/google/protobuf
    
    - name: Setup PHP with opencc4php from source
      uses: shivammathur/setup-php@v2
      with:
        extensions: nauxliu/opencc4php@master
      env:
        OPENCC_LIBS: libopencc-dev
```

**Expected behavior**

**Screenshots/Logs**

```text
Run shivammathur/setup-php@v2
/usr/bin/bash /opt/hostedtoolcache/linux.sh 8.0 /home/runner/work/_actions/shivammathur/setup-php/v2/dist

==> Setup PHP
✓ PHP Found PHP 8.0.7

==> Setup Tools
✓ composer Added composer 2.1.3

==> Setup Extensions
✗ nauxliu/opencc4php@master Could not install nauxliu/opencc4php@master on PHP 8.0.7

==> Support this project
✓ setup-php https://setup-php.com/support
```

**Additional context**

Extension repository: https://github.com/nauxliu/opencc4php

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
@razonyang 

- For `opencc`, you have to specify the extension name before the repo as the input format is `extension-repository@git_ref`
- For `protobuf` you have to specify the extension path in the `protobuf` repository i.e. `php/ext/google/protobuf`.
- Also you can set up both in a single `setup-php` step.

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    extensions: opencc-nauxliu/opencc4php@master, protobuf-protocolbuffers/protobuf@master
  env:
    OPENCC_LIBS: libopencc-dev
    PROTOBUF_PATH: php/ext/google/protobuf
```
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/954110498/workflow
