### ISSUE TITLE
Could not install imagick on PHP 7.4.21

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#471]
**Describe the bug**

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
MacOS

**PHP versions**
7.4

**To Reproduce**
```
  build-and-test-macos:
    # To prevent build a particular commit use
    #     git commit -m "......... [ci skip]"
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    needs: generate
    runs-on: ${{ matrix.operating-system }}
    env:
      extensions: mbstring, intl, json, yaml, apcu, imagick, gd, gettext, igbinary, redis
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      ext_cache_key: v5.0.0-alpha.2-macOS
    strategy:
      fail-fast: false
      matrix:
        operating-system: [macos-latest]
        php-versions: ['7.4', '8.0']

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.ext_cache_key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

#      - name: Install Requirements for Imagick
#        run: |
#          export HOMEBREW_MAKE_JOBS="-j$(getconf _NPROCESSORS_ONLN)"
#          brew install pkg-config imagemagick@7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: apc.enable_cli=on, session.save_path=/tmp
          extensions: ${{ env.extensions }}
```

**Expected behavior**
Installed imagick on PHP 7.4

**Screenshots/Logs**
https://github.com/phalcon/cphalcon/pull/15561/checks?check_run_id=2950380446#step:5:25

**Additional context**

**Are you willing to submit a PR?**
