### ISSUE TITLE
composer-require-checker: /usr/bin/env: ‘php\r’: No such file or directory

### ISSUE THREAD

**Issue by Slamdunk** [shivammathur/setup-php#473]
**Describe the bug**

Now:
```console
Run composer-require-checker check --ansi --config-file=$(realpath .require-checker.json)
  composer-require-checker check --ansi --config-file=$(realpath .require-checker.json)
  shell: /usr/bin/bash -e {0}
/usr/bin/env: ‘php\r’: No such file or directory
Error: Process completed with exit code 127.
```

4 days ago:
```console
Run composer-require-checker check --ansi --config-file=$(realpath .require-checker.json)
  composer-require-checker check --ansi --config-file=$(realpath .require-checker.json)
  shell: /usr/bin/bash -e {0}
ComposerRequireChecker 3.2.0@cd6c6b91ee3c065e60a35ca1a67becb0ae86dbb7
There were no unknown symbols found.
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`ubuntu-latest`

```console
Current runner version: '2.278.0'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210628.1
```

**PHP versions**
```console
Run shivammathur/setup-php@v2
  with:
    coverage: none
    php-version: 8.0
    tools: composer-normalize, composer-require-checker
/usr/bin/bash /opt/hostedtoolcache/linux.sh 8.0 /home/runner/work/_actions/shivammathur/setup-php/v2/dist

==> Setup PHP
✓ PHP Found PHP 8.0.7

==> Setup Tools
✓ composer Added composer 2.1.3
✓ composer-normalize Added composer-normalize 
✓ composer-require-checker Added composer-require-checker 

==> Setup Coverage
✓ none Disabled Xdebug and PCOV
```

**To Reproduce**
```yml
jobs:
  composer-json-lint:
    name: "Lint composer.json"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.0"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: composer-normalize, composer-require-checker

      - name: "Get composer cache directory"
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: composer-json-lint-${{ runner.os }}-php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json', '**/composer.lock') }}
          restore-keys: composer-json-lint-${{ runner.os }}-php-${{ matrix.php-version }}-composer-

      - name: "Validate composer.json"
        run: "composer validate --ansi --strict --no-check-all --no-check-publish"

      - name: "Normalize composer.json"
        run: "composer-normalize --ansi --dry-run"

      - name: "Install dependencies"
        run: "composer install --ansi --classmap-authoritative"

      - name: "Check composer.json explicit dependencies"
        run: "composer-require-checker check --ansi --config-file=$(realpath .require-checker.json)"
```

**Additional context**
Nothing changed in my code within the last 4 days.
It's also weird because it's been a month since the last commit con https://github.com/maglnet/ComposerRequireChecker
