### ISSUE TITLE
Support specific PHP version

### ISSUE THREAD

**Issue by iBotPeaches** [shivammathur/setup-php#475]
**Describe the feature**
PHP 7.4.21 came out and it has something that led to some crashes in our codebase. TLDR - "ini_set" a memory limit lower than what you have in use is no longer allowed. https://github.com/php/php-src/pull/7040. I'd much rather file a ticket on our team and fix this the right way then upgrade, then panic with our build suite failing with a new minor release.

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
```
Run shivammathur/setup-php@v2
  with:
    php-version: 7.4.20

==> Setup PHP
✓ PHP Switched to PHP 7.4.21
```

Why isn't that switching/checking out 7.4.20? Does it only support the nomenclature of like 7.4|7.3?

**Describe alternatives**
I have not figured out one.

**Are you willing to submit a PR?**
Not sure I understand enough of the codebase to do so :(

**Comment by shivammathur** [comment]
Duplicate https://github.com/shivammathur/setup-php/issues/456

I'm sorry, this is not supported.
This would require maintaining builds of each patch release for all the supported versions and operating systems, which would be a huge task and with the current funding, would be out of scope for this project.

**Comment by shivammathur** [comment]
For running `7.4.20` till you have a fix, you can use the old build of docker image we maintain for setup-php. It has `PHP 7.4.20`.
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1035163281/workflow
```yml
jobs:
  test:
    runs-on: ubuntu-latest
    container: setupphp/node@sha256:f0bae66978e4c4091aae10425f0fa58e537a9066264c05237cde23560466038d
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
```
