### ISSUE TITLE
support running inline php scripts

### ISSUE THREAD

**Issue by staabm** [shivammathur/setup-php#482]
**Describe the feature**
writing bash scripts etc. within github action workflows is a real pain - especially if you are used to the php language.

additionally the feedback loop getsss soo long when try and error debugging github action workflows.

I would love if there would be something possible like:

```yml
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          run-script: |
            echo "hello world";
            var_dump(file_get_contents("my/path.txt"));

            system("my-bin-script", $exitCode);
            // ...
```

so writing inline php within the workflow.

that way we could easily develop advanced logic without the need for advanced bash fu.

**Version**
- [ ] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

the long feedback look of github actions

**Describe alternatives**
in our use-case we cannot move the logic into a separat php file and run it with `php -f file.php`, since we need a self-containing workflow file (this is easier to distribute and keep in sync between github projects)

**Additional context**

n/a

**Are you willing to submit a PR?**

I don't think I can implement it myself

**Comment by shivammathur** [comment]
@staabm 
It is possible to run inline php code in the workflow. You have to specify the shell for the step as `php {0}`.

It saves whatever is in the run property to a file and executes using the default shell for the OS. For Linux, the default shell would be `sh` or `bash`,  which you can override to be `php`. `{0}` reference the file saved.

Relevant ADR: https://github.com/actions/runner/blob/main/docs/adrs/0277-run-action-shell-options.md
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1105361404/workflow

```yml
- name: Setup PHP 
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.0'

- name: Run inline PHP code
  shell: php {0}
  run: |
     <?php
     $welcome = "Hello, world";
     echo $welcome;
```
