### ISSUE TITLE
Action freezes for 3 minutes at installing extensions and then fails

### ISSUE THREAD

**Issue by faizanakram99** [shivammathur/setup-php#484]
**Describe the bug**
Action freezes for 3 minutes at installing extensions and then fails

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
8.0

**To Reproduce**
```yaml
- name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          tools: composer:v2.1.3, cs2pr:v1.4.0
          extensions: curl, mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, bcmath, iconv, gd, intl, mysqli, pdo_mysql, zip, redis, apcu, pdo_sqlsrv, sqlsrv
          coverage: none
        env:
          fail-fast: true
```

**Expected behavior**
It should install PHP and extensions

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/10880992/129353281-ee490a9f-c441-4c7f-90ed-f52e0fbe8a13.png)

**Additional context**
This workflow has been pretty much working since November 2020. It stopped today all of sudden.

**Are you willing to submit a PR?**
