### ISSUE TITLE
Unable to install gmp or bcmath extensions

### ISSUE THREAD

**Issue by oschwald** [shivammathur/setup-php#492]
**Describe the bug**

At some point in the last three months, `bcmath` and `gmp` stopped working in our workflow with no change to the workflow itself. We were installing PHP manually with `spc`, but the same things happens when switching back to `setup-php`. See the [last successful run](https://github.com/maxmind/MaxMind-DB-Reader-php/actions/runs/907209846) vs. a [current run](https://github.com/maxmind/MaxMind-DB-Reader-php/runs/3600859199?check_suite_focus=true).

As you can see, we are getting errors like "bcmath Could not install bcmath on PHP 7.3.30" with no further information.

![image](https://user-images.githubusercontent.com/278835/133292652-d2ff81a2-c5a6-4fa6-8178-eafbf5863d27.png)

**Version**
- [X] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

`ubuntu-latest`

**PHP versions**

7.2 - 8.0. 

**To Reproduce**

```
    strategy:
      matrix:
        arch: ["amd64", "i386"]
        operating-system: [ubuntu-latest]
        php-versions: ['7.2', '7.3', '7.4', '8.0']
        php-extensions: ['bcmath', 'gmp']
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: "mbstring, intl, ${{ matrix.php-extensions }}"
          tools: "composer, phpize"
          coverage: xdebug
```

**Expected behavior**

`bcmath` and `gmp` are installed when appropriate.

**Screenshots/Logs**

See above.

**Additional context**

**Are you willing to submit a PR?**

If I had any idea what the bug was, perhaps.
