### ISSUE TITLE
cURL 60 Error running composer install using windows-2016 and PHP 8.0

### ISSUE THREAD

**Issue by ajrice6713** [shivammathur/setup-php#511]
**Describe the bug**
On Windows-2016 and PHP 8.0 - seeing a cURL 60 error when running `composer install` 

```
Loading composer repositories with package information
Error: curl error 60 while downloading https://repo.packagist.org/packages.json: SSL certificate problem: unable to get local issuer certificate

                                                                                                                       
  [Composer\Downloader\TransportException]                                                                             
  curl error 60 while downloading https://repo.packagist.org/packages.json: SSL certificate problem: unable to get lo  
  cal issuer certificate          
```                                                                             

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
windows-2016, windows-2019, ubuntu-18.04, ubuntu-20.04

**PHP versions**
7.4, 8.0

**To Reproduce**
```    
name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, windows-2019, ubuntu-18.04, ubuntu-20.04]
        php-version: [7.4, 8.0]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: ${{ matrix.php-version }}

    - name: Install Packages
      run: composer install
```

**Expected behavior**
PHP & Composer Installed successfully with no cert issues 

**Screenshots/Logs**
https://github.com/Bandwidth/php-sdk/runs/3786499486?check_suite_focus=true

**Additional context**
Only happening on Windows 2016 and PHP 8.0 - not sure if this is an issue with the PHP setup or the actions runner itself - but any guidance would be appreciated. 

**Are you willing to submit a PR?**
