### ISSUE TITLE
ext-snmp for PHP 8.1

### ISSUE THREAD

**Issue by simPod** [shivammathur/setup-php#520]
**Describe the feature**

```yaml
-   uses: shivammathur/setup-php@v2
    with:
        extensions: snmp
        php-version: 8.1
```
ext-snmp is not installed.

> ✗ snmp Could not install snmp on PHP 8.1.0RC5-dev

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Are you willing to submit a PR?**

What can I do?
