### ISSUE TITLE
/tmp/install.sh: line 1: Failed: command not found – GitHub rate limit?

### ISSUE THREAD

**Issue by joppuyo** [shivammathur/setup-php#521]
**Describe the bug**
I'm getting this error intermittently when running GitHub actions in parallel:

It doesn't seem to be tied to any specific version of PHP.

```
==> Setup PHP
/tmp/install.sh: line 1: Failed: command not found
✗ PHP Could not setup PHP 7.1
Error: The process '/usr/bin/bash' failed with exit code 1
```

Maybe there's some sort of rate limit that prevents downloading this file?

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-20.04

**PHP versions**
Various

**To Reproduce**

```
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        acf_version:
          - 5.10.2
          - 5.10.1
          - 5.9.9
          - 5.9.8
          - 5.9.7
          - 5.9.6
          - 5.9.5
          - 5.9.4
          - 5.9.3
          - 5.9.2
          - 5.9.1
          - 5.9.0
          - 5.8.13
        wp_docker_tag:
          - 5.1-php7.1-apache
          - 5.2-php7.1-apache
          - 5.3-php7.1-apache
          - 5.4-php7.2-apache
          - 5.5-php7.2-apache
          - 5.6-php7.2-apache
          - 5.7-php7.3-apache
          - 5.8-php7.3-apache
          - 5.8-php7.4-apache
        include:
          - wp_docker_tag: 5.1-php7.1-apache
            xdebug_version: xdebug-2.7.2
            php_version: '7.1'
          - wp_docker_tag: 5.2-php7.1-apache
            xdebug_version: xdebug-2.7.2
            php_version: '7.1'
          - wp_docker_tag: 5.3-php7.1-apache
            xdebug_version: xdebug-2.7.2
            php_version: '7.1'
          - wp_docker_tag: 5.4-php7.2-apache
            xdebug_version: xdebug-2.7.2
            php_version: '7.2'
          - wp_docker_tag: 5.5-php7.2-apache
            xdebug_version: xdebug-2.7.2
            php_version: '7.2'
          - wp_docker_tag: 5.6-php7.2-apache
            xdebug_version: xdebug-2.7.2
            php_version: '7.2'
          - wp_docker_tag: 5.7-php7.3-apache
            xdebug_version: xdebug-2.7.2
            php_version: '7.3'
          - wp_docker_tag: 5.8-php7.3-apache
            xdebug_version: xdebug-2.7.2
            php_version: '7.3'
          - wp_docker_tag: 5.8-php7.4-apache
            xdebug_version: xdebug-3.0.4
            php_version: '7.4'
      fail-fast: false
    env:
      ACF_VERSION: ${{ matrix.acf_version }}
      WP_DOCKER_TAG: ${{ matrix.wp_docker_tag }}
      XDEBUG_VERSION: ${{ matrix.xdebug_version }}
      PHP_VERSION: ${{ matrix.php_version }}
    steps:
      - uses: actions/checkout@v1

      - name: Install PHP
        uses: shivammathur/setup-php@verbose
        with:
          php-version: ${{ matrix.php_version }}
          extensions: zip
```

**Expected behavior**
It should work every time and not fail intermittently
