### ISSUE TITLE
How to get outputs from inline PHP script?

### ISSUE THREAD

**Issue by franck-paul** [shivammathur/setup-php#523]
**Describe the bug**

I'm unable to get the output of an inline PHP script with ${{steps.[step-id].outputs}}

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

ubuntu-latest

**PHP versions**

PHP 8

**To Reproduce**

Here is my workflow .yml file:

```yml
# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "dcstore"
  dcstore:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Setup PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Run PHP code
    - name: Run PHP code
      id: getversion
      shell: php {0}
      run: |
        <?php
        $df = file_get_contents('./_define.php');
        $version = '';
        if (preg_match('/registerModule\((.*?),(.*?),(.*?),(.*?)\'(.*?)\'(.*?)(,.*)\)/s',$df,$matches)) {
          if (isset($matches[5])) {
            $version = $matches[5];
          }
        }
        echo $version;

    # Cope with returned version
    - name: Log output of the script
      run: echo "${{steps.getversion.outputs}}"
````

**Expected behavior**

The PHP script correctly output the expecting string ("1.16"), but the next step does not echo anything.

Is there anything I'm doing wrong?

**Comment by franck-paul** [comment]
Sorry for this issue, I was misreading the documentation!

Here is a working workflow:

```yaml
# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "dcstore"
  dcstore:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Setup PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Run PHP code
    - name: Run PHP code
      id: getversion
      shell: php {0}
      run: |
        <?php
        $df = file_get_contents('./_define.php');
        $version = '';
        if (preg_match('/registerModule\((.*?),(.*?),(.*?),(.*?)\'(.*?)\'(.*?)(,.*)\)/s',$df,$matches)) {
          if (isset($matches[5])) {
            $version = $matches[5];
          }
        }
        echo "::set-output name=module_version::$version";

    # Cope with returned version
    - name: Log output of the script
      run: echo "${{steps.getversion.outputs.module_version}}"
```
