### ISSUE TITLE
Show the filename from the output of cs2pr

### ISSUE THREAD

**Issue by CLL-GTA** [shivammathur/setup-php#524]
**Describe the feature**
I have setup the action with `cs2pr` and I am using `php-cs-fixer`

```
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: cs2pr

      - name: Install Composer Dependencies
        run: composer install -n --prefer-dist
        working-directory: tools/php-cs-fixer

      - name: Check code style
        run: composer php-cs-fixer -- --dry-run --using-cache=no --format=checkstyle | cs2pr
```

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
If `php-cs-fixer` finds an issue i have to hunt down the culprit file by running it on the codebase. `php-cs-fixer` includes the filename in its output and `cs2pr` includes it too. It would be useful if the filename was reported on the action's output so I can quickly fix it.

**Describe alternatives**

**Additional context**
The output from `php-cs-fixer` is 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle>
  <file name="CareLineLive/app/Http/Controllers/Exports/CarersExportController.php">
    <error severity="warning" source="PHP-CS-Fixer.no_unused_imports" message="Found violation(s) of type: no_unused_imports"/>
  </file>
</checkstyle>
```

and `cs2pr` produces

```
:warning file=CareLineLive/app/Http/Controllers/Exports/CarersExportController.php::Found violation(s) of type: no_unused_imports.
```

But in the action I only see the warning and not the file

![140112365-4a910add-3155-4ccd-a425-c381c0cc4219](https://user-images.githubusercontent.com/92724269/140384405-5985dcdd-7e77-49fe-b17f-ef2fe7db66f3.png)

**Are you willing to submit a PR?**
I would, but I don't have a clue where to start with a GH Action.

For reference, I first raised an [issue](https://github.com/staabm/annotate-pull-request-from-checkstyle/issues/84#issue-1043846325) on `staabm/annotate-pull-request-from-checkstyle`  but I now think the problem may be with the action.
