### ISSUE TITLE
Could not install rdkafka on PHP 8.0

### ISSUE THREAD

**Issue by Nikkoz** [shivammathur/setup-php#525]
**Describe the bug**
```yaml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: 8.0
    extensions: rdkafka
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
8.0

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
On Ubuntu there is no `php-rdkafka` package, so to install it you will need to install it using source. It needs the `librdkafka` library. You can use the [build from source API](https://github.com/shivammathur/setup-php/wiki/Add-extension-from-source) of setup-php which allows you to specify libraries.

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  env:
    RDKAFKA_LIBS: librdkafka-dev
  with:
    php-version: '8.0'
    extensions: rdkafka-arnaud-lb/php-rdkafka@5.0.0
```
Here is a test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1435310764/workflow
