### ISSUE TITLE
PhpManager exits succesffuly when it fails to install an extension

### ISSUE THREAD

**Issue by azjezz** [shivammathur/setup-php#526]
**Describe the bug**

when PhpManager fails to install an extension on Windows, it returns an exit code of 0, resulting on the action to continue running, even tho dependencies were not installed.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Windows

**PHP versions**

8.1

**To Reproduce**

```yml
name: "examples"

on:
  pull_request: ~
  push: ~

jobs:
  examples:
    name: "examples"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.1"
        operating-system:
          - "windows-latest"
        extensions:
          - bcmath, mbstring, intl, sodium, json, uv
          - bcmath, mbstring, intl, sodium, json, ev
          - bcmath, mbstring, intl, sodium, json, event
          - bcmath, mbstring, intl, sodium, json

    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: "${{ matrix.extensions }}"

      - name: "dump php modules"
        run: php -m

```

**Expected behavior**

For setup-php to fail if an extension wasn't installed.

**Screenshots/Logs**

see: https://github.com/azjezz/psl/runs/4171233110?check_suite_focus=true

**Additional context**

**Are you willing to submit a PR?**

I'm not much familiar with TS and GA, so i would leave this for someone to pick up :)

**Comment by shivammathur** [comment]
@azjezz
Yes, when extensions or tools fail to install, setup-php does not exit. This was a design choice to simplify cross-platform workflows as some extensions and tools only support a particular OS.

To change this, set `fail-fast` environment variable to `true`.
```yml
- name: "installing PHP"
  uses: "shivammathur/setup-php@v2"
  with:
    php-version: "${{ matrix.php-version }}"
    ini-values: memory_limit=-1
    tools: composer:v2, cs2pr
    extensions: "${{ matrix.extensions }}"
  env:
    fail-fast: true
```
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1446475729/workflow
Docs (last point in extension support): https://github.com/shivammathur/setup-php#heavy_plus_sign-php-extension-support
