### ISSUE TITLE
[Question] How to disable XDebug?

### ISSUE THREAD

**Issue by mimmi20** [shivammathur/setup-php#53]
I want to run some tests without XDebug, because PHP is faster then. How do I disable/uninstall XDebug?

**Comment by shivammathur** [comment]
@mimmi20 
I will add option to do that in the action.

**Comment by shivammathur** [comment]
@mimmi20 
Now you can specify `coverage: none` and it will disabled Xdebug.

For example
```yml
uses: shivammathur/setup-php@master
with:
  php-version: 7.3
  coverage: none
```

**Comment by mimmi20** [comment]
Thanks

**Comment by Nyholm** [comment]
How can I disable xdebug but keep pcov enabled?

**Comment by shivammathur** [comment]
@Nyholm specifying `coverage: pcov` does that.
```yml
uses: shivammathur/setup-php@master
with:
  php-version: 7.3
  coverage: pcov
```
