### ISSUE TITLE
Problems running multiple PHP versions on the same self-hosted runner

### ISSUE THREAD

**Issue by milewski** [shivammathur/setup-php#530]
**Describe the bug**

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [x] Self Hosted

Hi, I'm facing this issue where I have multiple branches, and each branch is running with a different version of PHP where branch A runs on PHP 8.0 and branch B on 8.1, I only have 1 worker running at a time (no concurrency)... But when I push code on each branch the PHP versions get switched up and the code runs with the wrong PHP version...

![image](https://user-images.githubusercontent.com/2874967/142372987-15fef978-3759-49a6-8136-7e10e44ff188.png)

```yml
jobs:
  phpunit:
    runs-on: self-hosted
    name: PHPUnit
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        env:
          runner: self-hosted
        with:
          php-version: 8.1
          extensions: sqlite3, gd
          tools: composer

```
