### ISSUE TITLE
Tools must be added after extensions

### ISSUE THREAD

**Issue by PierreRambaud** [shivammathur/setup-php#532]
**Describe the bug**

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**
PHP: 7.4.26, 8.0.13

**To Reproduce**
```yml
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, simplexml, pdo, mysql
```

**Expected behavior**
Tools sometimes require extensions to be properly installed.

**Screenshots/Logs**
https://github.com/PrestaShop/PrestaShop/runs/4266025190?check_suite_focus=true#step:6:147
