### ISSUE TITLE
Setting up OCI8 and PDO_oci extensions fails with PHP 8.1

### ISSUE THREAD

**Issue by derrabus** [shivammathur/setup-php#534]
**Describe the bug**

On the doctrine/dbal repository, we setup jobs with different database drivers. This does not work at the moment on PHP 8.1 with Oracle drivers. The same job on PHP 7.4 works fine.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

`ubuntu-20.04`

**PHP versions**

8.1

**To Reproduce**

```YAML
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "oci8"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
```

```YAML
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "pdo_oci"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
```

Full workflow: https://github.com/doctrine/dbal/blob/3.1.x/.github/workflows/continuous-integration.yml

**Expected behavior**

PHP is set up with ext-oci8 or ext-pdo_oci

**Screenshots/Logs**

```
Run shivammathur/setup-php@v2
/usr/bin/bash /opt/hostedtoolcache/linux.sh 8.1 /home/runner/work/_actions/shivammathur/setup-php/v2/dist

==> Setup PHP
✓ PHP Installed PHP 8.1.0-dev (db5ac35a50482fa6793f62aaaf1d3a6e8f82c2c0)

==> Setup Tools
✓ composer Added composer 2.1.12

==> Setup Extensions
Error: The process '/usr/bin/bash' failed with exit code 1
```

**Additional context**

N/A

**Are you willing to submit a PR?**

I don't know how to debug it. 😞
