### ISSUE TITLE
Update PCOV to 1.0.10

### ISSUE THREAD

**Issue by mikebronner** [shivammathur/setup-php#539]
**Describe the bug**
When installing PHP 8.1 and using PCOV as a coverage driver, it is throwing errors when running PHPUnit tests in parallel. There is a fix for this in PCOV 1.0.10, but it appears that this package is installing 1.0.9.

**Version**
- [X] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 20.04

**PHP versions**
8.1.0

**To Reproduce**
Run parallel tests using `php artisan test --parallel` through Laravel, or using the package `brianium/paratest` directly.

**Expected behavior**
Test to pass.

As a work-around for the time-being (for anyone else having this issue now), you can do the following in your workflow file:
```
      - name: Set up PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: Install latest version of PCOV. Remove this once Setup-Php is updated to include PCOV 1.0.10 or above.
        run: sudo pecl install pcov
```

**Comment by shivammathur** [comment]
@mikebronner 

I switched to using PECL for pcov in our cache here https://github.com/shivammathur/php-ubuntu/commit/8baf23a8dba9ca785fc541930ed839dba205a15f and it should work now for PHP 8.1, but that is until the GitHub Actions images add PHP 8.1 and those will use PCOV from `ppa:ondrej/php` which has `1.0.9`.

There is already an issue for this here https://github.com/oerdnj/deb.sury.org/issues/1688, so until it is updated on the PPA and in the GitHub actions images, please specify `pcov` with the version in `extensions` input, and setup-php will update it to `1.0.10` if required.

```yml
- name: Set up PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: "8.1"
    extensions: pcov-1.0.10
```
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1559475620/workflow
