### ISSUE TITLE
Workflow fails - mysql: command not found

### ISSUE THREAD

**Issue by wrabit** [shivammathur/setup-php#541]
**Describe the bug**
Since around 6 days, our tests are failing after setup at:

```
sudo /etc/init.d/mysql start
sudo: /etc/init.d/mysql: command not found
```

**Version**
I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [x] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu

**PHP versions**
trying 8.0 and 8.1

**To Reproduce**
```
name: Run tests

on:
  pull_request:
    branches: [ master, staging ]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      -   uses: actions/checkout@v1

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          env:
             update: true          
          with:
            php-version: '8.1'
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
            coverage: none

      -   name: create db
          run: |
            sudo /etc/init.d/mysql start
            mysql  -u root -proot -e 'CREATE DATABASE IF NOT EXISTS db_test;'
            sudo mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -proot mysql
      -   name: Cache composer dependencies
          uses: actions/cache@v1
          with:
            path: vendor
            key: composer-${{ hashFiles('composer.lock') }}

      -   name: Run composer install
          run: composer install -n --prefer-dist

      -   name: Prepare Laravel Application
          run: |
            cp .env.example .env
            php artisan key:generate
      -   name: Run tests
          run: php artisan test --parallel
          env:
            DB_PASSWORD: root
            REDIS_PORT: ${{ job.services.redis.ports[6379] }}
```

**Expected behavior**
The workflow to complete

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/5918271/146139091-3be908ad-2eaa-4ea9-8d38-59b825334bc3.png)

**Additional context**
Same error in V1 and V2

**Are you willing to submit a PR?**
Do not know the issue
