### ISSUE TITLE
In 8.1+ attempts to create a `Mysqli` instance in fail with a "No such file or directory" exception

### ISSUE THREAD

**Issue by jnvsor** [shivammathur/setup-php#543]
**Describe the bug**
In 8.1+ attempts to create a `Mysqli` instance in fail with a "No such file or directory" exception

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
8.1, 8.2

**Screenshots/Logs**
https://github.com/jnvsor/kint/runs/4555244727
[logs_116.zip](https://github.com/shivammathur/setup-php/files/7731359/logs_116.zip)

---

I'm _not sure_ if this is a bug in setup-php but I know `Mysqli` had some internal changes in 8.1, and I'm at my wits end so I'm writing to ask if you could take a look

**Comment by shivammathur** [comment]
@jnvsor 

Please start the `mysql` service before you run your tests.
```yml
- name: Start mysql service
  run: sudo systemctl start mysql
```

**Comment by jnvsor** [comment]
Hi @shivammathur, that didn't help. Logs are attached. [logs_117.zip](https://github.com/shivammathur/setup-php/files/7731735/logs_117.zip)

The tests receive server info in other PHP versions without needing to `sudo systemctl start mysql` (Specifically the `$mysqli->host_info` string)

I also tried adding the service explicitly as below, but it made no difference:

```
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306
```

If you need more info I could try making a minimal test repo

**Comment by shivammathur** [comment]
With the service container, you will have to set the `MYSQLI_HOST` with the port.
```yml
- run: php ./vendor/bin/phpunit --no-coverage tests
  if: '!matrix.phar'
  env:
    MYSQLI_HOST: localhost:${{ job.services.mysql.ports['3306'] }}
- run: php ./tests/phpunit-phar.php --no-coverage tests
  if: matrix.phar
  env:
    MYSQLI_HOST: localhost:${{ job.services.mysql.ports['3306'] }}
```
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1590635905/workflow
