### ISSUE TITLE
Failing to install Composer does not result in a failed build step

### ISSUE THREAD

**Issue by asgrim** [shivammathur/setup-php#548]
**Describe the bug**
Due to some GitHub Actions issues today, I noticed that if Composer fails to install (`✗ composer Could not setup composer` is shown in the Action's step output), `setup-php` does not actually fail the step. Subsequently, when a future action tries to use `composer`, it receives an error:

```
Run composer update --prefer-lowest --prefer-dist --no-interaction --no-progress
/usr/local/bin/composer: line 1: syntax error near unexpected token `newline'
/usr/local/bin/composer: line 1: `<!DOCTYPE html>'
Error: Process completed with exit code 2.
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 20.04

**PHP versions**
Any

**To Reproduce**
NOTE: This configuration is normally valid, but due to GH actions being unstable currently, that makes the issue "visible"
```yml
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl, composer:v2.1
          extensions: "curl, ${{ matrix.extensions }}"
```

**Expected behavior**

When `✗ composer Could not setup composer` is observed when running `shivammathur/setup-php@v2`, I would expect that build step (`Install PHP` in my case) to fail at that point.

**Screenshots/Logs**

![Screenshot from 2021-12-27 11-17-17](https://user-images.githubusercontent.com/496145/147484663-c4c39578-f00b-49e2-ac06-82207611b7b7.png)

The failing step `✗ composer Could not setup composer` can be observed, yet the step passes and continues, despite `Composer` not having successfully been installed.

**Comment by shivammathur** [comment]
Please set `fail-fast` as `true` to make sure it exits on any errors. 
This is documented in tools support section in the last point.
https://github.com/shivammathur/setup-php#wrench-tools-support

```yml
- name: Setup PHP with fail-fast
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7.1'
  env:
    fail-fast: true
```

In the next release, this will fail by default for `composer`, but to fail for other tools and extensions you will still need to set `fail-fast` to `true`.
