### ISSUE TITLE
ComposerRequireChecker broken since 2.16.0

### ISSUE THREAD

**Issue by ruudk** [shivammathur/setup-php#549]
**Describe the bug**
Since a day we notice that ComposerRequireChecker doesn't work properly anymore.

This might be related to this commit: https://github.com/shivammathur/setup-php/commit/d0696f9f8bc3b0456d759159fadc1bb4f31f1e10

```
ComposerRequireChecker 4.0.0@baa11a4e9e5072117e3d180ef16c07036cafa4a2

In JsonLoader.php line 56:

  unable to read .composer-require-checker.json

In Assert.php line 2060:

  The file ".composer-require-checker.json" does not exist.

check [--config-file CONFIG-FILE] [--ignore-parse-errors] [--output OUTPUT] [--] [<composer-json>]
```

**Version**
- 2.16.0

**Runners**
- [x] GitHub Hosted

**Operating systems**
Ubuntu 20.04

**PHP versions**
PHP 8.0

**To Reproduce**
```yaml
    composer-require-checker:
        strategy:
            fail-fast: false
        runs-on: ubuntu-20.04
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.4.0
            -   name: Setup PHP
                uses: shivammathur/setup-php@2.16.0
                with:
                    php-version: '8.0'
                    coverage: none
                    tools: composer-require-checker
            -   uses: ramsey/composer-install@2.0.5
            -   name: Check dependencies
                run: composer-require-checker check --config-file=.composer-require-checker.json
```

**Expected behavior**
It should just load the config from the checked out directory, instead of the directory where ComposerRequireChecker is installed.

When I change the command to:
```
composer-require-checker check --config-file=$(pwd)/.composer-require-checker.json
```

it works.
