### ISSUE TITLE
execute phpunit 9.5.11 in Github actions

### ISSUE THREAD

**Issue by benblub** [shivammathur/setup-php#551]
**Describe the bug**
Since 2022-01-04 evening without any code changes when i run php bin/phpunit it failed in Github actions. I checked the dir where the command is executed and its in root dir where composer.json is listed and phpunit is allready installed. And before it was working.
Error Output
```
No composer.json found in the current directory, showing available packages from packagist.org
Creating a "phpunit/phpunit" project at "./phpunit-9.5-0"
Installing phpunit/phpunit (9.5.11)
Plugins have been disabled.
  - Installing phpunit/phpunit (9.5.11): Extracting archive
Created project in /home/runner/work/XXX/bin/.phpunit/phpunit-9.5-0
```

A fix is running instead `php vendor/bin/phpunit`

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`

**Runners**

- [x] GitHub Hosted

**Operating systems**

ubuntu-latest

**PHP versions**

8.1

**To Reproduce**

Create a composer.json with added phpunit/phpunit "^9.5"

Workflow steps
````
jobs:
  foo:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, imagick
          coverage: pcov

      - name: Install Composer dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader --no-suggest

      - name: Run Tests
        run: |
          php bin/phpunit # <-- this was working before
````
**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**
