### ISSUE TITLE
Could not install memcached from source - memcached does not have a PHP extension

### ISSUE THREAD

**Issue by ruudk** [shivammathur/setup-php#552]
**Describe the bug**
When trying to install `memcached-php-memcached-dev/php-memcached@master` I get:
```
==> Setup memcached-master
✗ https://github.com/php-memcached-dev/php-memcached https://github.com/php-memcached-dev/php-memcached does not have a PHP extension
✗ memcached-master Could not install memcached-master on PHP 8.0.13
```

**Version**
- latest version

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 20.04

**PHP versions**
8.0.13

**To Reproduce**
```
  with:
    php-version: '8.0'
    coverage: none
    extensions: none ctype curl dom filter hash intl json libxml mbstring memcached-php-memcached-dev/php-memcached@master openssl pcntl pdo posix rdkafka-1.5.1 redis-5.3.5 session simplexml sodium zip zlib
```

**Expected behavior**
No error

I think this code might not be correct:
https://github.com/shivammathur/setup-php/blob/a34eeedd370660bc99d0698c97bfe3018387b1c1/src/scripts/ext/source.sh#L131-L132

as that line does exist:
https://github.com/php-memcached-dev/php-memcached/blob/d3b8ce13f13cee3017aa8a00a0cfb2e7709154d8/config.m4#L398
