### ISSUE TITLE
Installing extensions from PECL is not working when disabling all extensions first

### ISSUE THREAD

**Issue by ruudk** [shivammathur/setup-php#553]
**Describe the bug**
I use the following config:
```yaml
            -   name: Setup PHP
                uses: shivammathur/setup-php@verbose
                with:
                    php-version: '8.0'
                    coverage: none
                    extensions: 'none, igbinary, msgpack, memcached-3.1.4'
                env:
                    fail-fast: true
```

As you can see, I disable all extensions first, and then enable `igbinary` and `msgpack` (as the bundled memcached extension seems to use that), and then I choose not the latest memcached version but one before that, to trigger a PECL install.

I'm using `@verbose`, but no valuable error is logged.

**Version**
- v2

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 20.04

**PHP versions**
8.0

**To Reproduce**
See https://github.com/ruudk/setup-php-reproducers/blob/5f369a7eacb57a6a756d560628ad509c8eb48d93/.github/workflows/test.yaml, 
and failing workflow https://github.com/ruudk/setup-php-reproducers/runs/4753170961?check_suite_focus=true

**Expected behavior**
It should work, or at least show more error info?

**Screenshots/Logs**
Nothing special

**Additional context**

**Are you willing to submit a PR?**
Sure

**Comment by shivammathur** [comment]
On GitHub runners `memcached-3.1.5` should already be installed, so you can use that instead of `memcached-3.1.4`.
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
      php-version: '8.0'
      extensions: 'none, igbinary, msgpack, memcached-3.1.5'
  env:
      fail-fast: true
```

The error here is because PECL requires `xml` extension and if you add that then it will fail because it won't be able to find libmemcached. This can be improved and I will look into it.

Currently, If you want to use `memcached-3.1.4` you can install it using the source API of setup-php instead of PECL as it allows you to specify the library needed for it.
https://github.com/shivammathur/setup-php/wiki/Add-extension-from-source

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
      php-version: '8.0'
      extensions: 'none, igbinary, msgpack, memcached-php-memcached-dev/php-memcached@v3.1.4'
  env:
      fail-fast: true
      MEMCACHED_LIB: libmemcached-dev
```
