### ISSUE TITLE
sudo: command not found

### ISSUE THREAD

**Issue by LlZARD** [shivammathur/setup-php#555]
**Describe the bug**
Setup breaks with following output:

```
/usr/bin/docker exec  50772043d8164cc61863425fc4146e1b13aa7b1ada3d69d5674ee4c45c79d7a3 sh -c "cat /etc/*release | grep ^ID"
/bin/bash /__t/linux.sh 7.4 /__w/_actions/shivammathur/setup-php/v2/dist

==> Setup PHP
/__t/linux.sh: line 182: sudo: command not found
✗ PHP Could not setup PHP 7.4
Error: The process '/bin/bash' failed with exit code 1
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
7.4

**To Reproduce**
```yaml
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: ubuntu
      options: --network-alias testHost

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: imagick
```

**Comment by shivammathur** [comment]
Please specify the `runner` environment variable as `self-hosted`.

https://github.com/shivammathur/setup-php#self-hosted-setup

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  env:
    runner: self-hosted
  with:
    php-version: '7.4'
    extensions: imagick
```

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1719652095/workflow
