### ISSUE TITLE
Composer Failed

### ISSUE THREAD

**Issue by kpadil17** [shivammathur/setup-php#556]
**Describe the bug**
Hi,

I need help, my composer dependencies are not installing because of some missing or unenabled extensions.

Thank you!

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [x] Self Hosted

**Operating systems**
Linux

**PHP versions**
7.4.27

**To Reproduce**
```
- name: Configure PHP 7.3
        uses: shivammathur/setup-php@v2
        env:
          runner: self-hosted
        with:
          php-version: '7.4'
          tools: composer, phpunit
          coverage: xdebug
          extensions: mbstring,PDO,grpc,tokenizer,xml,json,ctype,fileinfo,openssl,bcmath,dom,mbstring,gd,apcu,ast

      - uses: actions/checkout@v1

      - name: Copy Environment Files
        run: php -r "file_exists('.env') || copy('.env.stage', '.env');"

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
```

**Expected behavior**
Failed to install composer dependencies.

**Screenshots/Logs**
```
2022-01-20T01:37:21.8738636Z   Problem 1
2022-01-20T01:37:21.8739810Z     - maatwebsite/excel[3.1.28, ..., 3.1.30] require phpoffice/phpspreadsheet 1.16.* -> satisfiable by phpoffice/phpspreadsheet[1.16.0].
2022-01-20T01:37:21.8741256Z     - maatwebsite/excel[3.1.31, ..., 3.1.x-dev] require phpoffice/phpspreadsheet ^1.18 -> satisfiable by phpoffice/phpspreadsheet[1.18.0, 1.19.0, 1.20.0, 1.21.0].
2022-01-20T01:37:21.8789765Z ##[error]Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - maatwebsite/excel[3.1.28, ..., 3.1.30] require phpoffice/phpspreadsheet 1.16.* -> satisfiable by phpoffice/phpspreadsheet[1.16.0].
    - maatwebsite/excel[3.1.31, ..., 3.1.x-dev] require phpoffice/phpspreadsheet ^1.18 -> satisfiable by phpoffice/phpspreadsheet[1.18.0, 1.19.0, 1.20.0, 1.21.0].
    - maatwebsite/excel 3.1.27 requires phpoffice/phpspreadsheet ^1.16 -> satisfiable by phpoffice/phpspreadsheet[1.16.0, ..., 1.21.0].
    - maatwebsite/excel 3.1.26 requires phpoffice/phpspreadsheet ^1.15 -> satisfiable by phpoffice/phpspreadsheet[1.15.0, ..., 1.21.0].
    - maatwebsite/excel[3.1.20, ..., 3.1.25] require phpoffice/phpspreadsheet ^1.14 -> satisfiable by phpoffice/phpspreadsheet[1.14.0, ..., 1.21.0].
    - maatwebsite/excel[3.1.18, ..., 3.1.19] require phpoffice/phpspreadsheet ^1.10 -> satisfiable by phpoffice/phpspreadsheet[1.10.0, ..., 1.21.0].
    - maatwebsite/excel[3.1.7, ..., 3.1.17] require phpoffice/phpspreadsheet ^1.6 -> satisfiable by phpoffice/phpspreadsheet[1.6.0, ..., 1.21.0].
    - maatwebsite/excel 3.1.0 requires phpoffice/phpspreadsheet ^1.4 -> satisfiable by phpoffice/phpspreadsheet[1.4.0, ..., 1.21.0].
    - maatwebsite/excel[3.1.1, ..., 3.1.6] require illuminate/support 5.5.* || 5.6.* || 5.7.* -> satisfiable by illuminate/support[v5.5.0, ..., 5.7.x-dev].
    - phpoffice/phpspreadsheet[1.4.0, ..., 1.21.0] require ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
    - illuminate/support 5.5.x-dev requires nesbot/carbon ^1.26.0 -> found nesbot/carbon[1.26.0, ..., 1.39.1] but it conflicts with your root composer.json require (^2.45).
    - illuminate/support 5.6.x-dev requires nesbot/carbon 1.26.* -> found nesbot/carbon[1.26.0, ..., 1.26.6] but it conflicts with your root composer.json require (^2.45).
    - illuminate/support[v5.5.0, ..., v5.6.11] require nesbot/carbon ^1.20 -> found nesbot/carbon[1.20.0, ..., 1.39.1] but it conflicts with your root composer.json require (^2.45).
    - illuminate/support[v5.5.40, ..., v5.7.1] require nesbot/carbon ^1.24.1 -> found nesbot/carbon[1.24.1, ..., 1.39.1] but it conflicts with your root composer.json require (^2.45).
    - illuminate/support v5.6.39 requires nesbot/carbon 1.25.* -> found nesbot/carbon[1.25.0, 1.25.1, 1.25.3] but it conflicts with your root composer.json require (^2.45).
    - illuminate/support[v5.7.2, ..., 5.7.x-dev] require nesbot/carbon ^1.26.3 -> found nesbot/carbon[1.26.3, ..., 1.39.1] but it conflicts with your root composer.json require (^2.45).
    - Root composer.json requires maatwebsite/excel ^3.1 -> satisfiable by maatwebsite/excel[3.1.0, ..., 3.1.x-dev].

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/15-xml.ini
    - /etc/php/7.4/cli/conf.d/20-apcu.ini
    - /etc/php/7.4/cli/conf.d/20-ast.ini
    - /etc/php/7.4/cli/conf.d/20-bcmath.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-curl.ini
    - /etc/php/7.4/cli/conf.d/20-dom.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gd.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-intl.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mbstring.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-simplexml.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.4/cli/conf.d/20-xdebug.ini
    - /etc/php/7.4/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.4/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.4/cli/conf.d/20-xsl.ini
    - /etc/php/7.4/cli/conf.d/30-grpc.ini
    - /etc/php/7.4/cli/conf.d/99-pecl.ini
```
