### ISSUE TITLE
PHPUnit code coverage error

### ISSUE THREAD

**Issue by SharkMachine** [shivammathur/setup-php#558]
**Describe the bug**

Defining filter for code coverage gives the following error:

```
Fatal error: Uncaught Error: Class "SebastianBergmann\CodeCoverage\Filter" not found in Standard input code:29
```

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
7.4, 8.0, 8.1

**To Reproduce**
https://github.com/SharkMachine/xmlseclibs/runs/4911038329?check_suite_focus=true

**Expected behavior**
Tests pass and code coverage is generated

**Comment by shivammathur** [comment]
Possibly an issue with PHPUnit phar.

As a workaround, you can install it using composer instead of phar by specifying the whole packagist name.

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1735463587/workflow

```yml
- uses: shivammathur/setup-php@v2
  with:
    php-version: ${{ matrix.php-versions }}
    tools: phpunit/phpunit:9.5
```
