### ISSUE TITLE
Action breaks actions/setup-node

### ISSUE THREAD

**Issue by martijngastkemper** [shivammathur/setup-php#562]
**Describe the bug**
When installing PHP after installing Node the previously installed Node version isn't available anymore. 

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 18.04

**PHP versions**
I've tested 7.4 and 8.1.

**To Reproduce**

This workflow echo's version 16, the default Node version of Ubuntu 18.04

```
on:
  push:

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "10"
      - uses: shivammathur/setup-php@v2
      - run: node --version
```

**Expected behavior**
This workflow echo's version 10, the version installed by `actions/setup-node`:

```
on:
  push:

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: shivammathur/setup-php@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "10"
      - run: node --version
```

**Screenshots/Logs**

Wrong output:

![Screenshot 2022-02-08 at 19 06 02](https://user-images.githubusercontent.com/250662/153049922-2d1ea9c6-c611-41af-bbf9-e6f5e86bb100.png)

Correct output:

![Screenshot 2022-02-08 at 19 07 22](https://user-images.githubusercontent.com/250662/153049501-0c8adef8-c449-4e07-9384-8930aefafdd9.png)

**Are you willing to submit a PR?**

I'm willing to do that, but it will take me some time to dive into the source.
