### ISSUE TITLE
Recent changes break availability of composer-installed command?

### ISSUE THREAD

**Issue by ChrisHardie** [shivammathur/setup-php#563]
**Describe the bug**

I see that some recent changes may affect how composer commands work. Just today I tried an action that failed where it didn't fail a few days ago:

```
Run vapor deploy production
  vapor deploy production
  shell: /usr/bin/bash -e {0}
  env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    VAPOR_API_TOKEN: ***
/home/runner/work/_temp/XXXXXXXXX.sh: line 1: vapor: command not found
Error: Process completed with exit code 127.
```

Noting it here in case it's related and/or others encounter the same.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
8.0

**To Reproduce**
```
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          coverage: none
      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli
      - name: Install Project Dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
      - name: Deploy Environment
        run: vapor deploy production
        env:
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
```
