### ISSUE TITLE
Support `patch` versions in matrix

### ISSUE THREAD

**Issue by SpacePossum** [shivammathur/setup-php#570]
**Describe the feature**
Support `patch` versions in matrix

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Additional context**
Hi all,
Not sure if I'm at the right spot, so please bare with me :sweat_smile: 
What I would like to do is to test with a specific PHP patch version in a matrix. This is partially helpful when testing if your code actually deals effective with that precise PHP version. It could be dealing with a bug or other change with PHP itself that is in one patch version, but not in the another.

You can see my attempt here:

```
        strategy:
            matrix:
                include:
                    - php: '7.1'
                    - php: '7.2.17'
```

Which results in:
https://github.com/symfony/polyfill/runs/5410092057?check_suite_focus=true#step:3:15

```
==> Setup PHP
✓ PHP Installed PHP 7.2.34
```

**Are you willing to submit a PR?**
I'm not familiar with the setup and already focusing on some other FOSS project so I think not.... sorry
