### ISSUE TITLE
`switch_version` doesn't change php-fpm

### ISSUE THREAD

**Issue by cjunge-work** [shivammathur/setup-php#572]
**Describe the bug**
Setting the desired version in the action doesn't switch php-fpm. The default seems to be php8.1 currently, but if I choose 7.4, then alternatives php-fpm isn't updated to php7.4-fpm.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
7.4, 8.1

**To Reproduce**
```
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
```

**Expected behavior**
`/run/php/php-fpm` should invoke php7.4-fpm, but it is linked to php8.1-fpm. php7.4-fpm is installed.

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**
