### ISSUE TITLE
Always install additional extension libs when given

### ISSUE THREAD

**Issue by ruudk** [shivammathur/setup-php#575]
I see that setup-php can automatically [install additional libs](https://github.com/shivammathur/setup-php/wiki/Add-extension-from-source#add-required-libraries-for-the-extension). 

But it appears that this is only picked up when building from source.

Right now, I'm trying to install https://pecl.php.net/package-info.php?package=memcached&version=3.2.0RC2 from PECL and that fails because it needs `libmemcached-dev`.

I provided this:
```yaml
            -   name: Setup PHP
                uses: shivammathur/setup-php@verbose
                with:
                    php-version: '8.1'
                    coverage: none
                    extensions: memcached-3.2.0RC2
                env:
                    fail-fast: true
                    MEMCACHED_LIBS: zlib1g-dev libmemcached-dev
```

It would be great if the same trick works for PECL packages as well.

I solved it by running `sudo apt-get install -y libmemcached-dev` before this step.

**Comment by shivammathur** [comment]
Added support in https://github.com/shivammathur/setup-php/commit/e9884d0d9ae42170c76ccbc614fdf2f6081e2f8a
Will be in the next release.

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/1960085437/workflow

**Comment by ruudk** [comment]
@shivammathur Thank you so much! Any ETA for that release?

**Comment by shivammathur** [comment]
@ruudk I was very busy last week. Will try to do it tomorrow.

**Comment by shivammathur** [comment]
Released `2.18.0` with support.
Docs: https://github.com/shivammathur/setup-php/wiki/Add-extension-from-PECL-with-libraries-and-custom-configuration

**Comment by ruudk** [comment]
I just tested it and it works great:

```yaml
            -   name: Setup PHP
                uses: shivammathur/setup-php@verbose
                with:
                    php-version: '8.1'
                    coverage: none
                    extensions: memcached-3.2.0RC2
                env:
                    fail-fast: true
                    MEMCACHED_LIBS: zlib1g-dev libmemcached-dev
# ✓ memcached-3.2.0RC2 Installed and enabled with libraries libmemcached-dev zlib1g-dev
```

but when I do the same for `rdkafka` it does not:
```yaml
            -   name: Setup PHP
                uses: shivammathur/setup-php@verbose
                with:
                    php-version: '8.1'
                    coverage: none
                    extensions: rdkafka
                env:
                    fail-fast: true
                    RDKAFKA_LIBS: librdkafka-dev

# ✗ rdkafka Could not install rdkafka on PHP 8.1.3
```

Could it be that the `*_LIBS` are skipped when no version is specified?
