### ISSUE TITLE
Could not setup symfony-cli

### ISSUE THREAD

**Issue by thegillou** [shivammathur/setup-php#581]
**Describe the bug**
When using `tools: symfony`, the symfony-cli couldn't be setup.
Here is the error when I run the step with `shivammathur/setup-php@verbose`:
```
[apt-fast 10:21:16]
[apt-fast 10:21:16]Working... this may take a while.
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
[apt-fast 10:21:16]Package manager quit with exit code.
✗ symfony-cli Could not setup symfony-cli
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu:latest

**PHP versions**
PHP 7.3.33

**To Reproduce**
Here is the step :
```
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.3'
                  extensions: intl, zip, memcached
                  tools: symfony
```

**Expected behavior**
The `symfony` binary should be usable.
