### ISSUE TITLE
installs an older version of protobuf

### ISSUE THREAD

**Issue by brettmc** [shivammathur/setup-php#584]
**Describe the bug**
The protobuf version installed by default for me is `3.19.1` (released 2021-10-29). The latest stable on pecl and github is `3.20.0`, but there are other more-recent stable versions in the `3.19.x` line too.
I can force it to install 3.20.0 by instead using `extensions: protobuf-3.20.0`, but I would prefer to not have to maintain that.

I _think_ this is a bug, or a caching issue? I ran the example code below in a brand new test repo to try to eliminate any caching that might be in play.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest
**PHP versions**
8.1
**To Reproduce**
```yaml
name: php
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup php
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: protobuf

    - name: phpinfo
      run: php -i
```
**Expected behavior**
Protobuf latest stable (3.20.0) to be installed

**Screenshots/Logs**
php -i output:
```
protobuf

Version => 3.19.1

Directive => Local Value => Master Value
protobuf.keep_descriptor_pool_after_request => 0 => 0
```
**Additional context**

**Are you willing to submit a PR?**
Yes
