### ISSUE TITLE
Can not downgrad mongodb extension version

### ISSUE THREAD

**Issue by tanguyantoine** [shivammathur/setup-php#585]
**Describe the bug**

I'm trying to install an older version of MongoDB extension but I can't install composer dependencies

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

- ubuntu

**PHP versions**

`7.4`

**To Reproduce**

```yaml
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: 'php-cs-fixer,composer, phpstan, phpunit'
        extensions: 'mongodb-1.7'
    - name: install dependencies
      run: composer install
```

**Expected behavior**

- install mongodb-1.7 extension and do not load others

**Screenshots/Logs**

````
==> Setup Extensions
/home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/extensions/add_extensions.sh: line 157:  3084 Broken pipe             yes '' 2> /dev/null
      3085 Segmentation fault      | sudo "$prefix_opts" pecl install -f -D "$(parse_pecl_configure_options "$suffix_opts")" "$extension" > /dev/null 2>&1
✓ mongodb-1.7 Installed and enabled
PHP Warning:  Module 'mongodb' already loaded in Unknown on line 0
PHP Warning:  Module 'mongodb' already loaded in Unknown on line 0
PHP Warning:  Module 'mongodb' already loaded in Unknown on line 0
✓ grpc Installed and enabled
```
**Additional context**
<!-- Add any other context about the problem here. -->

**Are you willing to submit a PR?**
<!-- We accept pull requests targeting the develop branch. -->
 Unfortunately no :-(

**Comment by shivammathur** [comment]
@tanguyantoine 
Please specify the exact semver version.
Ref: https://pecl.php.net/package/mongodb

```yml
- name: Setup PHP with PECL extension
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7.4'
    tools: 'php-cs-fixer,composer, phpstan, phpunit'
    extensions: 'mongodb-1.7.5'
```
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/2109020097/workflow
