### ISSUE TITLE
Sodium extension not installing

### ISSUE THREAD

**Issue by paragonie-security** [shivammathur/setup-php#594]
**Describe the bug**

When specifying `sodium` as one of the extensions, the sodium extension (which [ships with PHP](https://www.php.net/manual/en/sodium.installation.php) and doesn't need to be installed from PECL) is not enabled.

```yaml
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, sodium
          ini-values: error_reporting=-1, display_errors=On
          coverage: none
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

`ubuntu-latest`

**PHP versions**

`8.1`

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

https://github.com/paragonie/halite/runs/6549507420?check_suite_focus=true#step:5:8

**Additional context**

**Are you willing to submit a PR?**
