### ISSUE TITLE
Failed Set up job on php 7.3

### ISSUE THREAD

**Issue by MaryUshenina** [shivammathur/setup-php#602]
**Describe the bug**
I have following steps in my workflow:
``` 
steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
```
and got error
![image](https://user-images.githubusercontent.com/1484657/171570377-3368dd26-d91d-4023-a29a-7b4b0706ba81.png)

similar flow from 3 day ago worked successfully, so the problem probably caused from recent updates in package from 2022-05-30

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
```ubuntu-latest```

**PHP versions**
```7.3```

**Expected behavior**
set up job successfully
