### ISSUE TITLE
Github action coverage not working in latest PHP version.

### ISSUE THREAD

**Issue by palanisamy-emis** [shivammathur/setup-php#603]
Hi guys, Recently we have upgraded our app from PHP 7.2 to 8.1. After upgrading coverage part shows always 0.0%.
Build.yaml file -  
              - name: Setup PHP
               uses: shivammathur/setup-php@v2
               with:
              php-version: '8.1'
              extensions: mbstring, xml, ctype, iconv, intl, mysql, redis, soap, zip, pdo_mysql
              tools: composer:v2, pecl
              ini-values: xdebug.mode="develop,coverage"
              coverage: xdebug
              ini-set: "extension=mcrypt.so"

<img width="1125" alt="Screenshot 2022-06-08 at 3 39 21 PM" src="https://user-images.githubusercontent.com/70691178/172777633-9c3094a0-5320-4cb2-b654-1a0da208b71f.png">

Could someone help me to fix on this? Thanks

**Comment by shivammathur** [comment]
Please use the following step in your yml to setup php

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.1'
    extensions: mbstring, xml, ctype, iconv, intl, mysql, redis, soap, zip, pdo_mysql, mcrypt
    tools: composer:v2
    coverage: xdebug
```

Setup PHP automatically sets `xdebug.mode` to `coverage` and the extension `mcrypt` should be specified in extensions input.

If you are still facing the issue, please provide a public example reproducing the error, and I will have a look.
