### ISSUE TITLE
Could not install `event` extension

### ISSUE THREAD

**Issue by mbabker** [shivammathur/setup-php#604]
**Describe the bug**
Trying to set up PHP with the `event` extension results in only that extension not being installed.

**Version**
- [X] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 20.04

**PHP versions**
8.1

**To Reproduce**
```yaml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.1'
    tools: composer:v2
    extensions: bcmath, curl, dom, event, gd, intl, libxml, mailparse, mbstring, pcntl, pdo, pdo_mysql, redis, uuid, xml, zip
    coverage: none
```

**Expected behavior**
The `event` extension to be installed from PECL

**Screenshots/Logs**
![Screen Shot 2022-06-10 at 2 25 22 PM](https://user-images.githubusercontent.com/368545/173136208-1be2c437-d727-4292-8f51-7859f6bf5de3.png)

**Additional context**
This is a build we're migrating from another CI for a Symfony application, the job starts up MySQL and Redis and installs `wkhtmltopdf` before setting up PHP and Node.

**Are you willing to submit a PR?**
If I knew how to fix it, sure!
