### ISSUE TITLE
PHP 8.2 build seems out of date or something?

### ISSUE THREAD

**Issue by come-nc** [shivammathur/setup-php#605]
**Describe the bug**

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [ ] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

ubuntu-latest

**PHP versions**

8.2

**To Reproduce**

```
      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite, gd
          coverage: none

      - name: PHPUnit
        working-directory: tests
        run: phpunit --configuration phpunit-autotest.xml
```

**Expected behavior**

I should get the same errors as when running phpunit locally with php 8.2 built from git, especially a lot of errors and warnings about `Using ${var} in strings is deprecated, use {$var} instead at` and `Creation of dynamic property Class::$property is deprecated at`.

**Screenshots/Logs**

I get almost no more errors than with php 8.1.

**Additional context**

How is the PHP 8.2 nightly built? Is it from master branch?

**Are you willing to submit a PR?**
