### ISSUE TITLE
PDOException: could not find driver, upon re-run job it ok

### ISSUE THREAD

**Issue by kevincobain2000** [shivammathur/setup-php#606]
**Describe the bug**

We see PDO errors on **first run**, and _second run_ upon manual re-run job always succeeds with the same workflow file

```
Illuminate\Database\QueryException: could not find driver (SQL: PRAGMA foreign_keys = OFF;)
Caused by
PDOException: could not find driver
```

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [x] Self Hosted by https://github.com/myoung34/docker-github-actions-runner

**Operating systems**
linux

**PHP versions**
8.1

**To Reproduce**

```
      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          ini-values: pcre.jit=1,memory_limit=-1,disable_functions="",pcov.exclude="~(vendor|tests|node_modules)~",pcov.directory="./"
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
        env:
          runner: self-hosted

      - name: PHPUNIT Tests with Code Coverage
        run: |
            ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/coverage.xml --coverage-html build/coverage
```

**Expected behavior**
Setup PHP doesn't fail, but `phpunit` almost always fails whenever a push is made (first run). Interestingly, when we re-run manually by Re-run jobs, it succeeds.

**Screenshots/Logs**

```
Run shivammathur/setup-php@v2
/usr/bin/bash /_work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh

==> Setup PHP
✓ PHP Found PHP 8.1.7

==> Setup Extensions
✓ intl Enabled
✓ gd Enabled
✓ zip Enabled
✓ pdo Enabled
✓ sqlite3 Enabled
✓ pdo_sqlite Enabled
✓ dom Enabled
✓ curl Enabled
✓ libxml Enabled
✓ mbstring Enabled
✓ fileinfo Enabled
✓ exif Enabled
✓ iconv Enabled

==> Setup Tools
✓ composer Added composer 2.3.7

==> Setup Coverage
✓ pcov.enabled=1 Added to php.ini
✓ coverage: pcov PCOV enabled as coverage driver

==> Add php.ini values
✓ pcre.jit=1 Added to php.ini
✓ memory_limit=-1 Added to php.ini
✓ disable_functions= Added to php.ini
✓ pcov.exclude='~(vendor|tests|node_modules)~' Added to php.ini
✓ pcov.directory=./ Added to php.ini

==> #StandWithUkraine
✓ read-more https://setup-php.com/support-ukraine
```

**Additional context**

**Are you willing to submit a PR?**

**Comment by kevincobain2000** [comment]
Thanks that'd be little difficult, since it is an enterprise application. I posted it to see if it is an issue known to your knowledge with self-hosted runners.
The repo is just a Laravel application with phpunit, nothing special. The problem is not with the repo I would think, because upon manual re-run the job always goes to success. Only the first run (upon commit, it fails). I have also checked if the `sqlite` DB_CONNECTION is properly set on cache and envs.

**Comment by kevincobain2000** [comment]
Oddly, on the first job trigger, it also says `no coverage driver`, which upon hitting re-run jobs, the warning disappears as well.

**Comment by shivammathur** [comment]
ok. I will try to recreate it using the runner image you use this weekend with Laravel as the app. Will close it then.

**Comment by kevincobain2000** [comment]
Recently I added the following to the workflow and since then the issue has not appeared. I am not sure if that is what caused PHP extensions to go dark sometimes. But let me post an update if that is helpful

```
    steps:
      - name: Clear any existing tool cache
        run: |
          rm -rf "${{ runner.tool_cache }}" || true
```
