### ISSUE TITLE
Php missing from PATH on clean self-hosted runner

### ISSUE THREAD

**Issue by dino182** [shivammathur/setup-php#608]
**Describe the bug**
No php.exe can be found on the PATH within the context of the setup-php action on a clean self-hosted Windows runner. Instead calls to **php** from subsequent scripts in the current pwsh process resolve to the **Get-Php** cmdlet.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [ ] GitHub Hosted
- [x] Self Hosted

**Operating systems**
Windows 10
Windows Server 2022

**PHP versions**
7.4

**To Reproduce**
```yaml
runs-on: self-hosted
steps:
- name: Setup PHP
  uses: shivammathur/setup-php@3eda58347216592f618bb1dff277810b6698e4ca
  with:
    php-version: '7.4'
    extensions: fileinfo, gd
    tools: composer
```

**Expected behavior**
Action runs successfully and installs all expected tools.

**Screenshots/Logs**
https://github.com/dino182/setup-php-testing/runs/7044714697?check_suite_focus=true#step:2:27

**Additional context**
This will only happen if there is no version of php at all in the path. If the machine has any version available in the path, that will be used by the scripts that call php e.g. [add_tools.ps1](https://github.com/shivammathur/setup-php/blob/4969814b6978d2966d0bee3ff03434c950e9e56a/src/scripts/tools/add_tools.ps1#L16).

**Are you willing to submit a PR?**
Yes. Will create that shortly.
