### ISSUE TITLE
pdo_mysql and pdo_sqlite should install when specified in extension-csv input

### ISSUE THREAD

**Issue by Finesse** [shivammathur/setup-php#61]
I have the following step in [my workflow](https://github.com/Finesse/MicroDB/blob/master/.github/workflows/test.yml):

```yml
- name: Install PHP
  uses: shivammathur/setup-php@1.4.3
  with:
    php-version: 7.0
    extension-csv: pdo, pdo_sqlite, pdo_mysql
```

When the workflow is run, the steps [outputs](https://github.com/Finesse/MicroDB/commit/c1a5ca851f7da023cea68ccc87a169c366778926/checks?check_suite_id=272161301) the following:

```
==> Setup PHP and Composer
✓ PHP Installed PHP7.0
✓ Composer Installed

==> Setup Extensions
✓ pdo Enabled
✗ pdo_sqlite Could not find php7.0-pdo_sqlite
✗ pdo_mysql Could not find php7.0-pdo_mysql
```

And the extensions are not installed and therefore Composer emits an error on the next step. This is a bug because `pdo_sqlite` and `pdo_mysql` exist, work in PHP 7.1–7.3 and are installed on my machine with PHP 7.0.

**Comment by Finesse** [comment]
The workaround is to replace `pdo_sqlite` and `pdo_mysql` with `sqlite` and `mysql` in the workflow step. The `pdo_sqlite` and `pdo_mysql` extensions will be installed and Composer will see them.

```yml
- name: Install PHP
  uses: shivammathur/setup-php@1.4.3
  with:
    php-version: 7.0
    extension-csv: pdo, sqlite, mysql
```
