### ISSUE TITLE
Suggestion: improve feedback about installed Xdebug/Pcov versions

### ISSUE THREAD

**Issue by jrfnl** [shivammathur/setup-php#610]
**Describe the feature**

Currently, when using the `coverage` key, the feedback shown to the user will be along the lines of:
```yaml
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
```
```
==> Setup Coverage
✓ xdebug Xdebug enabled as coverage driver
```

I presume this is similar when using PCov.

I believe it would be useful to be able to see at a glance _which_ Xdebug (or Pcov) version was installed and would like to suggest adjusting the feedback to include this information, like so:

```
==> Setup Coverage
✓ xdebug Xdebug x.x.x enabled as coverage driver
```

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
If/when something is going wrong with the code coverage recording, the Xdebug/Pcov version used is generally needed in the debugging process.

**Describe alternatives**
For Xdebug, it's easy enough to retrieve the information by adding an extra step, but IMO that's an unnecessary extra step and it would be helpful if the information would always be available in the feedback from `setup-php`.
```yaml
      - name: "DEBUG: Show version details"
        run: php -v
```

**Are you willing to submit a PR?**
If you're open to the idea, I'd be happy to attempt a PR for this, though I haven't looked at the implementation details (yet).
