### ISSUE TITLE
Globally installed tools are not added to the `allow-plugins` option in `composer.json`

### ISSUE THREAD

**Issue by ste93cry** [shivammathur/setup-php#611]
**Describe the bug**
Since version `2.2`, any Composer plugin that needs to run must be listed in the [`allow-plugins`](https://getcomposer.org/doc/06-config.md#allow-plugins) config of the `composer.json`. I added the `symfony/flex` plugin to such list in the `composer.json` of my project, but it doesn't work because the tool is installed globally. To solve the problem, the `composer global config --no-plugins allow-plugins.symfony/flex true` command should be ran as part of the setup step.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`ubuntu-latest`

**PHP versions**
`8.1`

**To Reproduce**
```yaml
jobs:
  name: php
  on: [push]
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
         with:
           php-version: 8.1
           tools: flex
```

**Expected behavior**
The `symfony/flex` plugin is installed and allowed to run thanks to it being added to `allow-plugins` in `composer.json`. There should be no warning about the plugin being blocked.

**Screenshots/Logs**
```
symfony/flex (installed globally) contains a Composer plugin which is blocked by your allow-plugins config. You may add it to the list if you consider it safe. See 
https://getcomposer.org/allow-plugins
You can run "composer global config --no-plugins allow-plugins.symfony/flex [true|false]" to enable it (true) or keep it disabled and suppress this warning (false)
```

**Additional context**
None

**Are you willing to submit a PR?**
I'm not familiar with how this action works under the hood, but I can try
