### ISSUE TITLE
Tools: Laravel Pint

### ISSUE THREAD

**Issue by d8vjork** [shivammathur/setup-php#613]
**Describe the feature**

Add Laravel Pint as a tool for those projects that doesn't depend on it or when we don't want to grab dependencies twice (in tests and in code styling check)

The project's URL: https://github.com/laravel/pint

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Are you willing to submit a PR?**

Yes, when I've time to spent today or during this week I'll look at this

**Comment by shivammathur** [comment]
Released in `2.21.0`.

**Comment by Akecel** [comment]
Hello ! Thank you very much for this addition which saves my life ahah. Unfortunately I have a little problem with the setup of this tool.

I hesitated to create a new exit but I prefer to ask here first because I'm sure it's a stupid mistake on my part but if needed I could create an exit if it's a real bug.

I don't think I missed anything but the setup doesn't seem to work :/

Any idea ? Thanks in advance

```
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: pint
      - name: Run Laravel Pint without Fix
        run: pint --test
```

![image](https://user-images.githubusercontent.com/32711265/190985709-67cfac07-c613-4665-9358-85bc7a7b7ac0.png)
