### ISSUE TITLE
How to run a specific PHP version (with patch version)

### ISSUE THREAD

**Issue by Danon** [shivammathur/setup-php#618]
I'm using a solution which behaves differently between PHP `7.1.13` and `7.1.14`, and I'd like to run tests for the in Github Actions.

But when I used 

```yaml
with:
    php-version: 7.1.13
    tools: composer:v2
```

it installed `7.1.33` either way:
![image](https://user-images.githubusercontent.com/13367735/179393397-2281a50b-454a-4e41-8f0f-7f6ea20221c8.png)

Is there a way to run a specific patch version? PHP is known for introducing breaking changes in "patch" version
