### ISSUE TITLE
PCNTL extension is only loaded on php-cli but not on php-fpm on PHP8.1 and ubuntu 22.04

### ISSUE THREAD

**Issue by yobottehg** [shivammathur/setup-php#624]
**Describe the bug**
The `pcntl` extension is installed and enabled on php-cli but not on php-fpm.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu-latest

**PHP versions**
8.1

**To Reproduce**
```
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, amqp, pcntl
```

On the server running php -r "print_r(get_loaded_extensions());" will give you the "okay state" of the pcntl extension on php-cli

Adding a file called info.php with the content <?php print_r(get_loaded_extensions()); ?> and running curl localhost:8000/info.php will not state the `pcntl` extension

**Expected behavior**
Adding an extension loads them in both, php-cli and php-fpm

**Screenshots/Logs**
`[critical] Uncaught Error: Call to undefined function Symfony\Component\Messenger\EventListener\pcntl_signal()`

**Additional context**
The Symfony messenger EventSubscriber checks on cache build if it is needed (executed on php-cli)
```
public static function getSubscribedEvents(): array
    {
        if (!\function_exists('pcntl_signal')) {
            return [];
        }

        return [
            WorkerStartedEvent::class => ['onWorkerStarted', 100],
        ];
    }
```

But only executes the pcntl_signal function on runtime:
```
 public function onWorkerStarted(WorkerStartedEvent $event): void
    {
        pcntl_signal(\SIGTERM, function () use ($event) {
            $this->logger?->info('Received SIGTERM signal.', ['transport_names' => $event->getWorker()->getMetadata()->getTransportNames()]);

            $event->getWorker()->stop();
        });
    }
```

**Are you willing to submit a PR?**
Sure if i can get a hint where i would need to change things :)

**Comment by shivammathur** [comment]
In the builds we use in setup-php, extension pcntl is only compiled with `cli`, `cgi` and `embed` SAPIs. `fpm` and `apache` SAPI are not compiled with it because it is not a good idea to create a fork in these as they won't be able to control the child process.

Read this answer from Joe Watkins here which explains it in detail - https://stackoverflow.com/questions/35026153/call-to-undefined-function-pcntl-fork-php-fpm-nginx

That said and this is not recommended, you can compile `pcntl` using setup-php and enable it in fpm.
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/2753418416/workflow
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: 8.1
    extensions: pcntl-php/php-src@PHP-8.1
  env:
    PCNTL_PATH: ext/pcntl
    PCNTL_CONFIGURE_OPTS: '--enable-pcntl'
- run: |
    echo 'extension=pcntl.so' | sudo tee -a /etc/php/8.1/fpm/conf.d/10-pcntl.ini
```
