### ISSUE TITLE
Snappy extension sometimes isn't getting installed

### ISSUE THREAD

**Issue by ihor-sviziev** [shivammathur/setup-php#626]
**Describe the bug**

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Ubuntu 20.04, Ubuntu 22.04

**PHP versions**
7.4, 8.0, 8.1

**To Reproduce**

```yml
name: Extension workflow
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-20.04, ubuntu-22.04]
        php-versions: ['7.4', '8.0', '8.1']
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: snappy
          tools: composer:v2
          coverage: none

      - name: Testing PHP version
        run: php -v

      - name: Testing Extensions
        run: |
          php -i | grep snappy
          php -m
```

**Expected behavior**
The snappy extension should be installed 

**Screenshots/Logs**
❌ Snappy isn't installed
❌ php-setup action step didn't fail
<img width="744" alt="image" src="https://user-images.githubusercontent.com/1873745/182838676-958c6e36-b613-4f74-9960-530fcc60385a.png">

Example Github Actions run is here:
https://github.com/ihor-sviziev/test-php-setup-with-sodium/runs/7671290756?check_suite_focus=true#step:2:14

**Additional context**
When you're installing the only snappy extension, it works fine:

**Are you willing to submit a PR?**

No

**Comment by shivammathur** [comment]
@ihor-sviziev 

Snappy is not on PECL and there is no package for it.

Please use setup-php's [installing from source API](https://github.com/shivammathur/setup-php/wiki/Add-extension-from-source) for it.

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: ${{ matrix.php }}
    extensions: snappy-kjdev/php-ext-snappy@0.2.1   
```
