### ISSUE TITLE
pick up PHP version from composer.json

### ISSUE THREAD

**Issue by watarukura** [shivammathur/setup-php#629]
**Describe the feature**

for example actions/setup-go@v3, pick up Golang version from go.mod

```yaml
steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-go@v3
    with:
      go-version-file: "go.mod"
  - run: go version
```

I want to pick up PHP version from composer.json, like this

```yaml
steps:
  - uses: actions/checkout@v3
  - uses: shivammathur/setup-php@v2
    with:
      php-version-file: 'composer.json'
  - run: php --version
```

composer.json like this

```json
{
  "name": "foo/bar",
  "version": "0.0.1",
  "license": "MIT",
  "require": {
    "php": "^8.0|^8.1"
  }
}
```

**Version**
- [x] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**

When PHP version up, I must do same change to composer.json and GHA workflow yaml files.

**Describe alternatives**

**Additional context**

**Are you willing to submit a PR?**

I can try!
