### ISSUE TITLE
Setting up the action is slow sometimes

### ISSUE THREAD

**Issue by clxmstaab** [shivammathur/setup-php#63]
in comparison to all other steps within the github action setup-php is comparatively slow.

not sure there is room for improvement but I thought it might be usefull feedback for you. since github action will get payed on a per minute basis after reaching GA the runtime is an important aspect

![image](https://user-images.githubusercontent.com/47448731/67194464-72ccb200-f3f7-11e9-915e-0327c5f84539.png)

our push.yml does not contain something fancy, so I guess there is not much I can do from a consumer point of view:
```
name: PHP Checks

on: [push]

jobs:

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.2
    - run: mkdir -p "$HOME/.phpstan" && composer require --dev phpstan/phpstan-shim --working-dir "$HOME/.phpstan"
    - run: composer install # install the apps dependencies
    - run: $HOME/.phpstan/vendor/bin/phpstan analyse -c app/admin/phpstan.neon.dist
    - run: $HOME/.phpstan/vendor/bin/phpstan analyse -c app/shop/phpstan.neon.dist
    - run: $HOME/.phpstan/vendor/bin/phpstan analyse -c app/portal/phpstan.neon.dist
```
