### ISSUE TITLE
Symfony cli does not install anymore

### ISSUE THREAD

**Issue by starred-gijs** [shivammathur/setup-php#632]
**Describe the bug**
When trying to install the Symfony CLI tool, it fails

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**

8.1

**To Reproduce**

```yaml
      - name: Setup PHP
        uses: shivammathur/setup-php@verbose
        with:
          php-version: 8.1
          tools: symfony-cli
        env:
          fail-fast: true
```
**Expected behavior**

**Screenshots/Logs**

```
Err:3 https://repo.symfony.com/apt  Packages
  Could not handshake: The TLS connection was non-properly terminated. [IP: 3.224.177.130 443]
Ign:4 https://repo.symfony.com/apt  Translation-en
Reading package lists...
E: Failed to fetch https://repo.symfony.com/apt/Packages  Could not handshake: The TLS connection was non-properly terminated. [IP: 3.224.177.130 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
**Additional context**

The docs of the Symfony CLI now points to cloudsmith.io, a cloud based artifact repository. I think the link to the repository needs to be updated?
**Are you willing to submit a PR?**
