### ISSUE TITLE
Deployer version missing error

### ISSUE THREAD

**Issue by bbredewold** [shivammathur/setup-php#633]
**Bug Description**
When deploying our project, we get the error that deployer is not found.
![image](https://user-images.githubusercontent.com/2910910/185135733-53505678-a401-4090-bb97-1e43ddca7b3f.png)

When I compare our deployment with previous ones, there is a difference in the setup step.

**Before:**
<img width="262" alt="image" src="https://user-images.githubusercontent.com/2910910/185136863-9bee6cf9-141f-450c-b6ba-453a4d7b59e0.png">

**After:**
<img width="359" alt="image" src="https://user-images.githubusercontent.com/2910910/185136579-c01534cd-9349-4143-996d-d3a09b462877.png">

Maybe something was changed in the required properties?

**Used Github Action step**
```yaml
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: deployer:6.x
          coverage: none
```

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
- Ubuntu

**PHP versions**
- 8.0
