### ISSUE TITLE
Installing Symfony CLI is very slow

### ISSUE THREAD

**Issue by lmichelin** [shivammathur/setup-php#640]
**Describe the bug**
Installing Symfony CLI takes a lot of time, sometimes more than 1 minute. I think it's since this commit https://github.com/shivammathur/setup-php/commit/44d81f983056c06a11e04e43aa61bf7726912278, 

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`ubuntu-latest`

**PHP versions**
`8.1`

**To Reproduce**
```
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: symfony
        env:
          fail-fast: true
```

**Expected behavior**
Installing Symfony CLI shoud take a few seconds.

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/33673240/187959859-9c2be2a2-0ed9-40c1-95c7-9f372a38ec45.png)
![image](https://user-images.githubusercontent.com/33673240/187959920-30aa4de5-281d-43a7-861f-2229915d7ce1.png)

**Additional context**
Since commit https://github.com/shivammathur/setup-php/commit/44d81f983056c06a11e04e43aa61bf7726912278, the script checks if `brew` is available, but brew is available on GitHub Ubuntu runners and it's slow.

**Are you willing to submit a PR?**
Yes.
