### ISSUE TITLE
Deployer v7 not available as tool

### ISSUE THREAD

**Issue by Tjitse-E** [shivammathur/setup-php#643]
**Describe the bug**
The latest version of Deployer (deployer:7.x) is not available. 

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [] GitHub Hosted
- [x] Self Hosted

**To Reproduce**
```yml
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@7aff4d7a22a77f9733ffda9a5c414fa6043da9d1
        with:
          coverage: none
          extensions: gd, bcmath, soap, pdo_mysql, ctype, curl, dom, hash, iconv, intl, mbstring, openssl, simplexml, xsl, sockets, zip
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2, deployer:7.x
        env:
          runner: self-hosted
```
I also tried:
- `deployer:v7`
- `deployer:7`

**Expected behavior**
Deployer v7 is installed

**Screenshots/Logs**
![CleanShot 2022-09-13 at 20 55 07](https://user-images.githubusercontent.com/14849044/189986626-5ab79ad5-267b-4ccb-bc57-b8b437a055e6.png)

**Comment by shivammathur** [comment]
@Tjitse-E 

I cannot recreate the issue, please try rerunning the workflow and let me know if this persists.
https://github.com/shivammathur/test-setup-php/actions/runs/3048459581/workflow

Also, try with `GITHUB_TOKEN` env on the setup-php step.
```
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

and check you are able to reach https://deployer.org/manifest.json from your server.

**Comment by Tjitse-E** [comment]
@shivammathur  thanks again, adding `GITHUB_TOKEN` did the trick.

Working example:
```
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2, deployer:7.x
        env:
          runner: self-hosted
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deployer version
        run: |
          deployer -V
```

Outputs: Deployer 7.0.2
