### ISSUE TITLE
Could not setup symfony-cli

### ISSUE THREAD

**Issue by wesleylether** [shivammathur/setup-php#653]
**Describe the bug**
As of today I get the following message with configuring the tools:

```
==> Setup Tools
✓ composer Added composer 2.4.2
✗ symfony-cli Could not setup symfony-cli
```

So it is not installing symfony-cli anymore

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-20.04

**PHP versions**
PHP 8.1

**To Reproduce**
```yaml
    tests_be:
        runs-on: [ ubuntu-20.04 ]
        timeout-minutes: 7
        name: Test BE

        strategy:
            matrix:
                php-version: [ 8.1 ]
                composer-version: [ 2 ]

        steps:

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    tools: symfony-cli, composer:${{ matrix.composer-version }}
                    extensions: ctype, gd, iconv, intl, mbstring, pdo_sqlite, json

```
