### ISSUE TITLE
Can't install PEAR extensions on 2.22.0

### ISSUE THREAD

**Issue by morcegon** [shivammathur/setup-php#661]
**Describe the bug**
After upgrading from 2.21.2 to 2.22.0 the PEAR extensions installations stoped working.
I'm having this error log:
```bash
Run pear channel-update pear.php.net
  pear channel-update pear.php.net
  pear install Auth
  pear install Mail
  pear install Net_Curl
  pear install XML_Parser
  pear install XML_Serializer-0.21.0
  pear install Mail_Mim
  shell: /usr/bin/bash -e {0}
  env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
  
Updating channel "pear.php.net"
could not create lock file
Error: Process completed with exit code 1.
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

ubuntu-latest

**PHP versions**

8.0

**To Reproduce**

```yml
    steps:
      - name: Setup PHP and install extensions
        uses: shivammathur/setup-php@2.22.0
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, sockets, igbinary, zip, intl, libxml, soap, oauth, mcrypt
          
      - name: Setup PEAR extensions
        run: |
          pear channel-update pear.php.net
          pear install Auth
          pear install Mail
          pear install Net_Curl
          pear install XML_Parser
          pear install XML_Serializer-0.21.0
          pear install Mail_Mim
```

**Expected behavior**

Expecting no errors on the PEAR extensions step

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**
