### ISSUE TITLE
Set up a nightly build of PHP 8.2.0

### ISSUE THREAD

**Issue by llaville** [shivammathur/setup-php#664]
**Describe the bug**
Nightly build already used the current `PHP 8.2.1-dev` while stable `8.2.0` is not yet available.
 
**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Linux

**PHP versions**
PHP 8.2.x
See example with https://github.com/llaville/php-compatinfo-db/actions/runs/3425826275/jobs/5707010790#step:6:14 using `PHP 8.2.1-dev (d3b22722a0a23a81e5293e8242ef5b87b4615355)`

**To Reproduce**
```
        strategy:
            fail-fast: false
            matrix:
                include:
                    -
                        os: ubuntu-latest
                        php: 8.2
```

**Expected behavior**
Be able to run the upcoming `8.2.0` version (RC5 available) and not the future bugfix release 8.2.1
