### ISSUE TITLE
Intermittent failure installing mcrypt extension

### ISSUE THREAD

**Issue by TomAdam** [shivammathur/setup-php#666]
**Describe the bug**
The action intermittently fails to install the mcrypt extension. The workflow has a 20 part matrix and on each run approximately 6 parts will fail to install as below. On rerun of the failed parts, 1 or 2 will failed, and on a last run they are usually all successful. This began 2022-11-15 12:02PM GMT. It doesn't coincide with a release of the action, mcrypt on PECL or PHP. Also of note is the action itself doesn't fail, meaning the workflows continue when they could have failed much sooner.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2` 1a18b2267f80291a81ca1d33e7c851fe09e7dfc4
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-20.04

**PHP versions**
7.4.32

**To Reproduce**
```yaml
- name: Install PHP 7.4
  uses: "shivammathur/setup-php@v2"
  with:
    php-version: '7.4'
    extensions: imagick, zip, mcrypt, pdo_pgsql, gd, exif, :xdebug
    coverage: none
```

**Expected behavior**
Successful installation of mcrypt extension. Failure of setup-php action step when installation fails

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/1591228/202271821-2fcfe91d-1953-47ae-a5e7-a55589eb154b.png)

**Additional context**

**Are you willing to submit a PR?**
I could take a look in December.
