### ISSUE TITLE
pho with Mssql unit testing code

### ISSUE THREAD

**Issue by vigneshtnd1** [shivammathur/setup-php#667]
**Describe the feature**
pho unit testing with Mssql.

**Version**
- [ ] php 8.1`.

**Underlying issue**
Unable to perform unit testing

**Describe alternatives**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.1'
    extensions: sqlsrv, pdo_sqlsrv
```
