### ISSUE TITLE
Extension sodium loads twice

### ISSUE THREAD

**Issue by mabar** [shivammathur/setup-php#674]
**Describe the bug**

My builds are currently failing on PHP 8.2, because PHP raises warning `PHP Warning:  Module "sodium" is already loaded in Unknown on line 0`. 

I have sodium explicitly listed in php extensions, because without it sodium is not available on some versions (verified with PHP 7.4 on Windows). But even after removal of sodium from list and deleting extensions cache, warning is still raising.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v2` and in master (as of https://github.com/shivammathur/setup-php/tree/aa9b80f15808d36452d0bbac9762905bd9685ac2)
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

- Ubuntu 22.04.1 LTS (haven't checked others)

**PHP versions**

- 8.2

**To Reproduce**

Hopefully this is enough. I will prepare reproduction repo if it is not.
```yml
- name: Checkout
   uses: actions/checkout@v3

- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    tools: 'composer:v2'
    php-version: '8.2'
    coverage: pcov
    ini-values: "zend.assertions=1, assert.exception=1"
```

**Expected behavior**

No warning

**Screenshots/Logs**

- [build failure](https://github.com/orisai/openapi/actions/runs/3665485650/jobs/6196590335)
- [build failure after removal of explicitly listed sodium extension and deleting cache](https://github.com/orisai/auth/actions/runs/3665700586/jobs/6197011206)

**Additional context**

**Are you willing to submit a PR?**

Don't know what should I look for, sorry
