### ISSUE TITLE
Periodic `403: rate limit exceeded` when setting up `composer`

### ISSUE THREAD

**Issue by aaemnnosttv** [shivammathur/setup-php#679]
**Describe the bug**

We're periodically seeing the setup fail to install/setup `composer` specifically, which cites `✗ composer 403: rate limit exceeded` under the "Setup Tools" portion of the setup action.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

- ubuntu-latest

**PHP versions**

- 7.4

**To Reproduce**

```yml
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          extensions: mysqli, runkit7, uopz
          tools: composer:2.1
          php-version: '7.4'
```

**Expected behavior**

The installation for `composer` should succeed.

**Screenshots/Logs**

![image](https://user-images.githubusercontent.com/1621608/209218748-c8886bea-0f37-49ec-9482-f8d25e9b8646.png)

https://github.com/google/site-kit-wp/actions/runs/3760806217/jobs/6391916940#step:4:27

**Additional context**

- It does not happen consistently.
- This only seemed to start happening within the last few weeks or so, but somewhat recently

**Are you willing to submit a PR?**

Absolutely

**Comment by shivammathur** [comment]
@aaemnnosttv 
As you have set the composer version to `2.1`, the action calls the GitHub API to resolve that to the latest release matching that. From my understanding, GitHub Actions runners machines have a limited IP range and a lot of API calls from them as they are shared, the rate limit gets exceeded quite frequently.

To solve this you can set the `GITHUB_TOKEN` environment variable on the `setup-php` step.
https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#requests-from-github-actions

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7.4'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
