### ISSUE TITLE
Consider ability to use Composer LTS

### ISSUE THREAD

**Issue by danielbachhuber** [shivammathur/setup-php#686]
Our deployments started failing a couple of weeks ago: https://github.com/wp-cli/wp-cli-bundle/issues/471

As it turns out, it's probably a bug in Composer v2.5.1: https://github.com/composer/composer/issues/11245#issuecomment-1382413537

While we're fine to wait until the bug is fixed, it would be nice to be able to use Composer LTS with `shivammathur/setup-php`.

Thanks for the consideration!

**Comment by shivammathur** [comment]
@danielbachhuber 

You can specify the composer version as `2.2` in the `tools` input. 
Docs: https://github.com/shivammathur/setup-php#wrench-tools-support

**Please note:** When you specify a `major`/`major.minor` tool version, it is a good idea to specify `GITHUB_TOKEN` env variable to avoid the GitHub API rate limit as the action will call the API to resolve input version to a release.

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: 8.2
    tools: composer:2.2
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/3934647235/workflow
