### ISSUE TITLE
Select an old patch version of PHP

### ISSUE THREAD

**Issue by phil-davis** [shivammathur/setup-php#687]
**Describe the bug**
I want run PHP 8.1.13 and not 8.1.14 because of PHP issue https://github.com/php/php-src/issues/10218 that is fixed in commit https://github.com/php/php-src/commit/d12ba111e03fa4e6d76a66a029f5dbe6265b1ea9 but the next PHP 8.1.15 is not yet released.

See https://github.com/sabre-io/vobject/pull/604

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**
I an trying to use 8.1.13

**To Reproduce**
I have put 
`php-version: 8.1.13`
`update: false`
in https://github.com/sabre-io/vobject/blob/master/.github/workflows/ci.yml

**Expected behavior**
The workflow ends up using PHP 8.1.13

**Screenshots/Logs**
https://github.com/sabre-io/vobject/actions/runs/3964660146/jobs/6793716785
```
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh

==> Setup PHP
✓ PHP Updated to PHP 8.1.14
```

I still get PHP 8.1.14

**Additional context**

**Are you willing to submit a PR?**
Yes, if there is something that can be done about this.

How do I successfully specify an "old" PHP patch version?

**Comment by phil-davis** [comment]
I am not sure if this is a bug or an unimplemented feature!

**Comment by shivammathur** [comment]
@phil-davis 
This would be a feature I cannot support currently. More about that here #618

As an alternative till we have a new PHP version, please specify a container with PHP 8.1. We maintain `setupphp/node` images for setup-php to run on self-hosted environments and they can be used in this situation.
https://hub.docker.com/repository/docker/setupphp/node/tags

```yml
jobs:
  test:
    runs-on: ubuntu-latest
    container: setupphp/node@sha256:32a6c9fc7882993822650c62ef8f8cb5202a2827f92c07687d68cfc80140c849
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: `8.1`
```
