### ISSUE TITLE
SQL Server extension (PHP 8.1.9)

### ISSUE THREAD

**Issue by amichallet-cc** [shivammathur/setup-php#693]
**Describe the bug**
Can't install sqlsrv extension for PHP 8.1.9

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Using in Github Action

**PHP versions**
8.1.9

**To Reproduce**
```
    steps:
      - uses: actions/checkout@v2
      - name: copy dot env
        run: cp .env.test.dist .env
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv, intl, sqlsrv-5.10.1 (tried with sqlsrv,  5.11.0beta1, same behaviour)
          coverage: pconv
```

**Expected behavior**
sqlsrv extension installed and configured

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/119956771/215509218-c84ceead-19ff-48ae-b3bb-325db793ee85.png)
