### ISSUE TITLE
Wrong php version gets installed

### ISSUE THREAD

**Issue by benblub** [shivammathur/setup-php#695]
**Describe the bug**
I have a action.yml which defines the setup php

I changed from PHP 8.1 to 8.2
```yaml
name: Setup PHP
description: 'Setup PHP with required extensions, php.ini configuration, code-coverage support and various tools like composer in GitHub Actions.'

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pcntl-php/php-src@PHP-8.2, mbstring, xml, ctype, iconv, intl, pdo_sqlite, imagick, amqp
        coverage: pcov
        ini-values: sendmail_path=/usr/local/bin/mhsendmail
      env:
        PCNTL_PATH: ext/pcntl
        PCNTL_CONFIGURE_OPTS: '--enable-pcntl'

```

This composite file is imported from 2 other workflows. `- uses: ./.github/actions/php`. The problem is that one of the workflows still installs PHP 8.1, the other installs 8.2

I have no clue why this happen. Is there some caching mechanism?

````
Getting action download info
Download action repository 'shivammathur/setup-php@v2' (SHA:d[3](https://github.com/...#step:7:3)0ad8b18[4](https://github.com/...#step:7:4)3ace22e6698ab99bbafaa747b6bd0d)
Run ./.github/actions/php
Run shivammathur/setup-php@v2
  with:
    php-version: 8.1
    extensions: pcntl-php/php-src@PHP-8.1, mbstring, xml, ctype, iconv, intl, pdo_sqlite, imagick, amqp
    coverage: pcov
    ini-values: sendmail_path=/usr/local/bin/mhsendmail
    ini-file: production
````

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Comment by shivammathur** [comment]
Please provide the workflow link. As you can see in the output the action is getting the php-version input as 8.1 and so it installed PHP 8.1.

Please provide me with the link to the whole workflow and I can check. If it is a composite workflow, check the inputs and the defaults defined in the actions.yml for the composite workflow.

**Comment by benblub** [comment]
It's private repo but i can share here the workflows/files.

PHP Composite action.yml
```yaml
name: Setup PHP
description: 'Setup PHP with required extensions, php.ini configuration, code-coverage support and various tools like composer in GitHub Actions.'

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pcntl-php/php-src@PHP-8.2, mbstring, xml, ctype, iconv, intl, pdo_sqlite, imagick, amqp
        coverage: pcov
        ini-values: sendmail_path=/usr/local/bin/mhsendmail
      env:
        PCNTL_PATH: ext/pcntl
        PCNTL_CONFIGURE_OPTS: '--enable-pcntl'
```

The workflow which installs PHP 8.1
```yaml
name: API Migrations testing

on:
  pull_request:
    paths:
      - 'api/migrations/**'
      - 'api/src/Entity/**'
      - '.github/workflows/**'
    types: [ opened, synchronize, reopened ]

env:
  ....

jobs:
  api_migrations_testing:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.0.0
        ports:
          - 6379:6379
    defaults:
      run:
        working-directory: ./api
    steps:
      # Checkout target branch
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop
      - uses: ./.github/actions/mariadb
      - name: Create certs
        run: |
          openssl genpkey -out config/jwt/private.pem -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096 -pass pass:test
          openssl pkey -in config/jwt/private.pem -passin pass:test -out config/jwt/public.pem -pubout
      - uses: ./.github/actions/php
      - uses: ./.github/actions/composer
      - name: Run migrations for target branch
        run: |
          php bin/console doctrine:migration:migrate -n
          php bin/console doctrine:fixtures:load -n --group=Fixtures:Complete
      # checkout the current PR branch
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # Install composer dependencies of the PR branch
      - name: Install Composer dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Export and compare schema
        run: |
          APP_ENV=prod php bin/console api:openapi:export --output ../client/src/schema/schema_fresh.json
          cmp --silent ../client/src/schema/schema_fresh.json ../client/src/schema/schema.json || exit 1
      # Run the migrations of the PR branch against an existing database of the target branch
      - name: Run migrations for head branch
        run: |
          php bin/console doctrine:migration:migrate -n
          php bin/console doctrine:fixtures:load -n --group=Fixtures:Complete
      - name: Run migrations complete for head branch
        run: |
          php bin/console doctrine:database:drop --force
          php bin/console doctrine:database:create
          php bin/console doctrine:migration:migrate -n
          php bin/console doctrine:fixtures:load -n --group=Fixtures:Complete
      - name: Check that the mapping of the entities and database are up-to-date
        run: |
          php bin/console doctrine:migrations:up-to-date
          php bin/console doctrine:schema:validate
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ..
          known_hosts: ..
      - uses: adam7/platformsh-cli-action@v1.1
        with:
          token: token..
      - name: Get dev database
        run: platform db:dump -p XXX -e ${{ github.base_ref }} -A api -f db_dump.sql
      - name: Import database with data and run migrations
        run: |
          php bin/console doctrine:database:drop --force
          php bin/console doctrine:database:create
          mysql -uroot -proot -h127.0.0.1 -P3306 foo_test < db_dump.sql
          php bin/console cache:clear
          php bin/console doctrine:migration:migrate -n
```

The working action (short version)
```yaml
jobs:
  api_lint_and_test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.0.0
        ports:
          - 6379:6379
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/mariadb
      - uses: ./.github/actions/php
      - uses: ./.github/actions/composer
      - name: Install PHPCSFixer
```

**Comment by shivammathur** [comment]
@benblub 
Please provide the `.github/actions/php` file

**Comment by benblub** [comment]
> @benblub Please provide the `.github/actions/php` file

Thats the first code snippet @shivammathur 

```yaml
name: Setup PHP
description: 'Setup PHP with required extensions, php.ini configuration, code-coverage support and various tools like composer in GitHub Actions.'

runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: pcntl-php/php-src@PHP-8.2, mbstring, xml, ctype, iconv, intl, pdo_sqlite, imagick, amqp
        coverage: pcov
        ini-values: sendmail_path=/usr/local/bin/mhsendmail
      env:
        PCNTL_PATH: ext/pcntl
        PCNTL_CONFIGURE_OPTS: '--enable-pcntl'
```
