### ISSUE TITLE
Action started failing on 06.02.2023

### ISSUE THREAD

**Issue by bohdan-sokulskyi-n-ix** [shivammathur/setup-php#698]
**Describe the bug**
Action `shivammathur/setup-php` started either failing or been working for ~40 minutes before it's finished

**Version**
- [*] `v2`

**Runners**
- [*] GitHub Hosted

**Operating systems**
ubuntu-20.04

**PHP versions**
8.0

**To Reproduce**
```
name: Debug
on:
  push:
jobs:
  phpunit-tests:
    name: PHPUnit Tests (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-20.04
    container: shivammathur/node:focal-slim
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, zip, json, pdo, imagick, bcmath, redis, apcu, gd, mysql
          tools: composer:v2
        env:
          update: true
```

**Expected behavior**
Workflow works correctly

**Screenshots/Logs**
Output is like:
```
Run shivammathur/setup-php@v2
  with:
    php-version: 8.0
    extensions: mbstring, intl, zip, json, pdo, imagick, bcmath, redis, apcu, gd, mysql
    tools: composer:v2
    ini-file: production
  env:
    update: true
/usr/bin/docker exec  9703e6ad126f2b0ecd1e5a2c45208f9ee0f61024e23c1f8da7d67b26c289275b sh -c "cat /etc/*release | grep ^ID"
/usr/bin/bash /__w/_actions/shivammathur/setup-php/v2/src/scripts/run.sh

==> Setup PHP
Error: The process '/usr/bin/bash' failed with exit code 1
```
