### ISSUE TITLE
Intermittent failures fetching CA certificate bundle in Windows+WSL

### ISSUE THREAD

**Issue by asgrim** [shivammathur/setup-php#699]
**Describe the bug**
During the execution of `shivammathur/setup-php@v2`, sometimes we get a failure:

```
 ==> Setup PHP 
✗ PHP Could not fetch CA certificate bundle from Curl 
```

Despite us having `fail-fast: true` enabled, this does not cause the job to fail, however, it does mean that some HTTPS requests later on fail (https error, because CA bundle is out of date).

The failure is intermittent, and re-running the failed jobs from GH actions will eventually turn them all green.

 * Attempt 1 - https://github.com/scoutapp/scout-apm-php/actions/runs/4111683233/attempts/1
 * ...
 * Attempt 5 - https://github.com/scoutapp/scout-apm-php/actions/runs/4111683233

Originally I thought it was a fault of #692 but that issue was closed.

I have previously tried using `shivammathur/setup-php@verbose` but there is [no additional useful output](https://github.com/scoutapp/scout-apm-php/actions/runs/4075273458/jobs/7021797172#step:5:25).

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`windows-latest`, using `Vampire/setup-wsl@v2`

**PHP versions**
PHP 7.2 through to 8.2

**To Reproduce**

https://github.com/scoutapp/scout-apm-php/blob/30459215638fec79b8fb221cf1844cb75db39ba4/.github/workflows/continuous-integration.yml#L93-L130

```yaml
    steps:
      - uses: actions/checkout@v3
      - uses: Vampire/setup-wsl@v2
        if: ${{ matrix.os == 'windows-latest' }}
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ matrix.scout-ext == 'with-scout-ext' && 'zend_extension=D:\\a\\scout-apm-php\\scout-apm-php\\php_scoutapm.dll' || '' }}"
          tools: pecl, composer:v2.3
          extensions: "curl, sockets, fileinfo, ${{ matrix.extensions }}"
        env:
          fail-fast: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**

I should see:

```
==> Setup PHP 
√ PHP Installed PHP 7.2.34 
```

(replacing the PHP version with the appropriate version for each job)

**Screenshots/Logs**

![Screenshot from 2023-02-07 08-29-42](https://user-images.githubusercontent.com/496145/217192231-bcfcb0af-400d-482c-9e49-85ccf9aeaeb0.png)

**Additional context**

**Are you willing to submit a PR?**
I have no idea what the cause of the problem is, so wouldn't know where to start :(
