### ISSUE TITLE
Error: Input required and not supplied: php-version

### ISSUE THREAD

**Issue by J-Ben87** [shivammathur/setup-php#702]
Hi,

Thank you for your job and sorry to bother, this may be quite obvious for you but I'm struggling with this error.
I'm following the doc and trying to reproduce working examples, but I can't get my job to run properly.

I'm running it with the following file:

```
# .github/workflows/quality.yml

name: Quality

on:
    push:
        branches: ['*']

jobs:
    phpcs:
        name: PHP CodeSniffer
        runs-on: 'ubuntu-latest'

        strategy:
            matrix:
                php_version: ['8.1']

        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}

# ...
```

And getting the following error output:

```
Run shivammathur/setup-php@v2
  with:
    ini-file: production
Error: Input required and not supplied: php-version
```
![image](https://user-images.githubusercontent.com/1433301/218218147-4cca5cca-1a09-45be-9dc7-4649480ce18c.png)

Also when I directly set `php-version: '8.1'` instead of setting it with the `php-version: ${{ matrix.php-version }}` notation, everything works fine.
In this case I could do it, but for another job I need to run some steps on several php versions.

Any idea what I am doing wrong?
