### ISSUE TITLE
PHP patch version ignored

### ISSUE THREAD

**Issue by Bilge** [shivammathur/setup-php#704]
**Describe the bug**
This action only cares about the PHP major/minor version, but ignores the patch version (major.minor.patch).

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
8.1.13

**To Reproduce**
```yaml
jobs:
  Test:
    strategy:
      matrix:
        php:
          - 8.1.13
          - 8.2.0

    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
```
**Expected behavior**
Install exact PHP version (including patch version).

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/470626/220121917-a689c671-40ac-43c9-8889-2f8dd83e7462.png)

**Additional context**
https://github.com/Provider/Steam/actions/runs/4223861211/jobs/7334088925

**Are you willing to submit a PR?**
No lol
