### ISSUE TITLE
Intermittent failures at setup redis step

### ISSUE THREAD

**Issue by angeleg** [shivammathur/setup-php#708]
**Describe the bug**
Our build sometimes fails at the setup redis step. 

**Version**
- [x] `v2.24.0`

**Runners**
- [x] GitHub Hosted

**Operating systems**
Ubuntu
20.04.5
LTS

**PHP versions**
8.1.16

**To Reproduce**
```
-   name: Setup PHP
    id: setup-php
    uses: shivammathur/setup-php@2.24.0
    with:
        php-version: '8.1'
        coverage: none
        extensions: mbstring,bcmath,intl,gd,zip,memcached-3.2.0,redis-phpredis/phpredis@552f41a44f0687c221e5d4adf9ee387479bb78a1,rdkafka
    env:
        fail-fast: true
```

**Expected behavior**
No failures

**Screenshots/Logs**
Output:
```
>Run shivammathur/setup-php@2.24.0
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/2.24.0/src/scripts/run.sh

==> Setup PHP
✓ PHP Found PHP 8.1.16

==> Setup Extensions
✓ mbstring Enabled
✓ bcmath Enabled
✓ intl Enabled
✓ gd Enabled
✓ zip Enabled
✓ memcached Enabled

==> Setup redis-552f41a44f0687c221e5d4adf9ee
>git clone
>git submodule
>phpize
>configure
>make
>make install
✓ redis-552f41a44f0687c221e5d4adf9ee387 Installed from https://github.com/phpredis/phpredis and enabled
Error: The process '/usr/bin/bash' failed with exit code 1
```
