### ISSUE TITLE
assert() does not throw error. 

### ISSUE THREAD

**Issue by joelharkes** [shivammathur/setup-php#721]
**Describe the bug**

assert() should by default throw exception in >PHP8.0: https://php.watch/versions/8.0/assert-throws
But it does not, the tests fail with: `Failed asserting that exception of type "AssertionError" is thrown.`

**Version**
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Default github linux 
**PHP versions**

8.1

**To Reproduce**

```
    public function testThrowsOnRandomString(): void
    {
        $this->expectException(\AssertionError::class);
        new ValidEnum('asdfasdf');
    }
```

```
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.1]
        laravel: [10.*]
        stability: [prefer-stable]
#        exclude:
#          -   php: 8.0
#              laravel: 10.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, intl, gd, exif, iconv
            coverage: none
      -   name: Install dependencies
          run: |
            composer install
            composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
            composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      -   name: Execute tests
          run: vendor/bin/phpunit
```
**Expected behavior**

Test to succeed as assert should throw.

**Screenshots/Logs**

`Failed asserting that exception of type "AssertionError" is thrown.`

**Additional context**

**Are you willing to submit a PR?**

I'd have to figure out your codebase, but sure :)
