### ISSUE TITLE
Composer v2 uses older version

### ISSUE THREAD

**Issue by ihor-sviziev** [shivammathur/setup-php#733]
**Describe the bug**

In version 2.5.6, the regression issue was introduced https://github.com/composer/composer/issues/11480. It was fixed in 2.5.7, but this version isn't getting installed.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

- ubuntu-20.04

**PHP versions**

- 8.1

**To Reproduce**

```yml
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: none
```

**Expected behavior**

Installs latest composer version, which is 2.5.7. 

**Screenshots/Logs**

Not it installs 2.5.6, which 
<img width="772" alt="image" src="https://github.com/shivammathur/setup-php/assets/1873745/362b3e41-ac23-4520-b979-426bc2f59de2">

**Additional context**

**Are you willing to submit a PR?**
