### ISSUE TITLE
phpunit 404: Not found with v2.25.3

### ISSUE THREAD

**Issue by blizzz** [shivammathur/setup-php#743]
**Describe the bug**

With today's v2.25.3 the installation of phpunit:9 fails. Going back to 2.25.2 has it succeeding.

**Version**
- [X] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu-20.04

**PHP versions**
8.0, 8.1, 8.2

**To Reproduce**

```
name: PHPUnit foobar

on: pull_request

permissions:
  contents: read

concurrency:
  group: phpunit-foobar-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpunit-foobar:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']

    steps:
      - name: Checkout server
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ctype, curl, dom, fileinfo, gd, imagick, intl, json, mbstring, oci8, openssl, pcntl, pdo_sqlite, posix, sqlite, xml, zip
          tools: phpunit:9
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

**Expected behavior**

In the Set Up PHP 8.x step we  expect phpunit to be added correctly, like:

```
✓ phpunit Added phpunit 9.6.9
```

**Screenshots/Logs**

![Screenshot_20230612_201624](https://github.com/shivammathur/setup-php/assets/2184312/284b1b10-c535-47d5-8ccd-fa6f82b6f504)

**Additional context**

When we use setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d (2.25.2) we get the expected behaviour.

**Are you willing to submit a PR?**
Not familiar with typescript or writing actions :(
