### ISSUE TITLE
Installation of gd fails on 32bit with PHP 8.0

### ISSUE THREAD

**Issue by SystemKeeper** [shivammathur/setup-php#750]
**Describe the bug**

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [x] Self Hosted

**Operating systems**

Ubuntu 22.04 on selfhosted host, using `shivammathur/node:latest-i386` as container

**PHP versions**

8.0

**To Reproduce**

```yml
name: Test 32bit

on:
  pull_request:

jobs:
  phpunit-32bits:
    runs-on: ubuntu-22.04

    container: shivammathur/node:latest-i386

    strategy:
      matrix:
        php-versions: ['8.0']

    steps:
      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd
          tools: phpunit:9
          coverage: none
          ini-values:
            apc.enabled=on,
            apc.enable_cli=on
```

results in 

```
==> Setup Extensions
grep: /etc/apt/sources.list: No such file or directory
✗ gd Could not install gd on PHP 8.0.29
```

**Expected behavior**

Works 😉 

**Screenshots/Logs**

**Additional context**

Running `apt install php8.0-gd` inside the container works. The file `/etc/apt/sources.list` is indeed missing.

**Are you willing to submit a PR?**
