### ISSUE TITLE
Setup php 8.2 failed

### ISSUE THREAD

**Issue by ThanatosDi** [shivammathur/setup-php#752]
**Describe the bug**

When I want setup php 8.2, it return "The process '/usr/bin/bash' failed with exit code 1".
And when I change php version to 8.1, it will success setup.

![image](https://github.com/shivammathur/setup-php/assets/12424898/92887a90-05af-4e6b-8a02-da2f4c640ee7)

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [x] Self Hosted

**Operating systems**

Ubuntu 22.04

**PHP versions**

8.2

**To Reproduce**

```yaml
name: PHPUnit

on:
  pull_request:
      branches:
        - main
        - production
        - master
  workflow_dispatch:

env:
  salary-pwd: ${{ github.workspace }}/{project-folder}
  php-version: 8.2
  php-extensions: mongodb,redis,sqlite3,gd,bcmath
  key: cache-v1
  nodejs-version: 18

jobs:
    PHPUnit:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v3

        - name: Setup PHP
          uses: shivammathur/setup-php@master
          with:
            php-version: ${{ env.php-version }}
            extensions: ${{ env.php-extensions }}
            tools: composer:v2
```

**Expected behavior**

setup success

**Screenshots/Logs**

![image](https://github.com/shivammathur/setup-php/assets/12424898/92887a90-05af-4e6b-8a02-da2f4c640ee7)

**Additional context**

**Are you willing to submit a PR?**
