### ISSUE TITLE
Laravel pint no longer found

### ISSUE THREAD

**Issue by lionslair** [shivammathur/setup-php#765]
**Describe the bug**
Laravel pint not found. This is across multiple repositories

**Version**
- [* ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [ *] `v2`
- [ ] `v1`

**Runners**
- [ *] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
8.1 8.2

**To Reproduce**

```
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: pint
```

**Expected behavior**
Runs laravel pint

**Screenshots/Logs**

![image](https://github.com/shivammathur/setup-php/assets/832259/64cf02ce-c6f8-4ea0-b480-db6cb8d3fc0c)

![image](https://github.com/shivammathur/setup-php/assets/832259/0d3c8334-526b-4f0d-8688-dd96d56846f3)

![image](https://github.com/shivammathur/setup-php/assets/832259/5f4dc17b-1423-4fe8-9ca7-c47de5b4c037)

**Additional context**

```

0s
Run pint
  pint
  shell: /usr/bin/bash -e {0}
  env:
    COMPOSER_PROCESS_TIMEOUT: 0
    COMPOSER_NO_INTERACTION: 1
    COMPOSER_NO_AUDIT: 1
/usr/local/bin/pint: line 1: Not: command not found
Error: Process completed with exit code 127.
````
