### ISSUE TITLE
PHP8.3 + gd: Unable to load dynamic library 'gd.so'

### ISSUE THREAD

**Issue by tinect** [shivammathur/setup-php#767]
**Describe the bug**
PHP Startup: Unable to load dynamic library 'gd.so' (tried: /usr/lib/php/20230831/gd.so (/usr/lib/php/20230831/gd.so: undefined symbol: gdImageCreateFromAvif), /usr/lib/php/20230831/gd.so.so (/usr/lib/php/20230831/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
8.3

**To Reproduce**
```
- uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
```

**Expected behavior**
No warning and working setup.

**Additional context**
https://github.com/tinect/flysystem-garbage/actions/runs/6208371225/job/16855844375#step:3:13

**Are you willing to submit a PR?**
