### ISSUE TITLE
1 Hour to install PHP.

### ISSUE THREAD

**Issue by padupe** [shivammathur/setup-php#777]
**Describe the bug**
The process is taking more than 1 hour and is not completed.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [ ] GitHub Hosted
- [x] Self Hosted

**Operating systems**
Ubuntu 22.04

**PHP versions**
8.1 and 8.2

**To Reproduce**
```yaml
name: PR Validation

on:
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  code_quality:
    runs-on: self-hosted
    steps:
      - name: "Checkout app"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
      
      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress
      
      - name: Run tests with PHP Pest
        run: ./vendor/bin/pest --coverage-xml coverage

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.acme-enterprise.com/
        
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```

**Expected behavior**
Installation carried out in a short period.

**Screenshots/Logs**
![image](https://github.com/shivammathur/setup-php/assets/72894267/e0be581d-2d8f-44ba-8cf0-9f9b307e4416)

**Additional context**
I believe it is related to the issue #773.

**Are you willing to submit a PR?**
I can contribute if necessary. :)
