### ISSUE TITLE
unable to install parallel-lint

### ISSUE THREAD

**Issue by staabm** [shivammathur/setup-php#782]
**Describe the bug**
today our jobs using parallel-lint started failling

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`runs-on: ubuntu-latest`

**PHP versions**
```
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    tools: cs2pr, parallel-lint
                    coverage: none
```

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**
![image](https://github.com/shivammathur/setup-php/assets/120441/1930fe2b-0642-44fc-8843-841535435097)

![grafik](https://github.com/shivammathur/setup-php/assets/120441/38b41599-14ab-4fd5-aa20-83ce04ed29a9)

**Additional context**

**Are you willing to submit a PR?**
