### ISSUE TITLE
Debug symbols not included in libphp 8.3 ZTS even when debug set to true

### ISSUE THREAD

**Issue by dunglas** [shivammathur/setup-php#784]
**Describe the bug**
libphp8.3.so ZTS is stripped even when `debug` is true.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 22.04.3 LTS 

**PHP versions**
PHP 8.3 nightly

**To Reproduce**
```yaml
     -
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          ini-file: development
          coverage: none
          tools: none
        env:
          phpts: ts
          debug: true
```

**Expected behavior**
Debug symbols should be included.

**Screenshots/Logs**
```
$ file /usr/lib/libphp8.3.so
/usr/lib/libphp8.3.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=0aaebe820406e66a76acb2588689bc16bbd023dc, stripped
```

**Additional context**
n/a

**Are you willing to submit a PR?**
yes
