### ISSUE TITLE
Install ext-swoole failed on PHP 8.3.0-dev

### ISSUE THREAD

**Issue by huangdijia** [shivammathur/setup-php#786]
**Describe the bug**

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

github actions > Ubuntu 22.0

**PHP versions**

PHP 8.3.0-dev (1e66e6ae73c6d05db21cf0e11e926a8ecd789a39)

**To Reproduce**

```yml
name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Test on PHP ${{ matrix.php }} with Swoole ${{ matrix.swoole }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-22.04]
        # php: ['8.0', '8.1', '8.2', '8.3']
        php: ['8.3']
        # swoole: ['4.8.13', '5.0.3', '5.1.0']
        swoole: ['5.1.0']
        exclude:
          - php: '8.2'
            swoole: '4.8.13'
          - php: '8.3'
            swoole: '4.8.13'
          - php: '8.3'
            swoole: '5.0.3'
      max-parallel: 20
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, pdo, pdo_mysql, bcmath, swoole-${{ matrix.swoole }}
          tools: phpize
          coverage: none
      - name: Show Imformations
        run: |
          php -v
          php --ini |grep ini
          php --ri swoole
```

**Expected behavior**

**Screenshots/Logs**

[action link](https://github.com/friendsofhyperf/components/actions/runs/6957076122/job/18929273728)

```shell
/home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/extensions/add_extensions.sh: line 9: 10453 Segmentation fault      (core dumped) php -m > "$extension_list"
/home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/../scripts/extensions/add_extensions.sh: line 79: 10460 Segmentation fault      (core dumped) php -d'error_reporting=0' "${src:?}"/scripts/extensions/extension_map.php /tmp/map"$version".orig > /dev/null 2>&1
PHP Warning:  Module "swoole" is already loaded in Unknown on line 0
PHP Warning:  Module "swoole" is already loaded in Unknown on line 0
✗ swoole Could not install swoole on PHP 8.3.0-dev
```

**Additional context**

**Are you willing to submit a PR?**

No
