### ISSUE TITLE
Install doesn't respect the `amqp` extension version constraint

### ISSUE THREAD

**Issue by nebkam** [shivammathur/setup-php#791]
**Describe the bug**

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

`ubuntu-latest`

**PHP versions**

`7.4`

**To Reproduce**

Added a specific version of **amqp** extension:
> extensions: apcu, gd, imagick, intl, mongodb-1.14.0, mysqli, pdo, pdo_mysql, zip, amqp-1.11.0

It installs the wrong version (`amqp-2.1.1`)

**Expected behavior**

To install the specific version of the PHP extension (`amqp-1.11.0`)  or fail.

**Screenshots/Logs**

![Screenshot from 2023-11-28 08-25-09](https://github.com/shivammathur/setup-php/assets/1735290/a2206c33-7d82-43a7-878b-6d427dcda158)

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
@nebkam 
Installing amqp from pecl requires `librabbitmq`. You can specify the package for that in the `AMQP_LIBS` env and it will install correctly.
```yml
- name: Setup PHP with extensions
  uses: shivammathur/setup-php@verbose
  with:
    php-version: 8.1
    extensions: amqp-1.11.0
  env:
    AMQP_LIBS: librabbitmq-dev
```

Ref: https://github.com/shivammathur/setup-php/wiki/Add-extension-from-PECL-with-libraries-and-custom-configuration
