### ISSUE TITLE
Since `2.28.0` stopped to install extensions on `ubuntu-latest` OS

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#796]
**Describe the bug**
Since `2.28.0` version, jobs stopped to install extensions on `ubuntu-latest` OS. Works when specify version of Ubuntu.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu

**PHP versions**
Any

**To Reproduce**
```yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: phalcon, swoole
          tools: pecl
```
