### ISSUE TITLE
setup-php with 8.4 (nightly) is slow

### ISSUE THREAD

**Issue by brettmc** [shivammathur/setup-php#810]
**Describe the bug**
Running an action with 8.4 takes ~18 minutes to install whereas the released version (eg 8.3) take about 30s
eg https://github.com/open-telemetry/opentelemetry-php/actions/runs/7191304721/job/19585781470
It seems exceptionally slow, and I'd happily use a pre-built version from earlier (if it's building from source each time?)

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
8.4

**To Reproduce**
```
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
        coverage: xdebug
        tools: php-cs-fixer
        extensions: "ast, grpc, protobuf"
```

**Expected behavior**
To complete in a reasonable time

**Screenshots/Logs**
![Screenshot from 2024-01-12 16-30-58](https://github.com/shivammathur/setup-php/assets/4978962/dc7dd57b-84a5-4323-91f4-69717d99e54c)

**Additional context**

**Are you willing to submit a PR?**
Yes
