### ISSUE TITLE
Add support for GitHub tokens

### ISSUE THREAD

**Issue by skyzyx** [shivammathur/setup-php#815]
**Describe the feature**
Add support for:

```yaml
with:
  token: ${{ secrets.GITHUB_TOKEN }}
```

**Version**
- [X] I have checked releases, and the feature is missing in the latest patch version of `v2`.

**Underlying issue**
The action does not support passing a valid GitHub token into the action.

**Describe alternatives**
None. It would require using a different action, or writing one from scratch.

**Additional context**
We have GitHub Enterprise Server, and use self-hosted GitHub Actions runners. We regularly hit the GitHub API rate limits when using this action.

**Are you willing to submit a PR?**
I don't know JavaScript, so I cannot.

**Comment by shivammathur** [comment]
@skyzyx 

Try setting the `GITHUB_TOKEN` env in the setup-php step.

```yml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.3'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
