### ISSUE TITLE
The PHP version is not updated to latest release

### ISSUE THREAD

**Issue by imahmood** [shivammathur/setup-php#817]
**Describe the bug**
The PHP version is not updated to 8.2.15 using `update: true`

**Version**
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
```
runs-on: ubuntu-latest
```

**PHP versions**
8.2

**To Reproduce**
```
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.2'
    coverage: xdebug
  env:
    update: true
```

**Expected behavior**
```
==> Setup PHP
✓ PHP Installed PHP 8.2.15
```

**Screenshots/Logs**
```
==> Setup PHP
✓ PHP Installed PHP 8.2.14
```
