### ISSUE TITLE
Broken on macos-13

### ISSUE THREAD

**Issue by TimWolla** [shivammathur/setup-php#818]
**Describe the bug**

On macos-13, the action does not properly set up PHP.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

macos-13

**PHP versions**

8.2

**To Reproduce**

```yml
name: Test

on: push

jobs:
  test:
    runs-on: macos-13
    strategy:
      matrix:
        php:
          - "8.2"
    steps:
    - uses: actions/checkout@v4
    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php }}"
    - run: php -i
```

**Expected behavior**

I expected to see phpinfo output.

**Screenshots/Logs**

```
dyld[7166]: Library not loaded: @loader_path/../../../../opt/libavif/lib/libavif.16.dylib
  Referenced from: <D4737928-EC45-32C9-A9BD-43D5E8FD202D> /usr/local/Cellar/gd/2.3.3_6/lib/libgd.3.dylib
  Reason: tried: '/usr/local/Cellar/gd/2.3.3_6/lib/../../../../opt/libavif/lib/libavif.16.dylib' (), '/usr/local/lib/libavif.16.dylib' (), '/usr/lib/libavif.16.dylib' (no such file, not in dyld cache)
/Users/runner/work/_temp/3bd675c7-c270-4110-a565-99bda7e36ebb.sh: line 1:  7166 Abort trap: 6           php -i
Error: Process completed with exit code 134.
```

**Additional context**

https://github.com/TimWolla/setup-php-mac/actions/runs/7898005500/job/21554567205

**Are you willing to submit a PR?**

I don't have any macOS knowledge, thus unfortunately not.
