### ISSUE TITLE
php-version parameter is not respected on 8.3.x

### ISSUE THREAD

**Issue by Cadienvan** [shivammathur/setup-php#820]
**Describe the bug**
Whenever I put an 8.3.x version, the action always tries to install 8.3.3 instead of the given one, causing an issue.

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [x] Self Hosted

**Operating systems**
Amazon Linux

**PHP versions**
8.3.1

**To Reproduce**
```
           - name: setup php
              uses: shivammathur/setup-php@2.29.0
              with:
                  php-version: '8.3.1'
                  extensions: ${{ env.PHP_EXTENSIONS }}
              env:
                  runner: self-hosted
```

**Expected behavior**
setup-php should install 8.3.1

**Screenshots/Logs**
![Screenshot 2024-02-16 alle 12 41 06](https://github.com/shivammathur/setup-php/assets/5492927/002405bb-5b04-4aa0-ade5-620652827b3d)

**Additional context**

**Are you willing to submit a PR?**
