### ISSUE TITLE
setup fails with libicuio.74.dylib error

### ISSUE THREAD

**Issue by stovak** [shivammathur/setup-php#824]
**Describe the bug**

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
currently just using MacOS-latest

**PHP versions**
7.4, 8.2, 8.3

**To Reproduce**
```yaml
  functional:
    runs-on: ${{ matrix.operating-system }}
    name: Functional testing matrix - PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    if: ${{ github.repository_owner == 'pantheon-systems' }}
    strategy:
      matrix:
        operating-system: [ 'macos-latest' ]
        php-versions: [ '7.4', '8.2', '8.3' ]
      max-parallel: 1
```

**Expected behavior**
As recently as last week, these tests were running fine. Something must have changed with home-brew.

**Screenshots/Logs**
```
dyld[4587]: Library not loaded: '@loader_path/../../../../opt/icu4c/lib/libicuio.74.dylib'
  Referenced from: '/usr/local/Cellar/php@8.2/8.2.***6_***/bin/php'
  Reason: tried: '/usr/local/Cellar/php@8.2/8.2.***6_***/bin/../../../../opt/icu4c/lib/libicuio.74.dylib' (no such file), '/usr/local/lib/libicuio.74.dylib' (no such file), '/usr/lib/libicuio.74.dylib'
```

**Additional context**

**Are you willing to submit a PR?**
yes. No idea how to fix.
