### ISSUE TITLE
Apple ARM GitHub runners fail on PHP

### ISSUE THREAD

**Issue by Lewiscowles1986** [shivammathur/setup-php#825]
**Describe the bug**

https://github.com/pact-foundation/pact-php/pull/497

(in fact lots of recent runs) which use this, error when trying to setup php

**Version**
- [X] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1` (no data)

**Runners**
- [X] GitHub Hosted
- [ ] Self Hosted (no data)

**Operating systems**

MacOS, ARM

**PHP versions**

8.1, 8.2, 8.3

**To Reproduce**

```
name: Code Analysis & Test

on:
  push: 
test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: sockets, curl, zip, ffi
          php-version: 8.2
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


```

**Expected behavior**

No warnings about dylib

**Screenshots/Logs**

https://github.com/pact-foundation/pact-php/actions/runs/8074546373/job/22060026690?pr=494

**Additional context**

As your job passes, I never thought about it twice, but looking at the logs, it seems to be the root cause.

**Are you willing to submit a PR?**

If it stays open long enough. Watching failing builds is making my eye twitch

From https://github.com/pact-foundation/pact-php/pull/497
