### ISSUE TITLE
Unable to load dynamic library zip.so

### ISSUE THREAD

**Issue by lackovic10** [shivammathur/setup-php#831]
**Describe the bug**
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'zip.so' (tried: /usr/lib/php/20220829/zip.so (libzip.so.4: cannot open shared object file: No such file or directory), /usr/lib/php/20220829/zip.so.so (/usr/lib/php/20220829/zip.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Version**
- [x] `v2`

**Runners**
- [x] GitHub Hosted

**Operating systems**
`base-default` (should be `ubuntu-latest`)

**PHP versions**
`8.2`

**To Reproduce**
```
- name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: none, igbinary, redis, apcu, gd, bcmath, mbstring, SimpleXml, curl, dom, tokenizer, xml, xmlwriter, opcache, fileinfo, xmlreader, intl, mysqli, sockets, iconv
```

**Expected behavior**
`✓ zip Enabled`
