### ISSUE TITLE
Ioncube error using php 8.1

### ISSUE THREAD

**Issue by mauro-nigrele-wpromote** [shivammathur/setup-php#840]
**Describe the bug**
 Can't get Ioncube loader installed properly with PHP 8.1

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Default . Not specified (linux I guess)

**PHP versions**
8.1

**To Reproduce**
`
    steps:
      -   uses: actions/checkout@v2
      -   run: git fetch --prune --unshallow

      -   name: Load php 8.1
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            extensions: ioncube
          env:
            fail-fast: true
`
**Expected behavior**
PHP 8.1 with IonCube Loader is installed

**Screenshots/Logs**
````
Run shivammathur/setup-php@v2
  with:
    php-version: 8.1
    extensions: ioncube
    ini-file: production
  env:
    WEBROOT_PATH: /home/xxxx/xxxx-11
    REMOTE_HOME: /home/xxxx/
    fail-fast: true
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v[2](https://github.com/visiture-dev/lee-michaels/actions/runs/8971980259/job/24638933460#step:6:2)/src/scripts/run.sh
```

==> Setup PHP
✓ PHP Updated to PHP 8.1.27

==> Setup Extensions
✗ ioncube Could not install ioncube on PHP 8.1.2[7](https://github.com/visiture-dev/lee-michaels/actions/runs/8971980259/job/24638933460#step:6:7)
Error: The process '/usr/bin/bash' failed with exit code 1`

**Additional context**
N/A

**Are you willing to submit a PR?**
N/A
