### ISSUE TITLE
Could not install `decimal` extension on PHP 8.3.7

### ISSUE THREAD

**Issue by 2kai** [shivammathur/setup-php#845]
**Describe the bug**
I'd like to use `decimal` extension in GitHub Actions workflow but it couldn't be installed with the Setup PHP action. It is related to PHP 8.3.7 only, lower versions worked well.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

`ubuntu-latest`

**PHP versions**

`8.3.7`

**To Reproduce**

```yaml
steps:
  - name: Setup PHP
    uses: shivammathur/setup-php@v2
    with:
      php-version: '8.3'
      extensions: decimal
```

**Expected behavior**

`decimal` extension is successfully installed

**Screenshots/Logs**

```
==> Setup PHP
✓ PHP Installed PHP 8.3.7

==> Setup Extensions
✗ decimal Could not install decimal on PHP 8.3.7
```

**Additional context**

**Are you willing to submit a PR?**

Not yet.
