### ISSUE TITLE
Unreleased php version is used 

### ISSUE THREAD

**Issue by aurimasrim** [shivammathur/setup-php#849]
**Describe the bug**
We noticed today that our CI started to fail even though we haven't made any changes.
We found that the CI step is trying to install PHP version 8.3.8 even though it has not been officially released yet.
The [tag](https://github.com/php/php-src/releases/tag/php-8.3.8) is released but there's no [package](https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=php8.3&field.status_filter=published&field.series_filter=) yet.
I'm not even sure where it gets this version from.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu 22.04.4 LTS

**PHP versions**
PHP 8.3

**To Reproduce**
```yaml
            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    ini-values: date.timezone=UTC
                    php-version: 8.3
```

**Expected behavior**
Version 8.3.7 is installed

**Screenshots/Logs**
```
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh
==> Setup PHP
✓ PHP Installed PHP 8.3.8
```

**Additional context**

PHP 8.3.8 introduced a bug / BC break https://github.com/php/php-src/issues/14480

**Are you willing to submit a PR?**
