### ISSUE TITLE
Apt package mismatch, outdated packages in setup-php.com/ondrej/php/ubuntu

### ISSUE THREAD

**Issue by dac-humi** [shivammathur/setup-php#863]
**Describe the bug**

With github workflow config:

```yaml
- name: Setup PHP
  uses: shivammathur/setup-php@2.31.1
  with:
      php-version: 8.2
      extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, mysql
      coverage: none
      ini-values: opcache.enable_cli=1, opcache.jit=disable
 ```     
 
 We're running into problems where `gd` and `imagick` fail to install. It happens several times a day. 
 
 We turned on verbose and narrowed the problem. 
 
 As it goes through the process of installing extensions, it switches from one `ppa.launchpad.net/ondrej/php/ubuntu` to another `setup-php.com/ondrej/php/ubuntu` which leads to:
 
```
deb [arch=amd64 signed-by=/usr/share/keyrings/sp-php-keyring.gpg] https://setup-php.com/ondrej/php/ubuntu jammy main
Get:1 https://setup-php.com/ondrej/php/ubuntu jammy InRelease [24.6 kB]
Get:2 https://setup-php.com/ondrej/php/ubuntu jammy/main amd64 Packages [123 kB]
Get:3 https://setup-php.com/ondrej/php/ubuntu jammy/main Translation-en [38.0 kB]
 ...
 The following packages have unmet dependencies:
 php8.2-gd : Depends: php8.2-common (= 8.2.20-2+ubuntu22.04.1+deb.sury.org+1) but 8.2.22-1+ubuntu22.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

Looking carefully at the error:
```
8.2.20-2+ubuntu22.04.1+deb.sury.org+1
8.2.22-1+ubuntu22.04.1+deb.sury.org+1
```

8.2.20 != 8.2.22

We looked into the fallback mirror and it has an outdated package for some of the extensions like gd
```
Package: php8.2-gd
Version: 8.2.20-2+ubuntu22.04.1+deb.sury.org+1
Priority: optional
Section: php
Source: php8.2
Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
Installed-Size: 143 kB
Provides: php-gd
Depends: php-common (>= 1:81~), ucf, php8.2-common (= 8.2.20-2+ubuntu22.04.1+deb.sury.org+1), libc6 (>= 2.4), libgd3 (>= 2.3.3)
Download-Size: 32.9 kB
APT-Sources: https://setup-php.com/ondrej/php/ubuntu jammy/main amd64 Packages
Description: GD module for PHP
 This package provides the GD module(s) for PHP.
 .
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
 open source general-purpose scripting language that is especially suited
 for web development and can be embedded into HTML.
```

Possibly related:

- https://github.com/shivammathur/setup-php/issues/834
- https://github.com/shivammathur/setup-php/commit/2a5212466ca8f626f5b334783f6a2e7438e75326
 
 
 

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted
