### ISSUE TITLE
php: symbol lookup error: php: undefined symbol: crypto_core_ristretto255_scalar_invert

### ISSUE THREAD

**Issue by serzhik** [shivammathur/setup-php#864]
**Describe the bug**
I got error `php: symbol lookup error: php: undefined symbol: crypto_core_ristretto255_scalar_invert` on Setup Tools.
The same configuration worked with PHP 8.3.6 a week ago. Now I see an error message and PHP is 8.3.8

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [ ] GitHub Hosted
- [x] Self Hosted

**Operating systems**

**PHP versions**
8.3 (Issue with 8.3.8. It worked with 8.3.6)

**To Reproduce**
Configuration:

```
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
```

**Expected behavior**
No issues

**Screenshots/Logs**
<img width="732" alt="image" src="https://github.com/user-attachments/assets/e6963787-1297-4ddc-8776-fa965b2b009f">

**Additional context**
It worked with PHP 8.3.6 but does not work with PHP 8.3.8

**Are you willing to submit a PR?**
No

**Comment by shivammathur** [comment]
@serzhik 

Please try running it again with `update: true` input, and `runner: self-hosted` env if you are using a self-hosted runner. It should install PHP 8.3.10 now.

```yaml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.3'
    update:true
  env:
    runner: self-hosted
```

if this is not fixed, make sure the libsodium package is the latest one.

```bash
sudo apt-get update
sudo apt-get install libsodium -y
```

**Comment by shivammathur** [comment]
Please reopen if you are still facing the issue.

**Comment by serzhik** [comment]
```
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
        env:
          update: true
```

It still uses PHP 8.3.8

**Comment by shivammathur** [comment]
Please specify the `runner` env and set it to `self-hosted`.

**Comment by serzhik** [comment]
Issue still exists :(


Configurations:
```
name: magento-deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
        env:
          runner: self-hosted
          fail-fast: true
          update: true
```

Result:
<img width="758" alt="image" src="https://github.com/user-attachments/assets/3847fc07-beaa-40fa-be87-e705b714dd85">
