### ISSUE TITLE
Swoole Install with Pecl

### ISSUE THREAD

**Issue by cesurapp** [shivammathur/setup-php#865]
**Describe the bug**
swoole does not compile with parameters.

**Version**
v2

**Runners**
GitHub Hosted
 
**Operating systems**
Ubuntu-Latest

**PHP versions**
8.3

**To Reproduce**
```
     - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: :xdebug, swoole
          ini-values: sys_temp_dir=${{ runner.temp }}
        env:
          SWOOLE_CONFIGURE_OPTS: --enable-openssl
```
**Expected behavior**
```
PHP Fatal error:  Uncaught Swoole\Coroutine\Http\Client\Exception: you must configure with `--enable-openssl` to support ssl connection when compiling Swoole in /home/runner/work/swoole-bundle/swoole-bundle/src/Client/SwooleClient.php:55
```
