### ISSUE TITLE
Decimal Could not install decimal on PHP 8.3.12

### ISSUE THREAD

**Issue by Mathiasjv** [shivammathur/setup-php#871]
**Describe the bug**

Our CI Pipeline failed today at the afternoon, when i was trying to make some pull request, and after that it hasn't been possible to do anything with the CI, because it can't install the decimal extension.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Ubuntu-latest

**PHP versions**

PHP 8.3.12

**To Reproduce**

```
name: Our-Company

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: uuid, mcrypt, decimal, igbinary
          tools: composer:v2, cs2pr
          coverage: pcov
          ini-values: short_open_tag=Off
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cache/composer/files
            ./.php-cs-fixer.cache
            ./packages/our-company/shared/.cache
            ~/.npm
          key: shared-${{ matrix.php }}-${{ github.sha }}
          restore-keys: |
            shared-${{ matrix.php }}-
            shared-

      - name: Install dependencies
        working-directory: ./packages/our-company/shared
        run: composer install
```

I have called our company "our-company" because it's not relevant in this particular setup

**Expected behavior**

It should continue our pipeline so it can be possible if all standards are met, then it should be possible to merge to our master (Monorepo)

**Screenshots/Logs**

![Skærmbillede 2024-10-11 kl  01 04 49](https://github.com/user-attachments/assets/ad57a7c8-8809-4514-86c2-bf9ca07c227b)

**Additional context**

And after we setup php, our next ci is install dependencies, and then i get this error log because of decimal is not installed.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires PHP extension ext-decimal * but it is missing from your system. Install or enable PHP's decimal extension.
  Problem 2
    - Root composer.json requires php-decimal/php-decimal ^1.1 -> satisfiable by php-decimal/php-decimal[v1.1.0].
    - php-decimal/php-decimal v1.1.0 requires ext-decimal ^1.1 -> it is missing from your system. Install or enable PHP's decimal extension.

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/8.3/cli/php.ini
    - /etc/php/8.3/cli/conf.d/10-mysqlnd.ini
    - /etc/php/8.3/cli/conf.d/10-opcache.ini
    - /etc/php/8.3/cli/conf.d/10-pdo.ini
    - /etc/php/8.3/cli/conf.d/[15]-xml.ini
    - /etc/php/8.3/cli/conf.d/20-amqp.ini
    - /etc/php/8.3/cli/conf.d/20-apcu.ini
    - /etc/php/8.3/cli/conf.d/20-ast.ini
    - /etc/php/8.3/cli/conf.d/20-bcmath.ini
    - /etc/php/8.3/cli/conf.d/20-bz2.ini
    - /etc/php/8.3/cli/conf.d/20-calendar.ini
    - /etc/php/8.3/cli/conf.d/20-ctype.ini
    - /etc/php/8.3/cli/conf.d/20-curl.ini
    - /etc/php/8.3/cli/conf.d/20-dba.ini
    - /etc/php/8.3/cli/conf.d/[20]-dom.ini
    - /etc/php/8.3/cli/conf.d/20-enchant.ini
    - /etc/php/8.3/cli/conf.d/20-exif.ini
    - /etc/php/8.3/cli/conf.d/20-ffi.ini
    - /etc/php/8.3/cli/conf.d/20-fileinfo.ini
    - /etc/php/8.3/cli/conf.d/20-ftp.ini
    - /etc/php/8.3/cli/conf.d/20-gd.ini
    - /etc/php/8.3/cli/conf.d/20-gettext.ini
    - /etc/php/8.3/cli/conf.d/20-gmp.ini
    - /etc/php/8.3/cli/conf.d/20-iconv.ini
    - /etc/php/8.3/cli/conf.d/20-igbinary.ini
    - /etc/php/8.3/cli/conf.d/20-imagick.ini
    - /etc/php/8.3/cli/conf.d/20-imap.ini
    - /etc/php/8.3/cli/conf.d/20-intl.ini
    - /etc/php/8.3/cli/conf.d/20-ldap.ini
    - /etc/php/8.3/cli/conf.d/20-mbstring.ini
    - /etc/php/8.3/cli/conf.d/20-mcrypt.ini
    - /etc/php/8.3/cli/conf.d/20-memcache.ini
    - /etc/php/8.3/cli/conf.d/20-mongodb.ini
    - /etc/php/8.3/cli/conf.d/20-msgpack.ini
    - /etc/php/8.3/cli/conf.d/20-mysqli.ini
    - /etc/php/8.3/cli/conf.d/20-odbc.ini
    - /etc/php/8.3/cli/conf.d/20-pcov.ini
    - /etc/php/8.3/cli/conf.d/20-pdo_dblib.ini
    - /etc/php/8.3/cli/conf.d/20-pdo_firebird.ini
    - /etc/php/8.3/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/8.3/cli/conf.d/20-pdo_odbc.ini
    - /etc/php/8.3/cli/conf.d/20-pdo_pgsql.ini
    - /etc/php/8.3/cli/conf.d/20-pdo_sqlite.ini
    - /etc/php/8.3/cli/conf.d/20-pdo_sqlsrv.ini
    - /etc/php/8.3/cli/conf.d/20-pgsql.ini
    - /etc/php/8.3/cli/conf.d/20-phar.ini
    - /etc/php/8.3/cli/conf.d/20-posix.ini
    - /etc/php/8.3/cli/conf.d/20-pspell.ini
    - /etc/php/8.3/cli/conf.d/20-readline.ini
    - /etc/php/8.3/cli/conf.d/20-redis.ini
    - /etc/php/8.3/cli/conf.d/20-shmop.ini
    - /etc/php/8.3/cli/conf.d/20-simplexml.ini
    - /etc/php/8.3/cli/conf.d/20-snmp.ini
    - /etc/php/8.3/cli/conf.d/20-soap.ini
    - /etc/php/8.3/cli/conf.d/20-sockets.ini
    - /etc/php/8.3/cli/conf.d/20-sqlite3.ini
    - /etc/php/8.3/cli/conf.d/20-sqlsrv.ini
    - /etc/php/8.3/cli/conf.d/20-sysvmsg.ini
    - /etc/php/8.3/cli/conf.d/20-sysvsem.ini
    - /etc/php/8.3/cli/conf.d/20-sysvshm.ini
    - /etc/php/8.3/cli/conf.d/20-tidy.ini
    - /etc/php/8.3/cli/conf.d/20-tokenizer.ini
    - /etc/php/8.3/cli/conf.d/20-uuid.ini
    - /etc/php/8.3/cli/conf.d/20-xmlreader.ini
    - /etc/php/8.3/cli/conf.d/20-xmlwriter.ini
    - /etc/php/8.3/cli/conf.d/20-xsl.ini
    - /etc/php/8.3/cli/conf.d/20-yaml.ini
    - /etc/php/8.3/cli/conf.d/20-zip.ini
    - /etc/php/8.3/cli/conf.d/20-zmq.ini
    - /etc/php/8.3/cli/conf.d/[25]-memcached.ini
    - /etc/php/8.3/cli/conf.d/30-ds.ini
    - /etc/php/8.3/cli/conf.d/99-pecl.ini

You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-decimal` to temporarily ignore these required extensions.

```
**Are you willing to submit a PR?**
