### ISSUE TITLE
New PHP Startup error with php 7.0 on ubuntu with oauth extension

### ISSUE THREAD

**Issue by bkdotcom** [shivammathur/setup-php#873]
**Describe the bug**

PHP 7.0 is currently erroring with the oauth extension

script worked 3 weeks ago when last run

appologies if this isn't the place to report this issue

```yml
Run shivammathur/setup-php@v2
  with:
    php-version: 7.0
    extensions: intl, mysqli, oauth
    ini-values: error_reporting=-1, memory_limit=512M, post_max_size=256M, xdebug.mode="coverage,debug,develop"
    coverage: xdebug
    ini-file: production

    - name: Check PHP Version
      run: |
        php -v
        php -r 'echo "curl version: " . curl_version()["version"] . "\n";'
```

> Run php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/201510[12](https://github.com/bkdotcom/PHPDebugConsole/actions/runs/11339885693/job/31618621511#step:5:13)/oauth.so' - /usr/lib/php/20151012/oauth.so: undefined symbol: php_mt_rand_range in Unknown on line 0
PHP 7.0.33-76+ubuntu24.04.1+deb.sury.org+1 (cli) (built: Aug  2 2024 16:02:27) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-76+ubuntu24.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20[15](https://github.com/bkdotcom/PHPDebugConsole/actions/runs/11339885693/job/31618621511#step:5:16)1012/oauth.so' - /usr/lib/php/20151012/oauth.so: undefined symbol: php_mt_rand_range in Unknown on line 0
curl version: 8.5.0

Output from 3 weeks ago when script worked:
(appears to be same versions - sans xdebug and curl versions)

> Run php -v
PHP 7.0.33-76+ubuntu22.04.1+deb.sury.org+1 (cli) (built: Aug  2 2024 16:01:57) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-76+ubuntu22.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.8.1, Copyright (c) 2002-2019, by Derick Rethans
curl version: 7.81.0

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [X] `v2`
- [ ] `v1`

**Runners**

- [X] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

[ubuntu-latest](operating-system: [ubuntu-latest])

**PHP versions**

        php-version: ['5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
      (how to include 8.4 with xdebug?)

[Full workflow/action yml](https://github.com/user-attachments/files/17396871/phpunit.yml.txt)

----

### Related:   PHP 7.2 and 7.3 appear to have changed as well

xdebug has gone from using v3.1.6  to using v3.1.5

I believe 3.1.5 has [this bug](https://bugs.xdebug.org/view.php?id=259)

#### 3 weeks ago

> PHP 7.3.33-**20**+ubuntu22.04.1+deb.sury.org+1 (cli) (**built: Aug  2** 2024 16:18:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.33, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.33-20+ubuntu22.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with **Xdebug v3.1.6**, Copyright (c) 2002-2022, by Derick Rethans
curl version: 7.81.0

#### Yesterday

> PHP 7.3.33-**21**+ubuntu24.04.1+deb.sury.org+1 (cli) (**built: Sep 27** 2024 04:16:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.33, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.33-21+ubuntu24.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with **Xdebug v3.1.5**, Copyright (c) 2002-2022, by Derick Rethans
curl version: 8.5.0
