### ISSUE TITLE
Cannot install PECL Opentelemetry extension

### ISSUE THREAD

**Issue by ajtrichards** [shivammathur/setup-php#878]
**Describe the bug**
I'm trying to install the PECL OpenTelemetry extension but it continually fails. Looking at the open telemetry website this should be available

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Linux - Ubuntu 24.04 and 22.04

**PHP versions**
8.2.24 and 8.3

**To Reproduce**
```
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup PHP 8.2, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        env:
          update: true
        with:
          php-version: '8.2'
          tools: pecl
          extensions: pecl_opentelemetry
```

I've also tried with:
```
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup PHP 8.2, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: '8.2'
          tools: pecl
      - name: Install PECL Opentelemetry
         run: pecl install opentelemetry
```

**Expected behavior**
Installation of PECL Open Telemetry

**Screenshots/Logs**
Output from the GitHub Actions logs:

```
Run shivammathur/setup-php@v2
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh

==> Setup PHP
✓ PHP Installed PHP 8.2.24

==> Setup Extensions
✗ pecl_opentelemetry Could not install pecl_opentelemetry on PHP 8.2.24

==> Setup Tools
✓ composer Added composer 2.8.2
✓ PECL Added PECL 1.10.15

==> Sponsor setup-php
✓ setup-php https://setup-php.com/sponsor
```

**Additional context**
None

**Are you willing to submit a PR?**
n/a

**Comment by ajtrichards** [comment]
It looks like it should have been added using:

```
        name: Setup PHP 8.2, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        env:
          update: true
        with:
          php-version: '8.2'
          tools: pecl
          extensions: opentelemetry
```
