### ISSUE TITLE
Bug: Specifiying patch version of PHP is ignored

### ISSUE THREAD

**Issue by tomocrafter** [shivammathur/setup-php#881]
### Describe the bug

Hi, Thank you for making great github action to install PHP easily.
I found that installing the current latest PHP version `8.3.13` with this action fails and installs `8.3.12` instead.

After debugging for a hour and then found that this action seems drop the patch version from version string when parsing the php-version.
Here: https://github.com/shivammathur/setup-php/blob/ce2f681d2257b1c64228aa701fefa22db84edf4b/src/utils.ts#L69

Could you fix/add feature to make it possible installing precise version down to patch version?

Thank you!

### Version

- [X] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

ubuntu-latest

### PHP versions

8.3.13

### To Reproduce

Run the job below on action:
```yml
      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3.13
          tools: composer
        env:
          GITHUB_TOKEN: ${{ secrets.COMPOSER_AUTH }}
```

### Expected behavior

installs 8.3.13 instead of 8.3.12

### Screenshots/Logs

```
Run shivammathur/setup-php@v2
  with:
    php-version: 8.3.13
    tools: composer
    ini-file: production
  env:
    GITHUB_TOKEN: ***
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh

==> Setup PHP
✓ PHP Installed PHP 8.3.12

==> Setup Tools
✓ composer Added composer 2.8.2

==> Sponsor setup-php
✓ setup-php https://setup-php.com/sponsor
```

### Are you willing to submit a PR?

Yes
