### ISSUE TITLE
Bug: setup php got slower recently

### ISSUE THREAD

**Issue by staabm** [shivammathur/setup-php#891]
### Describe the bug

recently it seems setup-php got a lot slower, and I am not sure whether where to search for the root cause

we see the problem in a few private repositories

### Version

- [X] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

ubuntu-latest

### PHP versions

8.1

### To Reproduce

1:1 workflow:

```
# Various code analysis checks
name: Code Analysis

on:
    pull_request:
        types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
    group: code_analysis-${{github.event_name}}-${{ github.head_ref || github.run_id }} # will be canceled on subsequent pushes in pull requests but not branches
    cancel-in-progress: true

jobs:
    code_analysis:
        if: github.event.pull_request.draft == false

        strategy:
            fail-fast: false
            matrix:
                actions:
                    -   name: 'PHP Linter'
                        run: |
                            composer exec --no-interaction -- parallel-lint application/ config/ library/ public/ scripts/ --exclude library/clxProductNet/ --checkstyle | cs2pr

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest
        timeout-minutes: 2

        steps:
            -   uses: actions/checkout@v4
                with:
                    token: ${{ secrets.PHP_GH_ACTION }}

            - name: Read config.platform.php from composer.json
              id: composer-config
              run: |
                  phpVersion=$(composer config platform.php)
                  echo "platform-php=$phpVersion" >> $GITHUB_OUTPUT

            -   uses: shivammathur/setup-php@v2
                with:
                    # min php-version of the project
                    php-version: ${{ steps.composer-config.outputs.platform-php }}
                    tools: cs2pr, parallel-lint
                    coverage: none

            -   name: disable post-install-cmd in composer.json, which would trigger grunt etc.
                run: composer config scripts.post-install-cmd --unset

            -   run: ${{ matrix.actions.run }}
```

the composer.json looks like
```
{
	"require": {
		"php": "^8.1",
    }
...
}
```

which means the workflow is running on 8.1

### Expected behavior

should be fast, as it was a few weeks ago

### Screenshots/Logs

see the setup task taking ~2 minutes to complete

![grafik](https://github.com/user-attachments/assets/629dca78-44a8-464b-8bed-2114bb804d36)

### Are you willing to submit a PR?

Yes
