### ISSUE TITLE
Bug: Swoole's extension version is ignored

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#896]
### Describe the bug

It ignores specified version and installs latest one.

### Version

- [X] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

Any

### PHP versions

PHP 8.1

### To Reproduce

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: pcov
          ini-values: >-
            display_errors=On,
            date.timezone=UTC,
            pcov.exclude="~(vendor|tests|.phan)~"
          extensions: swoole-5.1.6
          tools: pecl

### Expected behavior

Install version `5.1.6` instead of latest.

### Screenshots/Logs

```
==> Setup PHP
✓ PHP Found PHP 8.1.31

==> Setup Extensions
✓ swoole-6.0.0 Installed and enabled
```

### Are you willing to submit a PR?

No

**Comment by shivammathur** [comment]
@Jeckerson 

Can you test it with ubuntu-22.04 or ubuntu-24.04 and specify this in env in setup-php step.
```yml
  - name: Setup PHP
    uses: shivammathur/setup-php@v2
    with:
      php-version: '8.1'
      coverage: pcov
      ini-values: >-
        display_errors=On,
        date.timezone=UTC,
        pcov.exclude="~(vendor|tests|.phan)~"
      extensions: swoole-5.1.6
      tools: pecl
    env:
      SWOOLE_LIBS: libbrotli-dev
```
