### ISSUE TITLE
Bug: Tool composer-dependency-analyser is not supported

### ISSUE THREAD

**Issue by szepeviktor** [shivammathur/setup-php#897]
### Describe the bug

✗ composer-dependency-analyser Tool composer-dependency-analyser is not supported

```yaml
        -
            name: "Set up PHP"
            uses: "shivammathur/setup-php@2.30.0"
            with:
                php-version: "${{ matrix.php-version }}"
                tools: composer-dependency-analyser
```

### Version

- [X] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

ubuntu-22.04

### PHP versions

8.2

### To Reproduce

https://github.com/szepeviktor/byte-level-care/actions/runs/12501351988/workflow?pr=257

### Expected behavior

composer-dependency-analyser installed

### Are you willing to submit a PR?

Yes
