### ISSUE TITLE
Bug: Unable to install tools specific versions

### ISSUE THREAD

**Issue by deguif** [shivammathur/setup-php#899]
### Describe the bug

When a version is specified on a tool to add during the install, the install script doesn't seem to take the version into account.

### Version

- [X] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

Ubuntu24.04

### PHP versions

PHP 8.4

### To Reproduce

 ```
           - name: 'Setup PHP'
              uses: 'shivammathur/setup-php@v2'
              with:
                  php-version: '8.4'
                  coverage: 'none'
                  extensions: 'json, mbstring, tokenizer'
                  tools: 'composer-normalize:2.28.3, php-cs-fixer:3.66.2'
```

### Expected behavior

The tools below should have been installed with the specified version :
- `composer-normalize` in `2.28.3`
- `php-cs-fixer` in `3.66.2`

### Screenshots/Logs

```
Run shivammathur/setup-php@v2
  with:
    php-version: 8.4
    coverage: none
    extensions: json, mbstring, tokenizer
    tools: composer-normalize:2.28.3, php-cs-fixer:3.66.2
    ini-file: production
/usr/bin/bash /home/runner/work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh

==> Setup PHP
✓ PHP Installed PHP 8.4

==> Setup Extensions
✓ json Enabled
✓ mbstring Enabled
✓ tokenizer Enabled

==> Setup Tools
✓ composer Added composer 2.8.4
✓ composer-normalize Added composer-normalize 2.3.9
✓ php-cs-fixer Added php-cs-fixer 

==> Setup Coverage
✓ none Disabled Xdebug and PCOV

==> Sponsor setup-php
✓ setup-php https://setup-php.com/sponsor
```

### Are you willing to submit a PR?

No
