### ISSUE TITLE
Bug: Imagick extension does not have SVG format.

### ISSUE THREAD

**Issue by laurentmuller** [shivammathur/setup-php#902]
### Describe the bug

From 10 january 2025, the Imagick extension doew not more load the SVG format.

When setup:

```
==> Setup PHP
✓ PHP Installed PHP 8.2.27

==> Setup Extensions
✓ imagick Enabled

==> Setup Tools
✓ composer Added composer 2.8.4

==> Setup Coverage
✓ xdebug Xdebug 3.4.0 enabled as coverage driver

==> Sponsor setup-php
✓ setup-php https://setup-php.com/sponsor
```

In one of my unit test, I use the Imagick within the SVG format. This is the Imagick version:

```
Array
(
    [versionNumber] => 16
    [versionString] => ImageMagick 6.9.12-98 Q16 x86_64 18038 https://legacy.imagemagick.org/
)
```

Add the list of formats:

```
Array
(
   // ....
    [197] => SPARSE-COLOR
    [198] => SR2
    [199] => SRF
    [200] => STEGANO
    [201] => SUN
    [202] => TEXT
    // ....
)
```

We can see that the `SVG` format is not present.

In my local tests, I have the following version:

```
Array
{
    [versionNumber] => 1808
    [versionString] => ImageMagick 7.1.0-18 Q16 x64 2021-12-14 https://imagemagick.org
}
```

### Version

- [X] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

Ubuntu 24.04.1LTS

### PHP versions

PHP 8.2.27

### To Reproduce

```yaml
- name: Install PHP with extensions
    uses: shivammathur/setup-php@v2
    with:
        php-version: '8.2'        
        extensions: imagick
```

### Expected behavior

The Imagick extension must have support for SVG format. 

### Are you willing to submit a PR?

No

**Comment by laurentmuller** [comment]
I have remarked that when installing Imagick, the following package version is downloaded:

```bash
Setting up imagemagick-6.q16 (8:6.9.12.98+dfsg1-5.2build2) ...
```

So I have removed the install Imagick package and set the version for the extension:

```yaml
- name: Install PHP with extensions
    uses: shivammathur/setup-php@v2
    with:
        php-version: '8.2'        
        extensions: imagick-6.q16
```

This work as expected !
