### ISSUE TITLE
Bug: action stuck

### ISSUE THREAD

**Issue by fabio-ivona** [shivammathur/setup-php#904]
### Describe the bug

It seems that the action gets stuck while running

this is the debug log from the workflow:

I've tried to wait several minutes, without any success

any ideas?

### Version

- [x] v2
- [ ] v1

### Runners

Self Hosted

### Operating systems

ubuntu 24.04

### PHP versions

PHP8.4

### To Reproduce

just start a workflow in a self-hosted runner

### Expected behavior

```yml
    steps:

      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        env:
          runner: self-hosted
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          extensions: curl, mbstring, gd, zip, sqlite
          coverage: none

```

### Screenshots/Logs

![Image](https://github.com/user-attachments/assets/81a922ea-48cd-4b5d-b2f4-9adc2511b128)

### Are you willing to submit a PR?

No
