### ISSUE TITLE
Add a revolving "v1" tag

### ISSUE THREAD

**Issue by leofeyer** [shivammathur/setup-php#91]
It seems common practice to add a revolving `v1` tag to GitHub actions, so we can require the current major version instead of `@master`:

**Examples**

```yml
steps:
    - uses: actions/checkout@v1
    - uses: codecov/codecov-action@v1
```

GitHub also recommends this in their documentation:

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-actions#versioning-your-action

I am not sure how much sense a revolving tag makes, especially as it implies more work on your end (deleting and re-adding it upon every new release). Still I wanted to bring it up to hear your thoughts on this. 🙈
