### ISSUE TITLE
Bug: action hangs

### ISSUE THREAD

**Issue by weirdan** [shivammathur/setup-php#912]
### Describe the bug

The action gets stuck after `==> Setup Tools` message

### Version

- [x] v2
- [ ] v1

### Runners

Self Hosted

### Operating systems

Ubuntu 22.04.4 LTS

### PHP versions

I'm installing PHP 8.0

### To Reproduce

```yaml
      - uses: shivammathur/setup-php@verbose
        with:
          php-version: '8.0'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, imagick, xdebug, redis
        env:
          update: true
          runner: self-hosted
```

### Expected behavior

The action should not hang

### Screenshots/Logs

```
==> Setup PHP
Repository ondrej/php already exists
[apt-fast 10:57:56]
[apt-fast 10:57:56]Working... this may take a while.
Reading package lists...
Building dependency tree...
Reading state information...
php8.0-cgi is already the newest version (1:8.0.30-12+ubuntu22.04.1+deb.sury.org+1).
php8.0-cli is already the newest version (1:8.0.30-12+ubuntu22.04.1+deb.sury.org+1).
php8.0-curl is already the newest version (1:8.0.30-12+ubuntu22.04.1+deb.sury.org+1).
php8.0-dev is already the newest version (1:8.0.30-12+ubuntu22.04.1+deb.sury.org+1).
php8.0-fpm is already the newest version (1:8.0.30-12+ubuntu22.04.1+deb.sury.org+1).
php8.0-intl is already the newest version (1:8.0.30-12+ubuntu22.04.1+deb.sury.org+1).
php8.0-mbstring is already the newest version (1:8.0.30-12+ubuntu22.04.1+deb.sury.org+1).
php8.0-mysql is already the newest version (1:8.0.30-12+ubuntu22.04.1+deb.sury.org+1).
php8.0-opcache is already the newest version (1:8.0.30-12+ubuntu22.04.1+deb.sury.org+1).
php8.0-pgsql is already the newest version (1:8.0.30-12+ubuntu22.04.1+deb.sury.org+1).
php8.0-xml is already the newest version (1:8.0.30-12+ubuntu22.04.1+deb.sury.org+1).
php8.0-zip is already the newest version (1:8.0.30-12+ubuntu22.04.1+deb.sury.org+1).
0 upgraded, 0 newly installed, 0 to remove and 62 not upgraded.
update-alternatives: error: no alternatives for php-fpm
✓ xml Enabled
✓ php-config Added php-config 
✓ PECL Added PECL 1.10.12
date.timezone=UTC
memory_limit=-1
xdebug.mode=coverage
opcache.enable=1
opcache.jit_buffer_size=256M
opcache.jit=1235
php-version=8.0.30
✓ PHP Found PHP 8.0.30
==> Setup Extensions
✓ mbstring Enabled
✓ xml Enabled
✓ ctype Enabled
✓ iconv Enabled
✓ intl Enabled
✓ pdo_sqlite Enabled
✓ dom Enabled
✓ filter Enabled
✓ gd Enabled
✓ iconv Enabled
✓ json Enabled
✓ mbstring Enabled
✓ pdo Enabled
✓ imagick Enabled
✓ xdebug Enabled
✓ redis Enabled
==> Setup Tools
```

### Additional context

Refs https://github.com/shivammathur/setup-php/issues/904#issuecomment-2636423780

Seems to be the same as #904 

Disabling tools installation completely (`tools: none`) allows the action to be completed.

### Are you willing to submit a PR?

No

**Comment by shivammathur** [comment]
@weirdan 
Have you setup password-less sudo?
https://github.com/shivammathur/setup-php/wiki/Requirements-for-self-hosted-runners#linuxwsl

**Comment by weirdan** [comment]
@shivammathur yes. GH runner runs under `ubuntu` user who is in the `sudo` group. I also confirmed it by logging in under that user and running `sudo -Es` - it dropped me into root shell and did not ask for a password.

**Comment by shivammathur** [comment]
@weirdan 
Please run your workflow with the `more-verbose` branch and provide me the logs

```
- uses: shivammathur/setup-php@more-verbose
  with:
    php-version: '8.0'
    extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo, imagick, xdebug, redis
  env:
    update: true
    runner: self-hosted
```
