### ISSUE TITLE
Bug: phpunit Could not setup phpunit

### ISSUE THREAD

**Issue by blgastesi** [shivammathur/setup-php#913]
### Describe the bug

The package cannot install `phpunit` no more. 

### Version

- [x] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

`ubuntu-latest`

### PHP versions

`8.1`

### To Reproduce

```
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.1'
    extensions: mbstring, intl
    ini-values: post_max_size=256M, variables_order=EGPCS
    coverage: xdebug
    tools: php-cs-fixer, phpunit
```

### Expected behavior

Being able to install `phpunit`

### Screenshots/Logs

![Image](https://github.com/user-attachments/assets/66db9f03-54fb-4145-8c36-5cf89d5cbf8b)

### Are you willing to submit a PR?

Yes
