### ISSUE TITLE
Bug: setup-php action fails sporadically

### ISSUE THREAD

**Issue by theophileds** [shivammathur/setup-php#914]
### Describe the bug

The setup-php action is failing intermittently with a generic exit code 1 error when trying to setup PHP 8.2. The error occurs randomly, making it difficult to reproduce consistently. The failure appears to be related to PHP server package installation issues.

### Version

- [x] v2
- [ ] v1

### Runners

Self Hosted

### Operating systems

ubuntu22-full-x64

### PHP versions

PHP 8.2

### To Reproduce

```
- name: Setup PHP
  uses: shivammathur/setup-php@2.31.0
  with:
    php-version: '8.2'
    extensions: amqp-1.11.0, gd, gmp, soap, bcmath, apcu, redis-6.0.2, timezonedb-2023.3
    coverage: pcov
  env:
    runner: self-hosted
```

### Expected behavior

==> Setup PHP
PHP Could not setup PHP 8.2
Error: The process '/usr/bin/bash' failed with exit code 1

### Additional context

Similar issues have occurred in the past related to PHP server package failures
The current sporadic nature makes debugging challenging
Looking for ways to:

- Enable more verbose logging
- Specify alternative package repositories
- Get more detailed error information about the package installation process

### Are you willing to submit a PR?

Yes
