### ISSUE TITLE
Setup-PHP slow since moving to ARC

### ISSUE THREAD

**Issue by mason-rogers** [shivammathur/setup-php#922]
**Describe the bug**
Setup-php takes over 2 minutes to setup every time, since moving to ARC.

I previously had a single runner running directly on a Ubuntu 22.04 VPS, but outgrew this and needed automatically scaling runners (alongside the issue of running directly on the node means runs are not ephemeral), but since doing this i've noticed a dramatic decrease in speed.

Supposedly because the apt files are now being destroyed with the runners container. Is there any recommended way to cache this or should I just be mounting the apt cache to the runners so that it persists between runs?

To put it into context, the setup-php runs have gone from 1-5 seconds, to 1:30-3:00 minutes. It feels un-usable and I feel like there is a thing i'm missing for self hosted users

**Version**
v2

**Environment**
Self Hosted - Github Actions ARC running in k3s

**PHP versions**
8.3

**To Reproduce**
```
      - name: Setup PHP
        uses: shivammathur/setup-php@more-verbose
        with:
          php-version: '8.3'
          extensions: soap
        env:
          runner: self-hosted
```

**Expected behavior**
Installation to be cached/quicker in subsequent runs

**Screenshots/Logs**

![Image](https://github.com/user-attachments/assets/4d67ab24-6114-4b84-83ef-1cd6f7d995f3)
[setup-php.log](https://github.com/user-attachments/files/19041406/setup-php.log)

Before ARC:

![Image](https://github.com/user-attachments/assets/09bd6a9b-35eb-4045-bb53-f3c8a5c4c8a4)
