### ISSUE TITLE
Bug: Segfault on Windows with PHP 8.2+ and Xdebug 3.5.0-dev

### ISSUE THREAD

**Issue by clue** [shivammathur/setup-php#923]
### Describe the bug

First off, thanks for this great action, it's been incredibly useful across a larger number of project's I've been involved in personally, keep it up!

At the moment, the `shivammathur/setup-php@v2` action appears to install Xdebug 3.5.0-dev on Windows with PHP 8.2+ by default. While the installation works fine, I'm currently seeing consistent segfaults in a larger number of projects when running PHPUnit.

* Specifically, it looks like there might be some incompatibility using fibers with the latest Xdebug dev version, so this is something that would affect pretty much any newer project using @ReactPHP for instance. This makes it trivial to reproduce in most ReactPHP-based projects (e.g. https://github.com/clue-labs/framework-x/actions/runs/13677666370/job/38241806426).

* Given installation works fine and this error shows up in a later step, I understand this might arguably be out of scope here. I plan to report this to Xdebug as well, but felt it made sense to report here too given this appears to be "broken by default" with the current defaults. Specifically, I didn't introduce any changes on my end recently when the builds started failing on affected versions.

* Currently, this does not seem to affect any PHP version on Linux or any older PHP versions on Windows. This appears to be because they all consistently install the latest release version Xdebug 3.4.1.

* I've tried installing a different Xdebug version by using `extensions: xdebug-stable` and `extensions: xdebug-3.4.1` as per the documentation, but this didn't appear to have any effect as it would still install Xdebug 3.5.0-dev (https://github.com/clue-labs/framework-x/actions/runs/13677730259/job/38242021176#step:3:4). Unless I'm mistaken this did work on Linux a couple of weeks ago (see next point). Am I missing something obvious here?

* I've seen similar issues with PHP 8.4.4 on Linux recently also using Xdebug 3.5.0-dev, but it looks like the action now defaults to installing Xdebug 3.4.1 again (https://github.com/clue/reactphp-redis/pull/173 and https://github.com/clue/reactphp-redis/pull/174). I couldn't locale a changelog describing these changes, so any pointers would be appreciated (it's kind of odd this worked for months, stopped working for a week or two and now seemingly randomly works again).

* I've looked into working around this problem by disabling Xdebug on PHP 8.2+ for Windows only, but I'm not particularly excited about the prospect of going through these changes in all repositories (https://github.com/clue/framework-x/pull/276).

* I guess my problem boils down to this: Should this action install a dev version like Xdebug 3.5.0-dev by default or should it prefer the stable release Xdebug 3.4.1? In either case, how can I override this decision if my project has different requirements?

Thank you!

### Version

- [x] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

Windows Server 2022

### PHP versions

PHP 8.2, PHP 8.3, PHP 8.4

### To Reproduce

```
jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }})
    runs-on: windows-2022
    strategy:
      matrix:
        php:
          - 8.4
          - 8.3
          - 8.2
          - 8.1
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: xdebug-stable # temporarily force stable Xdebug due to segfault with 3.5.0-dev?
          coverage: xdebug
          ini-file: development
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text
```

### Expected behavior

* `extensions: xdebug-stable` or `extensions: xdebug-3.4.1` should install the selected Xdebug version
* Should this action install stable release Xdebug 3.4.1 by default instead of a dev version like Xdebug 3.5.0-dev?

### Screenshots/Logs

```
Run shivammathur/setup-php@v2
  with:
    php-version: 8.4
    extensions: xdebug-stable
    coverage: xdebug
    ini-file: development
"C:\Program Files\PowerShell\7\pwsh.exe" D:\a\_actions\shivammathur\setup-php\v2\src\scripts\run.ps1

==> Setup PhpManager 
√ PhpManager Installed 

==> Setup PHP 
√ PHP Found PHP 8.4.4 

==> Setup Extensions 
√ xdebug Installed and enabled 

==> Setup Tools 
√ composer Added composer 2.8.6 

==> Setup Coverage 
√ xdebug Xdebug 3.5.0-dev enabled as coverage driver 
```

### Are you willing to submit a PR?

Yes
