### ISSUE TITLE
Bug: Could not setup phpunit

### ISSUE THREAD

**Issue by eylemugurel** [shivammathur/setup-php#938]
### Describe the bug

PHP stacks 8.2, 8.3, and 8.4 are unable to setup PHPUnit.

Meanwhile PHP 8.1 stack is setting it up correctly.

### Version

- [x] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

Ubuntu, macOS, Windows

### PHP versions

PHP 8.2, 8.3, 8.4

### To Reproduce
```yml
name: Backend Tests
on: push
jobs:
  test-backend:
    runs-on: ${{matrix.operating-system}}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        php-version: ['8.1', '8.2', '8.3', '8.4']
    steps:
    - name: Configure Git
      run: git config --global core.autocrlf false
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{matrix.php-version}}
        tools: phpunit
    - name: Run Tests
      run: phpunit --configuration test/backend/phpunit.xml
```

### Expected behavior

Relevant PHPUnit versions are expected to be set up.

### Screenshots/Logs

![Image](https://github.com/user-attachments/assets/dbc6bc1d-ad13-4e56-a398-64fc47c82fdf)

### Are you willing to submit a PR?

No
