### ISSUE TITLE
Bug: Hanging Github action for last few days

### ISSUE THREAD

**Issue by robw-raviga** [shivammathur/setup-php#940]
### Describe the bug

On and off over the last few days, some Github actions have started hanging at the setup php step.  Looks like it's paused at the "setup tools" step

I missed one overnight and it eventually timed out after 6 hours 😱.   Trying again sometimes resolves it.

I don't know what other information to provide.

Happens on both Github hosted and my own runners (first thing I did was switch to github hosted in case that was my issue).

### Version

- [x] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

Ubuntu-latest

### PHP versions

8.2

### To Reproduce

```yaml
- name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2, phpunit:10.3.5
          extensions: sqlite
```

### Expected behavior

Usually this step succeeds in less than a minute and the workflow continues

### Screenshots/Logs

![Image](https://github.com/user-attachments/assets/4e295144-dc74-4551-990a-88da775f25f5)

### Are you willing to submit a PR?

No
