### ISSUE TITLE
Bug: setup-php will install mongodb-2.0.0 even though I specify 1.21.0

### ISSUE THREAD

**Issue by leonzu21** [shivammathur/setup-php#941]
### Describe the bug

Hi!

Here's my config in `ci.yml`:

```yaml
- name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: symfony-cli
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mongodb-1.21.0
```

I'm attempting to specify the version of mongodb extension to install, but the step will always install 2.0.0 even though 1.21.0 was added to build cache [here](https://github.com/shivammathur/setup-php/issues/868).

```
Run shivammathur/setup-php@v2
  
/usr/bin/bash /opt/actions-runner/_work/_actions/shivammathur/setup-php/v2/src/scripts/run.sh
==> Setup PHP
✓ PHP Installed PHP 8.3.20
==> Setup Extensions
✓ mbstring Enabled
✓ xml Enabled
✓ ctype Enabled
✓ iconv Enabled
✓ intl Enabled
✓ pdo_sqlite Enabled
✓ mongodb-2.0.0 Installed and enabled
==> Setup Tools
✓ composer Added composer 2.8.6
✓ symfony-cli Added symfony-cli 5.11.0
==> Sponsor setup-php
✓ setup-php https://setup-php.com/sponsor
```

Anyone else encounter this issue?

Thanks!

### Version

- [x] v2
- [ ] v1

### Runners

Self Hosted

### Operating systems

```yaml
runs-on: [ self-hosted, linux, amd64, small ]
```

### PHP versions

PHP 8.3

### To Reproduce

Specify the mongodb extension as follows:
```yaml
name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: symfony-cli
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mongodb-1.21.0
```

### Expected behavior

setup-php should install ext-mongodb 1.21.0

### Are you willing to submit a PR?

Yes
