### ISSUE TITLE
Bug: Sporadic failure with "undefined" is not valid JSON

### ISSUE THREAD

**Issue by Sainan** [shivammathur/setup-php#952]
### Describe the bug

We use this step in GitHub-hosted ARM MacOS runners as they do not have PHP preinstalled, and it seems to be failing every once in a while with this not very helpful error message:
- https://github.com/PlutoLang/Pluto/actions/runs/15092937598/job/42423875962
- https://github.com/PlutoLang/Pluto/actions/runs/15093952455/job/42426154452

### Version

- [x] v2
- [ ] v1

### Runners

GitHub Hosted

### Operating systems

MacOS 14

### PHP versions

Not specified

### To Reproduce

The relevant part of our workflow file:
```yml
  macos-arm64:
    runs-on: macos-14
    steps:
      - uses: shivammathur/setup-php@v2
```

### Expected behavior

Workflow doesn't fail.

### Are you willing to submit a PR?

No
