### ISSUE TITLE
Bug: Failing to install PHP 8.0 and 8.2 (potentially others) due to conflicting PPA keyring signature

### ISSUE THREAD

**Issue by davgothic** [shivammathur/setup-php#953]
### Describe the bug

Hi, were experiencing failures to setup PHP versions 8.0 and 8.2 using this action on self-hosted runners.

The error appears to be:
```
E: Conflicting values set for option Signed-By regarding source https://ppa.launchpadcontent.net/ondrej/php/ubuntu/ jammy: /usr/share/keyrings/ondrej-php-keyring.gpg != 
E: The list of sources could not be read.
```

### Version

- [x] v2
- [ ] v1

### Runners

Self Hosted

### Operating systems

Ubuntu 22.04

### PHP versions

PHP 8.0, PHP 8.2

### To Reproduce

```yaml
name: Test PHP

on:
  workflow_call:

jobs:
  test:
    name: Automated Testing
    runs-on: "self-hosted"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@verbose
        with:
          php-version: 8.2
          coverage: none
        env:
          runner: self-hosted
```

### Expected behavior

The PHP versions specified should be installed and next steps execute.

### Screenshots/Logs

```
==> Setup PHP
ID=ubuntu
VERSION_ID=22.04
VERSION_CODENAME=jammy
deb [arch=amd64 signed-by=/usr/share/keyrings/ondrej-php-keyring.gpg] https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy main
Hit:1 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy InRelease
Reading package lists...
E: Conflicting values set for option Signed-By regarding source https://ppa.launchpadcontent.net/ondrej/php/ubuntu/ jammy: /usr/share/keyrings/ondrej-php-keyring.gpg != 
E: The list of sources could not be read.
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [4387 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2944 kB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1245 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [[127](https://github.com/Gear4music/backend-app-purchase-analytic-forecasting/actions/runs/15137815435/job/42553724320#step:4:128) kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [3255 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1547 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [4540 kB]
Fetched 18.3 MB in 2s (9578 kB/s)
Reading package lists...
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
E: Conflicting values set for option Signed-By regarding source https://ppa.launchpadcontent.net/ondrej/php/ubuntu/ jammy: /usr/share/keyrings/ondrej-php-keyring.gpg != 
E: The list of sources could not be read.
E: Conflicting values set for option Signed-By regarding source https://ppa.launchpadcontent.net/ondrej/php/ubuntu/ jammy: /usr/share/keyrings/ondrej-php-keyring.gpg != 
E: The list of sources could not be read.
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
E: Conflicting values set for option Signed-By regarding source https://ppa.launchpadcontent.net/ondrej/php/ubuntu/ jammy: /usr/share/keyrings/ondrej-php-keyring.gpg != 
E: The list of sources could not be read.
✓ xml Enabled
✓ php-config Added php-config 
✓ PECL Added PECL 1.10.16
✗ PHP Could not setup PHP 8.2
Error: The process '/usr/bin/bash' failed with exit code 1
```

### Are you willing to submit a PR?

Yes
