### ISSUE TITLE
Bug:verbose mode freeze

### ISSUE THREAD

**Issue by ThanatosDi** [shivammathur/setup-php#961]
### Describe the bug

When I run setup-php on my self-hosted, at Setup PHP step freeze until 15 minutes timeout.

### Version

- [ ] v2
- [ ] v1

### Runners

Self Hosted

### Operating systems

Ubuntu 24.04
Ubuntu 20.04

### PHP versions

PHP 8.2

### To Reproduce

```yaml

ConfigChecker:
    runs-on: ['self-hosted','ci','php8.3','config-checker','${{ github.repository }}']
    needs: [SetWorkspace]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP (Debug)
        uses: shivammathur/setup-php@verbose
        timeout-minutes: 15
        with:
          php-version: 8.3
          tools: composer:v2
          extensions: mongodb-1.17.0

      - name: 執行 Config 檢查
        working-directory: ${{ needs.SetWorkspace.outputs.workspace }}
        id: config-check
        run: |
          php artisan config:check --no-progress
```

### Expected behavior

Setup PHP finish

### Screenshots/Logs

```
/usr/bin/bash /_work/_actions/shivammathur/setup-php/verbose/src/scripts/run.sh
force-confnew
Reading package lists...
Building dependency tree...
Reading state information...
apt-transport-https is already the newest version (2.[8](https://github.com/{owner}/{repo}/actions/runs/{runs_id}/job/{job_id}#step:3:9).3).
ca-certificates is already the newest version (20240203).
curl is already the newest version (8.5.0-2ubuntu10.6).
make is already the newest version (4.3-4.1build2).
make set to manually installed.
jq is already the newest version (1.7.1-3build1).
unzip is already the newest version (6.0-28ubuntu4.1).
gcc is already the newest version (4:13.2.0-7ubuntu1).
gcc set to manually installed.
g++ is already the newest version (4:13.2.0-7ubuntu1).
g++ set to manually installed.
gnupg is already the newest version (2.4.4-2ubuntu17.2).
The following additional packages will be installed:
  autotools-dev libmagic-mgc libmagic1t64 m4
Suggested packages:
  autoconf-archive gnu-standards autoconf-doc libtool m4-doc
The following NEW packages will be installed:
  autoconf automake autotools-dev file libmagic-mgc libmagic1t64 m4
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,602 kB of archives.
After this operation, 13.3 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble/main amd64 libmagic-mgc amd64 1:5.45-3build1 [307 kB]
Get:2 http://archive.ubuntu.com/ubuntu noble/main amd64 libmagic1t64 amd64 1:5.45-3build1 [87.2 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble/main amd64 file amd64 1:5.45-3build1 [22.0 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble/main amd64 m4 amd64 1.4.1[9](https://github.com/pi-tw/interview2020/actions/runs/15577176175/job/43864220698#step:3:10)-4build1 [244 kB]
Get:5 http://archive.ubuntu.com/ubuntu noble/main amd64 autoconf all 2.71-3 [339 kB]
Get:6 http://archive.ubuntu.com/ubuntu noble/main amd64 autotools-dev all 20220[10](https://github.com/pi-tw/interview2020/actions/runs/15577176175/job/43864220698#step:3:11)9.1 [44.9 kB]
Get:7 http://archive.ubuntu.com/ubuntu noble/main amd64 automake all 1:1.16.5-1.3ubuntu1 [558 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 1,602 kB in 2s (743 kB/s)
Selecting previously unselected package libmagic-mgc.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 2[11](https://github.com/{owner}/{repo}/actions/runs/{runs_id}/job/{job_id}#step:3:12)33 files and directories currently installed.)
Preparing to unpack .../0-libmagic-mgc_1%3a5.45-3build1_amd64.deb ...
Unpacking libmagic-mgc (1:5.45-3build1) ...
Selecting previously unselected package libmagic1t64:amd64.
Preparing to unpack .../1-libmagic1t64_1%3a5.45-3build1_amd64.deb ...
Unpacking libmagic1t64:amd64 (1:5.45-3build1) ...
Selecting previously unselected package file.
Preparing to unpack .../2-file_1%3a5.45-3build1_amd64.deb ...
Unpacking file (1:5.45-3build1) ...
Selecting previously unselected package m4.
Preparing to unpack .../3-m4_1.4.19-4build1_amd64.deb ...
Unpacking m4 (1.4.19-4build1) ...
Selecting previously unselected package autoconf.
Preparing to unpack .../4-autoconf_2.71-3_all.deb ...
Unpacking autoconf (2.71-3) ...
Selecting previously unselected package autotools-dev.
Preparing to unpack .../5-autotools-dev_20220109.1_all.deb ...
Unpacking autotools-dev (20220109.1) ...
Selecting previously unselected package automake.
Preparing to unpack .../6-automake_1%3a1.16.5-1.3ubuntu1_all.deb ...
Unpacking automake (1:1.16.5-1.3ubuntu1) ...
Setting up libmagic-mgc (1:5.45-3build1) ...
Setting up libmagic1t64:amd64 (1:5.45-3build1) ...
Setting up m4 (1.4.19-4build1) ...
Setting up file (1:5.45-3build1) ...
Setting up autotools-dev (20220109.1) ...
Setting up autoconf (2.71-3) ...
Setting up automake (1:1.16.5-1.3ubuntu1) ...
update-alternatives: using /usr/bin/automake-1.16 to provide /usr/bin/automake (automake) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/automake.1.gz because associated file /usr/share/man/man1/automake-1.16.1.gz (of link group automake) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/aclocal.1.gz because associated file /usr/share/man/man1/aclocal-1.16.1.gz (of link group automake) doesn't exist
Processing triggers for libc-bin (2.39-0ubuntu8.4) ...
RUNNER_TOOL_CACHE=/tmp

==> Setup PHP
Error: The action 'Setup PHP (Debug)' has timed out after [15](https://github.com/{owner}/{repo}/actions/runs/{runs_id}/job/{job_id}#step:3:16) minutes.
```

### Are you willing to submit a PR?

No

**Comment by shivammathur** [comment]
@ThanatosDi Please run the action using `more-verbose` tag and provide me the logs.

**Comment by alistaircol** [comment]
I am also encountering this issue on self hosted Ubuntu runner.

<pre>
Operating System
  Distribution: Ubuntu 22.04.1 LTS
  Architecture: x86_64
</pre>

Last output from setup step before it hangs until runner kills it for timing out:

<pre>
==> Setup PHP
ID=ubuntu
VERSION_ID=22.04
VERSION_CODENAME=jammy
Error: The operation was canceled.
</pre>

```yaml
name: blah

on: [pull_request]

jobs:
  phpstan:
    runs-on: [self-hosted, ubuntu-latest, x64, linux]

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@verbose
        with:
          php-version: '7.4'
          extensions: gd
```

This only happened after this commit: https://github.com/shivammathur/setup-php/commit/27853eb8b46dc01c33bf9fef67d98df2683c3be2
