### ISSUE TITLE
Bug: When bumping from 2.33.0 to 2.34.0 I get: Unable to process command '::add-matcher::/opt/hostedtoolcache/php.json' successfully.

### ISSUE THREAD

**Issue by ruudk** [shivammathur/setup-php#962]
### Describe the bug

With the following:
```yaml
- name: Setup PHP
  uses: shivammathur/setup-php@2.34.0
- name: Setup problem matchers for PHP
  run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
- name: Setup problem matchers for PHPUnit
  run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
```
I'm getting:
```
Run echo "::add-matcher::/opt/hostedtoolcache/php.json"
Error: Unable to process command '::add-matcher::/opt/hostedtoolcache/php.json' successfully.
Error: Could not find file '/opt/hostedtoolcache/php.json'.
```

### Version

- [x] v2
- [ ] v1

### Runners

Self Hosted

### Operating systems

depot-ubuntu-22.04 https://depot.dev

### PHP versions

PHP 8.4

### To Reproduce

x

### Expected behavior

No error. It broke when upgrading from 2.33.0 to 2.34.0

### Are you willing to submit a PR?

Yes
