### ISSUE TITLE
Question: specify  minimum xdebug version / version based on matrix.php-version

### ISSUE THREAD

**Issue by bkdotcom** [shivammathur/setup-php#964]
So....
Xdebug 3.4.3 has sume nasty regressions
https://xdebug.org/updates#:~:text=Fixed%20bugs,Fixed%20bugs

workflow snippet:

```
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']

    steps:
    - name: Install PHP
      uses: shivammathur/setup-php@v2 # https://github.com/marketplace/actions/setup-php-action
      with:
        php-version: ${{ matrix.php-version }}
        extensions: iconv, intl, mysqli, oauth
        ini-values: error_reporting=-1, memory_limit=512M, post_max_size=256M, xdebug.mode="coverage,debug,develop"
        coverage: xdebug
```

a)   tested on a crazy range of php-versions

currently:
 php 5.4 : Xdebug v2.3.3
 php 5.5 : Xdebug v2.5.5
 php 5.6 : Xdebug v2.5.5
 php 7.0 : Xdebug v2.9.0
...
 php 7.4 : Xdebug v3.1.5
 php 8.0 : Xdebug v3.4.3  (Segmentation faults - 3.4.3 does not agree with php 8.0)

How would I go about specifying  >= 2.3.3, >=3.1.5, >=3.4.3  or any version but 3.4.3  ?
