### ISSUE TITLE
Bug: Incorrect rdkafka installed

### ISSUE THREAD

**Issue by rkorebrits-paystack** [shivammathur/setup-php#968]
### Describe the bug

Hi @shivammathur,
First of all, thanks for all the good work! :-)

We are suddenly experiencing issues with the wrong `rdkafka` being installed

|before|after|
|--|--|
|<img src="https://github.com/user-attachments/assets/6686043f-189c-40da-91de-58c4bd988db0">|<img src="https://github.com/user-attachments/assets/8563c75d-9cd5-4c4a-afa5-48a5db0e9639">|

### Version

- [x] v2
- [ ] v1

### Runners

Self Hosted

### Operating systems

`ubuntu-22.04`

### PHP versions

7.1

### To Reproduce

```
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.1
        tools: pecl
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, mysql, mysqli, redis, sockets, rdkafka-4.1.2
```

### Expected behavior

Should install `4.1.2` as listed

### Screenshots/Logs

```
Run composer install -n --prefer-dist
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires enqueue/rdkafka 0.[10](https://github.com/PaystackHQ/legacy-api/actions/runs/15876096098/job/44763956096?pr=2538#step:5:11).4 -> satisfiable by enqueue/rdkafka[0.10.4].
    - enqueue/rdkafka 0.10.4 requires ext-rdkafka ^3.0.3|^4.0 -> it has the wrong version installed (6.0.5).
```

### Are you willing to submit a PR?

No
